Repository magento/merchdocs, pull requests merged in 2019-12, with the labels that each got.

#160 Update data-attributes-product.md
  src/system/data-attributes-product.md
Labels: Progress: approved

#182 update to flat catalog topic
  src/catalog/catalog-flat.md
Labels: 2.3.3, Editorial, Progress: approved

#183 Info to configure shipping origin address
  src/shipping/shipping-label-create.md
Labels: Minor update, Partner: Ziffity, partners-contribution

#180 Updated Currency-Configuration.md
  src/stores/currency-configuration.md
Labels: Minor update, Partner: Webjump, Progress: approved, partners-contribution

#185 Format updates in systems topics folder (part 2)
  src/system/developer-client-restrictions.md
  src/system/developer-tools.md
  src/system/email-communications.md
  src/system/encryption-key.md
  src/system/erp-systems.md
  src/system/file-optimization.md
  src/system/frontend-development-workflow.md
  src/system/index-management-events.md
  src/system/index-management.md
  src/system/integrations.md
  src/system/media-storage-content-delivery-network.md
  src/system/media-storage-database.md
  src/system/permissions-locked-users.md
  src/system/permissions-role-resources.md
  src/system/permissions-user-roles.md
  src/system/permissions-users-all.md
  src/system/permissions.md
Labels: Editorial, Progress: approved

#196 Add Marketpace User Guide to the site search
  Gemfile.lock
  src/_includes/layout/header-scripts.html
Labels: Progress: approved

#195 Update braintree.md
  src/configuration/sales/braintree.md
Labels: Minor update, Partner: Rave Digital, Progress: approved, partners-contribution

#177 Doc added for ASI system configuration
  src/configuration/advanced/system.md
  src/images/images/system-adobe-stock-integration.png
Labels: Major update, Progress: changes requested, asi-1.0

#187 Adobe Stock Integration Overview and Usage documents
  src/_data/b2b/toc/content.yml
  src/_data/ce/toc/content.yml
  src/_data/ee/toc/content.yml
  src/cms/adobe-stock-manage.md
  src/cms/adobe-stock.md
  src/images/images/adobe-stock/filters.png
  src/images/images/adobe-stock/image-details.png
  src/images/images/adobe-stock/ims-login.png
  src/images/images/adobe-stock/licensed-images.png
  src/images/images/adobe-stock/mango.png
  src/images/images/adobe-stock/save-licensed.png
  src/images/images/adobe-stock/save-preview.png
  src/images/images/adobe-stock/search-grid.png
Labels: New topic, Progress: review, asi-1.0

#189 Adobe Stock: expanding on category creation documentation
  src/catalog/category-create.md
  src/images/images/category-content.png
Labels: Major update, asi-1.0

#190 Using Adobe Stock Integration via the WYSIWYG editor Insert Image functionality
  src/cms/editor-insert-image.md
  src/images/images/media-storage.png
Labels: Major update, asi-1.0

#191 Updating media storage docs to add info about Adobe Stock Integration
  src/cms/media-storage.md
  src/images/images/btn-browse.png
  src/images/images/editor-toolbar/btn-insert-edit-image.png
Labels: Major update, Progress: approved, asi-1.0

#192 Expanding page builder image functionality to call out Adobe Stock Integration usage
  src/cms/page-builder-media-image.md
Labels: Minor update, Progress: approved, asi-1.0

#201 [WIP] Format updates in systems topics folder (part 3)
  src/_data/ce/toc/operations.yml
  src/images/images/system-tools-setup-web-config.png
  src/images/images/system-tools-web-setup-admin-account.png
  src/images/images/system-tools-web-setup-advanced-modules-config.png
  src/images/images/system-tools-web-setup-customize-store.png
  src/images/images/system-tools-web-setup-database.png
  src/images/images/system-tools-web-setup-install.png
  src/images/images/system-tools-web-setup-readiness-check.png
  src/system/cache-full-page.md
  src/system/cache-management.md
  src/system/cron.md
  src/system/data-transfer-tax-rates.md
  src/system/email-communications.md
  src/system/erp-systems.md
  src/system/file-optimization.md
  src/system/frontend-development-workflow.md
  src/system/index-management.md
  src/system/integrations.md
  src/system/media-storage-content-delivery-network.md
  src/system/static-file-signature.md
  src/system/support-data-collector.md
  src/system/support-system-report.md
  src/system/support.md
  src/system/system-menu.md
  src/system/template-path-hints.md
  src/system/tools.md
  src/system/translate-inline.md
  src/system/web-setup-extension-manager.md
  src/system/web-setup-module-manager.md
  src/system/web-setup-system-configuration.md
  src/system/web-setup-system-upgrade.md
  src/system/web-setup-wizard.md
  src/system/web-setup.md
Labels: Progress: approved

#186 Magento instead of Magneto
  src/shipping/magento-shipping-attributes.md
Labels: Editorial, Progress: approved, Waiting for response

#194 Update 404.md
  src/404.md
Labels: Partner: Rave Digital, Progress: approved, partners-contribution

#176 DOC-53-CCPA-compliance-for-user-guide
  src/_data/b2b/toc/getting-started.yml
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/getting-started.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/getting-started.yml
  src/_data/ee/toc/marketing.yml
  src/magento/change-log.md
  src/marketing/google-tag-manager.md
  src/marketing/google-tools.md
  src/marketing/google-universal-analytics.md
  src/stores/compliance-ccpa-guide.md
  src/stores/compliance-ccpa.md
  src/stores/compliance-cookie-law.md
  src/stores/compliance-gdpr.md
  src/stores/compliance-industry.md
  src/stores/compliance-payment-services-directive.md
  src/stores/compliance-privacy-google.md
  src/stores/cookie-reference.md
  src/stores/privacy-policy.md
Labels: Major update, New topic, Progress: review

#212 DOC-53-compliance-link-fix
  src/stores/compliance-ccpa-guide.md
Labels: Progress: approved

#209 Update to gift options info
  src/sales/gift-options.md
Labels: Minor update
