Repository magento/merchdocs, pull requests merged in 2019-09, with the labels that each got.

#19 Fixed table formatting
  src/catalog/categories-category-products.md
Labels: bug

#18 Update heading and style formatting
  src/catalog/catalog-menu.md
Labels: Editorial

#32 magento/merchdocs#17: Remove links from headings in topics
  src/catalog/catalog-menu.md
  src/catalog/product-gift-card.md
  src/catalog/search-configuration.md
  src/cms/content-menu.md
  src/cms/pages-core.md
  src/configuration/general/b2b-features.md
  src/customers/customers-menu.md
  src/design/design-menu.md
  src/design/page-layout-standard.md
  src/magento/magento-extensions.md
  src/marketing/event-components.md
  src/marketing/marketing-menu.md
  src/marketing/meta-data.md
  src/marketing/rewards-loyalty.md
  src/marketing/search-terms.md
  src/marketing/seo-best-practices.md
  src/quick-tour/customer-journey.md
  src/reports/bi-essentials-report-builder.md
  src/reports/marketing-reports.md
  src/reports/private-sales-reports.md
  src/reports/reports-menu.md
  src/reports/sales-reports.md
  src/sales/checkout-process.md
  src/sales/sales-menu.md
  src/shipping/carriers.md
  src/shipping/magento-shipping-quick-look.md
  src/stores/configuration-overview.md
  src/stores/x-stores.md
Labels: Editorial

#33 magento/merchdocs#28: Links to Marketplace user docs - 404
  src/magento/magento-marketplace.md
Labels: bug

#36 Fix incorrect UI navigation
  src/catalog/catalog-flat.md
  src/catalog/category-create.md
  src/catalog/category-hidden.md
  src/catalog/category-root.md
  src/catalog/navigation-layered-filterable-attributes.md
  src/catalog/product-create-bundle.md
  src/catalog/product-create-configurable.md
  src/catalog/product-create-downloadable.md
  src/catalog/product-create-grouped.md
  src/catalog/product-create-simple.md
  src/catalog/product-create-virtual.md
  src/catalog/product-gift-card-create.md
  src/catalog/product-price-minimum-advertised-configure.md
  src/catalog/product-translate.md
  src/catalog/swatch-create.md
  src/cms/widget-new-products-list.md
  src/images/images-ee/category-root-ee.png
  src/images/images-ee/category-scheduled-changes.png
  src/images/images-ee/gift-card-account-add-new.png
  src/images/images-ee/marketing-gift-card-accounts-new-information.png
  src/images/images-ee/marketing-gift-card-accounts-new-send.png
  src/images/images-ee/product-create-gift-card-type.png
  src/images/images-ee/product-scheduled-changes.png
  src/images/images-ee/product-workspace-ee.png
  src/images/images/21product-add-bundle.png
  src/images/images/21product-add-configurable.png
  src/images/images/21product-add-downloadable.png
  src/images/images/21product-add-grouped.png
  src/images/images/21product-add-virtual.png
  src/images/images/admin-customer-view.png
  src/images/images/attribute-delete.png
  src/images/images/attribute-new-manage-labels.png
  src/images/images/attribute-new-product.png
  src/images/images/category-root.png
  src/images/images/product-add-simple.png
  src/images/images/product-admin-customer-view.png
  src/images/images/product-attribute-add-new.png
  src/images/images/product-attribute-add-select.png
  src/images/images/product-attribute-add.png
  src/images/images/product-bundle-details.png
  src/images/images/product-create-choose-attribute-set-downloadable.png
  src/images/images/product-create-choose-attribute-set-gift-card.png
  src/images/images/product-create-choose-attribute-set.png
  src/images/images/product-create-store-view-choose.png
  src/images/images/product-details-configurable.png
  src/images/images/product-details-downloadable.png
  src/images/images/product-details-simple.png
  src/images/images/product-edit-save-close.png
  src/images/images/product-grouped-details.png
  src/images/images/product-price-msrp.png
  src/images/images/product-settings.png
  src/marketing/event-update.md
  src/shipping/shipping-label-configure.md
  src/stores/attribute-delete.md
  src/tax/fixed-product-tax-configuration.md
Labels: Editorial, bug

#20 Copyedits to several Basic Config section pages
  src/stores/admin-account.md
  src/stores/admin-session-lifetime.md
  src/stores/admin-signin.md
  src/stores/admin.md
Labels: Editorial

#37 Clean up formats in quick-tour topics folder
  src/quick-tour/attract-customers.md
  src/quick-tour/build-loyalty.md
  src/quick-tour/catalog-page.md
  src/quick-tour/customer-journey.md
  src/quick-tour/customer-retention.md
  src/quick-tour/differentiate-personalize.md
  src/quick-tour/engage.md
  src/quick-tour/home-page.md
  src/quick-tour/increase-average-order-value.md
  src/quick-tour/increase-profitability.md
  src/quick-tour/loyalty-advocacy.md
  src/quick-tour/market-opportunities.md
  src/quick-tour/moment-of-purchase.md
  src/quick-tour/path-to-purchase.md
  src/quick-tour/product-page.md
  src/quick-tour/reduce-ordering-errors.md
  src/quick-tour/search-results.md
  src/quick-tour/self-service-tools.md
  src/quick-tour/shopping-cart.md
  src/quick-tour/success.md
Labels: Editorial

#40 Fixed small typo for MAGEDOC-3614
  src/customers/account-companies.md
Labels: Editorial, small changes

#29 Copyedit
  src/cms/pages-workspace.md
Labels: Editorial, small changes

#34 Update klarna.md
  src/payment/klarna.md
Labels: Editorial, small changes

#38 MAGEDOC-3643 Added link to Access Guidelines.
  src/catalog/navigation-accessibility.md
Labels: documentation, small changes

#39 Fixed small type from MAGEDOC-3614
  src/stores/b2b-features.md
Labels: Editorial, small changes
