Repository magento/merchdocs, pull requests merged in 2019-10, with the labels that each got.

#51 Updates for Inventory 1.1.3
  src/catalog/inventory-product-sources.md
  src/catalog/inventory-sources-disable.md
  src/catalog/inventory-sources.md
  src/images/images/btn-dropdown.png
  src/images/images/inventory/inventory-product-sources-before.png
  src/images/images/stores-inventory-sources-disable.png
Labels: inventory-1.1.3

#55 Fix typos in readme
  README.md
Labels: Editorial, Progress: approved

#54 Update pages-core.md
  src/cms/pages-core.md
Labels: Editorial, Progress: approved, small changes

#43 Update inventory-about-sources-stocks.md
  src/catalog/inventory-about-sources-stocks.md
Labels: Minor update, Progress: approved

#41 Clean up formats in stores topics folder (part 1)
  src/images/images/btn-columns.png
  src/images/images/btn-default-view.png
  src/images/images/btn-save-all-changes.png
  src/stores/admin-account.md
  src/stores/admin-actions-control.md
  src/stores/admin-dashboard.md
  src/stores/admin-email-templates-configure.md
  src/stores/admin-global-search.md
  src/stores/admin-grid-controls.md
  src/stores/admin-grid-layout.md
  src/stores/admin-message-inbox.md
  src/stores/admin-session-lifetime.md
  src/stores/admin-signin.md
  src/stores/admin-workspace.md
  src/stores/admin.md
  src/stores/attribute-date-time-options.md
  src/stores/attribute-delete.md
  src/stores/attribute-product-create.md
  src/stores/attribute-sets.md
  src/stores/attributes-customer-address-templates.md
  src/stores/attributes-customer-address.md
  src/stores/attributes-customer.md
Labels: Editorial, Progress: approved

#59 Update new-price-rule.md
  src/_includes/new-price-rule.md
Labels: Minor update

#65 add descriptions for fixed product tax options
  src/configuration/sales/tax.md
Labels: Progress: review, Technical, internal-dev

#63 Ignore .jekyll-metadata globally
  .gitignore
Labels: Progress: approved

#58 Update dynamic-blocks-price-rules.md
  src/cms/dynamic-blocks-price-rules.md
Labels: Minor update

#66 Amazon Sales Channel updates for 3.0.0
  src/_data/b2b/toc/getting-started.yml
  src/_data/ce/toc/getting-started.yml
  src/_data/ee/toc/getting-started.yml
  src/_includes/amazon-catalog-search-configure.md
  src/_includes/amazon-fulfilled-by-configure.md
  src/_includes/amazon-intelligent-pricing-ceiling-configure.md
  src/_includes/amazon-intelligent-pricing-condition-variances-configure.md
  src/_includes/amazon-intelligent-pricing-floor-price-configure.md
  src/_includes/amazon-intelligent-pricing-price-rule-actions-configure.md
  src/_includes/amazon-listing-preview.md
  src/_includes/amazon-listing-price-configure.md
  src/_includes/amazon-listing-price-intro.md
  src/_includes/amazon-listing-rules-configure.md
  src/_includes/amazon-listing-rules.md
  src/_includes/amazon-order-settings-configure.md
  src/_includes/amazon-order-settings.md
  src/_includes/amazon-price-rule-condition.md
  src/_includes/amazon-price-rules-gen-settings-configure.md
  src/_includes/amazon-pricing-rules-price-adjustment-configure.md
  src/_includes/amazon-product-listing-condition-configure.md
  src/_includes/amazon-standard-price-rule-configure.md
  src/_includes/amazon-stock-quantity-configure.md
  src/_includes/amazon-store-reports.md
  src/_includes/amazon-third-party-listings-configure.md
  src/_includes/amazon-third-party-listings.md
  src/_includes/b2b-business-price-configure.md
  src/configuration/sales-channels.md
  src/configuration/sales-channels/global-settings.md
  src/configuration/services/channels.md
  src/images/images/config-sales-channels.png
  src/images/images/sales-channels/amazon/amazon-listing-price.png
  src/images/images/sales-channels/amazon/config-sales-channel-global-settings.png
  src/magento/change-log.md
  src/sales-channels/amazon/about-amazon-sales-channel.md
  src/sales-channels/amazon/about-listings-and-catalog.md
  src/sales-channels/amazon/add-pricing-rule.md
  src/sales-channels/amazon/amazon-best-practices.md
  src/sales-channels/amazon/amazon-logs-reports.md
  src/sales-channels/amazon/amazon-manually-update-incomplete-listing.md
  src/sales-channels/amazon/amazon-matching-attributes-values.md
  src/sales-channels/amazon/amazon-onboarding-home.md
  src/sales-channels/amazon/amazon-order-details.md
  src/sales-channels/amazon/amazon-pre-setup-tasks.md
  src/sales-channels/amazon/amazon-store-dashboard.md
  src/sales-channels/amazon/amazon-verify-api-key.md
  src/sales-channels/amazon/listing-price.md
  src/sales-channels/amazon/order-settings.md
  src/sales-channels/amazon/sales-channel-settings.md
  src/sales-channels/amazon/store-integration.md
  src/stores/configuration.md
Labels: 3.0.0 Amazon Sales Channel, Major update, New topic, Progress: approved

#45 Clean up formats in stores topics folder (part 2)
  src/_data/b2b/toc/catalog.yml
  src/_data/ce/toc/catalog.yml
  src/_data/ee/toc/catalog.yml
  src/stores/attributes-input-types.md
  src/stores/attributes-product.md
  src/stores/attributes-rating.md
  src/stores/attributes-returns.md
  src/stores/attributes.md
  src/stores/b2b-basics.md
  src/stores/b2b-best-practices.md
  src/stores/b2b-configuration-settings.md
  src/stores/b2b-configure-quotes.md
  src/stores/b2b-features.md
  src/stores/compliance-cookie-law.md
  src/stores/compliance-cookie-restriction-mode.md
  src/stores/compliance-gdpr-google.md
  src/stores/compliance-gdpr.md
  src/stores/compliance-industry.md
  src/stores/compliance-pci.md
  src/stores/configuration-overview.md
  src/stores/configuration.md
  src/stores/contact-us.md
  src/stores/cookie-reference.md
  src/stores/country-options.md
  src/stores/currency-configuration.md
  src/stores/currency-overview.md
  src/stores/currency-symbols.md
  src/stores/currency-update.md
  src/stores/currency.md
  src/stores/locale-options.md
  src/stores/privacy-policy.md
  src/stores/security-admin.md
  src/stores/security-browser-capabilities-detection.md
Labels: Editorial, Progress: review

#68 magento/devdocs#: Fix content in “To disable Page Builder” section
  src/cms/page-builder-setup.md
  src/images/images-ee/config-general-content-management-advanced-content-tools-disable-page-builder-popup.png
Labels: Minor update, Partner: Atwix, Progress: approved, partners-contribution

#80 Update Best Practices
  src/sales-channels/google-ads/google-best-practices.md
Labels: Progress: approved, small changes

#74 Update content-staging.md
  src/cms/content-staging.md
Labels: Editorial, Progress: approved, small changes

#75 Update admin-session-lifetime.md
  src/stores/admin-session-lifetime.md
Labels: Technical, small changes

#76 Update account-company-create.md
  src/customers/account-company-create.md
Labels: Editorial, small changes

#91 📝 update readme with correct optimized build command line invocations
  README.md
Labels: Technical

#92 Small changes 17 11 19
  src/cms/content-staging.md
  src/customers/account-company-create.md
  src/stores/admin-session-lifetime.md
Labels: Progress: approved

#94 Merchdocs-4 SEO Topics - Links to Rewrite Types
  src/marketing/url-rewrite-create.md
Labels: Contribution day, Editorial, Progress: review

#96 Convert HTML tables - system folder
  src/system/action-log-report.md
  src/system/data-attributes-customer.md
  src/system/data-export-criteria.md
  src/system/permissions-role-resources.md
  src/system/permissions-users-all.md
  src/system/web-setup.md
Labels: Contribution day, Editorial, Partner: creativestyle, Progress: review, partners-contribution

#78 Clean up formats in stores topics folder (part 3)
  src/sales/terms-and-conditions.md
  src/stores/security-captcha.md
  src/stores/security-google-recaptcha.md
  src/stores/security-session-validation.md
  src/stores/security-two-factor-authentication-manage.md
  src/stores/security-two-factor-authentication-use.md
  src/stores/security-two-factor-authentication.md
  src/stores/security.md
  src/stores/state-options.md
  src/stores/store-details.md
  src/stores/store-email-addresses.md
  src/stores/store-information.md
  src/stores/store-language-add.md
  src/stores/store-mode-single.md
  src/stores/store-scope-reference.md
  src/stores/store-urls-custom-admin.md
  src/stores/store-urls.md
  src/stores/stores-all-create-store.md
  src/stores/stores-all-create-view.md
  src/stores/stores-all-create-website.md
  src/stores/stores-all-stores.md
  src/stores/stores-all-view-edit.md
  src/stores/stores-attributes-customer.md
  src/stores/stores-menu.md
  src/stores/stores.md
  src/stores/terms-and-conditions.md
  src/stores/websites-stores-views.md
  src/stores/x-stores.md
  src/system/permissions-role-resources.md
Labels: Editorial, Progress: approved

#98 Update catalog-flat.md
  src/catalog/catalog-flat.md
Labels: Partner: Rave Digital, Progress: approved, partners-contribution

#95 Convert HTML tables - shipping folder
  src/shipping/magento-shipping-shipment-workflow.md
  src/shipping/shipping-label-create.md
  src/shipping/shipping-label-package.md
Labels: Contribution day, Editorial, Partner: creativestyle, partners-contribution

#99 Fix options line breaking
  src/stores/admin-actions-control.md
Labels: Editorial, Progress: approved

#97 corrected image link commands
  src/system/data-export-criteria.md
Labels: Progress: approved, internal-dev, small changes

#100 Add rake task to check external links
  rakelib/test.rake
Labels: Progress: approved, Site improvements

#90 MC-21664 Added note about running full text indexer with Elasticsearch.
  src/system/index-management.md
Labels: 2.3.3, Minor update, Progress: approved

#102 Clean up formats in marketing topics folder (part 1)
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/marketing.yml
  src/marketing/customer-engagement.md
  src/marketing/customer-segment-attributes.md
  src/marketing/customer-segment-banner.md
  src/marketing/customer-segment-create.md
  src/marketing/customer-segment-price-rule.md
  src/marketing/customer-segments.md
  src/marketing/email-a-friend.md
  src/marketing/email-company-configuration.md
  src/marketing/email-logo.md
  src/marketing/email-marketing-automation-campaign-automate.md
  src/marketing/email-marketing-automation-campaign-send.md
  src/marketing/email-marketing-automation-contacts.md
  src/marketing/email-marketing-automation-exclusion-rules.md
  src/marketing/email-marketing-automation-studio.md
  src/marketing/email-marketing-automation.md
  src/marketing/email-marketing-campaign-create.md
  src/marketing/email-reminder-rules-configure.md
  src/marketing/email-reminder-rules-create.md
  src/marketing/email-reminder-rules.md
  src/marketing/email-reminder-templates.md
  src/marketing/email-template-configuration.md
  src/marketing/email-template-custom.md
  src/marketing/email-template-footer.md
  src/marketing/email-template-header.md
  src/marketing/email-template-list.md
  src/marketing/email-template-message.md
  src/marketing/engagement-cloud-account-access.md
  src/marketing/engagement-cloud-account-api-users.md
  src/marketing/engagement-cloud-account-details.md
  src/marketing/engagement-cloud-account-transactional-email-users.md
  src/marketing/engagement-cloud-campaign-automate.md
  src/marketing/engagement-cloud-campaign-create.md
  src/marketing/engagement-cloud-campaign-schedule.md
  src/marketing/engagement-cloud-contacts.md
  src/marketing/engagement-cloud-exclusion-rules.md
  src/marketing/engagement-cloud-setup.md
  src/marketing/engagement-cloud.md
  src/marketing/event-components.md
  src/marketing/event-configure.md
  src/marketing/event-create.md
  src/marketing/event-restrict-access.md
  src/marketing/event-restrict-sales.md
  src/marketing/event-ticker.md
  src/marketing/event-update.md
  src/marketing/events-private-sales.md
Labels: Editorial, Progress: approved

#103 magento/merchdocs#71: Image import - must use hardcoded directory
  src/system/data-import-product-images.md
  src/system/data-import.md
Labels: Partner: Atwix, Progress: approved, Technical, partners-contribution

#107 Update the theme gem to use the Jekyll 4
  Gemfile
  Gemfile.lock
Labels: Progress: approved

#106 Clean up formats in marketing topics folder (part 2)
  src/marketing/engagement-cloud-account-api-users.md
  src/marketing/gift-registries.md
  src/marketing/gift-registry-configure.md
  src/marketing/gift-registry-create.md
  src/marketing/gift-registry-information.md
  src/marketing/gift-registry-search.md
  src/marketing/google-adwords.md
  src/marketing/google-content-experiments.md
  src/marketing/google-enhanced-ecommerce.md
  src/marketing/google-tag-manager-create-tag.md
  src/marketing/google-tag-manager-troubleshooting.md
  src/marketing/google-tag-manager.md
  src/marketing/google-tools.md
  src/marketing/google-universal-analytics.md
  src/marketing/invitations-configure.md
  src/marketing/invitations.md
  src/marketing/magento-product-reviews-config.md
  src/marketing/magento-product-reviews-moderate.md
  src/marketing/magento-product-reviews.md
  src/marketing/marketing-menu.md
  src/marketing/markup-tags-links.md
  src/marketing/markup-tags.md
  src/marketing/merchandising.md
  src/marketing/meta-canonical.md
  src/marketing/meta-data.md
  src/marketing/newsletter-configuration.md
  src/marketing/newsletter-queue.md
  src/marketing/newsletter-subscribers.md
  src/marketing/newsletter-template.md
  src/marketing/newsletters.md
  src/marketing/price-rule-cart-scheduled-changes.md
  src/marketing/price-rule-catalog-scheduled-changes.md
  src/marketing/price-rule-discount-first-purchase.md
  src/marketing/price-rule-discount-minimum-purchase.md
  src/marketing/price-rule-multiple-sku.md
  src/marketing/price-rules-cart-buy-x-get-y-free.md
  src/marketing/price-rules-cart-coupon-code-configure.md
  src/marketing/price-rules-cart-coupon-report.md
  src/marketing/price-rules-cart-coupon.md
  src/marketing/price-rules-cart-create.md
  src/marketing/price-rules-cart-free-shipping.md
  src/marketing/price-rules-cart.md
  src/marketing/price-rules-catalog-create.md
  src/marketing/price-rules-catalog.md
Labels: Editorial, Progress: review

#116 Update product-price-special.md
  src/catalog/product-price-special.md
Labels: Editorial, Partner: Balance Internet, Progress: review, partners-contribution

#118 MLEU 2019 - Contribution Day
  src/marketing/url-rewrite-create.md
  src/shipping/magento-shipping-shipment-workflow.md
  src/shipping/shipping-label-create.md
  src/shipping/shipping-label-package.md
  src/system/action-log-report.md
  src/system/data-attributes-customer.md
  src/system/data-export-criteria.md
  src/system/permissions-role-resources.md
  src/system/permissions-users-all.md
  src/system/web-setup.md
Labels: Progress: review
