Repository magento/merchdocs, pull requests merged in 2019-11, with the labels that each got.

#117 magento/merchdocs#: Fix point 2 in “Method 1: Create a Specific Coupon”
  src/marketing/price-rules-cart-coupon.md
Labels: Minor update, Partner: Atwix, Progress: approved, partners-contribution, small changes

#115 Update product-create-configurable.md
  src/catalog/product-create-configurable.md
Labels: Minor update, Partner: Balance Internet, Progress: approved, partners-contribution, small changes

#114 Update pricing-advanced.md
  src/catalog/pricing-advanced.md
Labels: Editorial, Partner: Balance Internet, Progress: approved, partners-contribution, small changes

#113 Update products.md
  src/catalog/products.md
Labels: Editorial, Partner: Balance Internet, Progress: approved, partners-contribution, small changes

#124 Small changes
  src/catalog/pricing-advanced.md
  src/catalog/product-create-configurable.md
  src/catalog/products.md
  src/marketing/price-rules-cart-coupon.md
Labels: Progress: approved

#121 Update product-search-engine-optimization.md
  src/catalog/product-search-engine-optimization.md
Labels: Editorial, Partner: Balance Internet, Progress: approved, partners-contribution

#130 Fix #123 - Update to Placeholder Images topic
  src/catalog/product-image-placeholders.md
Labels: Editorial, Minor update, Progress: review

#131 Fix #126 - update Google API topic
  src/configuration/sales/google-api.md
  src/images/images-ee/config-sales-google-api-google-analytics-ee.png
Labels: Editorial, Minor update, Progress: approved

#128 Added a note on existing GET parameters being removed during redirect…
  src/_includes/url-rewrite-get-params.md
  src/marketing/url-rewrite-category.md
  src/marketing/url-rewrite-cms-page.md
  src/marketing/url-rewrite-custom.md
  src/marketing/url-rewrite-product.md
  src/marketing/url-rewrite.md
Labels: Progress: approved

#132 MAGEDOC-3963-price-rule-custom-options
  src/catalog/settings-advanced-custom-options.md
  src/images/images/price-rule-cart.png
  src/images/images/price-rules-cart-ee.png
  src/images/images/storefront-customizable-option-cart-price-rule.png
  src/images/images/storefront-customizable-option-product-detail.png
  src/marketing/price-rules-cart-create.md
  src/marketing/price-rules-cart.md
Labels: Minor update, Progress: review

#134 Update devdocs-theme and other gems
  Gemfile
  Gemfile.lock
Labels: Progress: approved

#133 Update rake preview tasks to use local config
  .gitignore
  _checks/html_check_hook.rb
  bin/jekyll
  lib/double_slash_check.rb
  rakelib/preview.rake
Labels: Progress: approved, Site improvements

#137 Fix bug in rake preview:xx commands
  Rakefile
  _checks/html_check_hook.rb
  _config.checks.yml
  _config.yml
  rakelib/preview.rake
Labels: Progress: approved

#129 Format updates in systems topics folder (part 1)
  src/_includes/backup-deprecated.md
  src/configuration/sales/amazon-pay.md
  src/payment/amazon-pay-setup.md
  src/system/action-log-archive.md
  src/system/action-log-bulk-actions.md
  src/system/action-log-report.md
  src/system/action-log.md
  src/system/amazon-logs.md
  src/system/backups.md
  src/system/cache-full-page.md
  src/system/cache-management.md
  src/system/cron.md
  src/system/data-advanced-price.md
  src/system/data-attributes-customer.md
  src/system/data-attributes-product.md
  src/system/data-complex.md
  src/system/data-csv.md
  src/system/data-export-criteria.md
  src/system/data-export.md
  src/system/data-import-guidelines.md
  src/system/data-import-history.md
  src/system/data-import-price-tier.md
  src/system/data-import-product-images.md
  src/system/data-import.md
  src/system/data-schedule-export.md
  src/system/data-schedule-import.md
  src/system/data-scheduled-import-export.md
  src/system/data-transfer-configurable-products.md
  src/system/data-transfer-examples.md
  src/system/data-transfer-tax-rates.md
  src/system/data-validation.md
  src/system/system.md
Labels: Editorial, Progress: review

#147 Add missing word
  src/catalog/inventory-bulk-transfer-inventory.md
Labels: Editorial, small changes

#146 Remove duplicate "each"
  src/catalog/swatch-create.md
Labels: Editorial, Progress: approved, small changes

#142 Remove dot
  src/configuration/sales/3d-secure.md
Labels: Editorial, small changes

#141 Fix typo
  src/catalog/product-price-minimum-advertised-logic.md
Labels: Editorial, small changes

#140 Add word "to"
  src/catalog/inventory-product-quantity.md
Labels: Editorial, small changes

#145 Fix text for product pages sitemap XML configuration
  src/configuration/catalog/xml-sitemap.md
Labels: Minor update

#138 documenting rake tasks and optimizations added in #133
  README.md
Labels: Minor update, Technical

#149 Fix link to customer configuration
  src/customers/account-dashboard-company-profile.md
Labels: Editorial, Progress: approved, small changes

#139 MAGEDOC-3872-add-import-option-sorting-info
  src/_data/b2b/toc/operations.yml
  src/_data/ce/toc/operations.yml
  src/_data/ee/toc/operations.yml
  src/catalog/product-create-bundle.md
  src/images/images/product-bundle-items-move.png
  src/images/images/product-bundle-section-move.png
  src/images/images/product-bundle-values-export-data.png
  src/images/images/product-bundle-values-position-parameter.png
  src/system/data-transfer-bundle-products.md
  src/system/data-transfer-examples.md
Labels: Progress: approved

#151 Add site switcher to the header
  Gemfile.lock
Labels: Progress: approved, Site improvements

#154 Fix copyright-notice
  src/design/copyright-notice.md
Labels: Minor update, Partner: Webjump, Progress: approved, partners-contribution

#150 Remove extra ending `</td>` from vat.md
  src/tax/vat.md
Labels: Editorial, Progress: approved, small changes

#156 [site] Add 'rake index'
  Rakefile
  _config.index.yml
  _config.yml
  _plugins/algolia.rb
  rakelib/build.rake
Labels: Progress: approved, Site improvements

#153 PHP update for reCAPTCHA setup
  src/configuration/security/google-recaptcha.md
  src/stores/security-google-recaptcha.md
Labels: Minor update, Progress: approved, small changes

#157 Fix Alter path to access correct page.
  src/tax/display-settings.md
Labels: Minor update, Partner: Webjump, Progress: approved, partners-contribution, small changes

#143 Root categories cannot be set per store view
  src/catalog/category-root.md
Labels: Minor update

#144 Fix duplicate explanation of setting
  src/stores/attribute-product-create.md
Labels: Minor update

#155 MAGEDOC-3609-improvements-for-email-templates
  src/cms/widget-static-block.md
  src/marketing/email-template-configuration.md
  src/marketing/email-template-custom.md
  src/marketing/email-template-header.md
  src/marketing/email-templates.md
  src/marketing/markup-tags.md
  src/marketing/sales-email-configure.md
  src/marketing/variables-custom.md
  src/marketing/variables-predefined.md
  src/marketing/variables-reference.md
  src/marketing/variables.md
Labels: Minor update, Progress: review

#159 Small changes
  src/catalog/inventory-bulk-transfer-inventory.md
  src/catalog/inventory-product-quantity.md
  src/catalog/product-price-minimum-advertised-logic.md
  src/catalog/swatch-create.md
  src/configuration/catalog/xml-sitemap.md
  src/configuration/sales/3d-secure.md
  src/configuration/security/google-recaptcha.md
  src/customers/account-dashboard-company-profile.md
  src/stores/security-google-recaptcha.md
  src/tax/display-settings.md
  src/tax/vat.md
Labels: Progress: approved

#136 Update the enabling inventory topic
  src/catalog/inventory.md
Labels: Minor update, Progress: approved

#165 Add raw for sample code
  src/marketing/variables-custom.md
Labels: Editorial, Progress: approved

#164 Fix navigation for PayPal pages
  src/_data/b2b/toc/getting-started.yml
  src/_data/ce/toc/getting-started.yml
  src/_data/ee/toc/getting-started.yml
Labels: Minor update, Progress: approved

#163 Fix callout
  src/catalog/inventory.md
  src/configuration/sales/paypal-payments-advanced.md
Labels: Editorial, Progress: approved, small changes

#161 Updated PHP note - reCAPTCHA
  src/configuration/security/google-recaptcha.md
  src/stores/security-google-recaptcha.md
Labels: Minor update, Progress: approved

#162 Fix code format
  src/marketing/email-template-list.md
Labels: Editorial, Progress: approved

#167 MAGEDOC-3609-improvements-for-email-templates
  src/marketing/variables-custom.md
Labels: Progress: approved

#166 Deleted unnecessary images
  requisition-list-add-from-order.png
  src/customer-account-my-downloadable-products.png
Labels: Editorial, Progress: approved

#170 [site] Add 'mdl' to the bundle
  .mdlrc
  Gemfile
  Gemfile.lock
  bin/mdl
  rakelib/check.rake
  rakelib/test.rake
Labels: Progress: approved, Site improvements

#172 Add MBI to search and update site switcher
  Gemfile.lock
  src/_includes/layout/header-scripts.html
Labels: Progress: approved, Site improvements

#173 Mark up "Dynamic Blocks" header
  src/cms/content-menu.md
Labels: Editorial, Progress: approved, small changes

#175 Removed mid-sentence break
  src/catalog/inventory-about-sources-stocks.md
Labels: Editorial, Progress: approved, small changes

#179 Small changes to master
  src/catalog/inventory-about-sources-stocks.md
  src/cms/content-menu.md
  src/configuration/sales/paypal-payments-advanced.md
Labels: Progress: approved
