Repository magento/merchdocs, pull requests merged in 2020-02, with the labels that each got.

#310 Adding conditional to metadata for EE
  src/marketing/create-new-rec.md
  src/marketing/edit-existing-rec.md
  src/marketing/product-recommendations.md
  src/marketing/product-recs-limitations.md
  src/marketing/recommendation-best-practices.md
  src/marketing/recommendation-metrics.md
Labels: 2.3.4, Progress: approved, bug, internal-dev

#308 Add copyright to source code
  Rakefile
  _checks/html_check_hook.rb
  _plugins/edition.rb
  _plugins/last-modified-at.rb
  lib/converter.rb
  lib/double_slash_check.rb
  lib/link-checker.rb
  rakelib/build.rake
  rakelib/check.rake
  rakelib/preview.rake
  rakelib/test.rake
  rakelib/update.rake
Labels: Progress: approved, legal, maintenance

#309 Update bundled gem dependencies
  Gemfile.lock
Labels: Progress: approved, maintenance

#311 CAPTCHA Clarification
  src/configuration/advanced/admin.md
  src/configuration/customers/customer-configuration.md
  src/images/images-b2b/config-customers-customer-configuration-captcha.png
  src/images/images-ee/config-customers-customer-configuration-captcha.png
  src/images/images/config-customers-customer-configuration-captcha.png
  src/stores/security-captcha.md
Labels: Major update, Progress: approved, internal-dev

#312 Updated Flat Catalog topics
  src/catalog/catalog-flat.md
  src/catalog/navigation-product-listings.md
  src/configuration/catalog/catalog.md
Labels: Minor update, Progress: approved, internal-dev

#302 quote-price-negotiation.md
  src/quick-tour/build-loyalty.md
  src/sales/quote-price-negotiation.md
Labels: Progress: approved

#297 Improves instructions on how to create VM attributes
  src/catalog/category-product-rules.md
Labels: Minor update, Partner: Maginus, partners-contribution

#294 Updated table formatting and added entries for Content > Elements
  src/system/permissions-role-resources.md
Labels: 2.3.4, Minor update, Progress: approved, bug, internal-dev

#299 GH #286 Updated Cart Price Rule topic
  src/marketing/price-rules-cart-create.md
Labels: Minor update, Progress: review, internal-dev

#313 Updating limitations to mention headless implementation
  src/marketing/product-recs-limitations.md
Labels: 2.3.3, Progress: approved, internal-dev

#306 Added field description to data-attributes-product
  src/system/data-attributes-product.md
Labels: Minor update, Progress: approved, internal-dev

#292 Advanced Reporting Base Currency Limitation
  src/reports/advanced-reporting.md
Labels: Minor update, Progress: approved, internal-dev

#305 Format updates in catalog topics folder (part 1)
  src/catalog/attribute-best-practices.md
  src/catalog/catalog-flat.md
  src/catalog/catalog-images-video.md
  src/catalog/catalog-menu.md
  src/catalog/catalog-price-scope.md
  src/catalog/catalog-scope.md
  src/catalog/catalog-shared-assign-companies.md
  src/catalog/catalog-shared-category-permissions-update.md
  src/catalog/catalog-shared-create.md
  src/catalog/catalog-shared-custom-pricing-update.md
  src/catalog/catalog-shared-general-information-update.md
  src/catalog/catalog-shared-manage.md
  src/catalog/catalog-shared-price-scope.md
  src/catalog/catalog-shared-pricing-structure.md
  src/catalog/catalog-shared-product-add.md
  src/catalog/catalog-shared-product-in.md
  src/catalog/catalog-shared-product-selection-update.md
  src/catalog/catalog-shared.md
  src/catalog/catalog-urls-dynamic-media.md
  src/catalog/catalog-urls.md
  src/catalog/categories-category-products.md
  src/catalog/categories-content-settings.md
  src/catalog/categories-custom-design.md
  src/catalog/categories-display-settings.md
  src/catalog/categories-search-engine-optimization.md
  src/catalog/categories.md
  src/catalog/category-best-practices.md
  src/catalog/category-create.md
  src/catalog/category-hidden.md
  src/catalog/category-modify.md
  src/catalog/category-permissions.md
  src/catalog/category-product-rules.md
  src/catalog/category-products-sort.md
  src/catalog/category-root.md
  src/catalog/category-scheduled-changes.md
  src/configuration/general/advanced-reporting.md
  src/customers/account-company-update.md
Labels: Editorial, Progress: approved, internal-dev

#318 [DOKU] Update documentation regarding Magento2 issue #25674
  src/catalog/search-elasticsearch.md
  src/configuration/catalog/catalog.md
  src/images/images/config-catalog-catalog-search-elasticsearch-1.png
  src/images/images/config-catalog-catalog-search-elasticsearch.png
Labels: Minor update, Progress: approved

#317 Criteria for Reorder functionality added
  src/sales/reorders-allow.md
Labels: Partner: Ziffity, Progress: review, partners-contribution

#303 Update ASC intelligent repricing text
  src/_includes/amazon-intelligent-pricing-ceiling-configure.md
  src/_includes/amazon-intelligent-pricing-floor-price-configure.md
  src/_includes/amazon-pricing-rules-price-adjustment-configure.md
  src/sales-channels/amazon/floor-price.md
  src/sales-channels/amazon/intelligent-repricing-rules.md
  src/sales-channels/amazon/optional-ceiling-price.md
  src/sales-channels/amazon/price-adjustment.md
  src/sales-channels/amazon/pricing-products.md
Labels: Minor update, Progress: approved, internal-dev

#315 Gh#265 update tax partner reference
  src/system/data-transfer-tax-rates.md
Labels: Minor update, Progress: approved

#322 Shared Catalog Navigation Path
  src/catalog/catalog-shared-pricing-structure.md
Labels: Progress: review

#335 Markdown linting: MD001
  _checks/styles/style-rules-prod
  src/sales-channels/amazon/price-rule-examples.md
Labels: Editorial, Site improvements

#336 Enable markdown linting PR test in GitHub actions
  .github/workflows/main.yml
Labels: Site improvements

#324 Enforce ruby version for ruby version managers
  .ruby-version
Labels: Progress: review, maintenance

#321 Format updates in catalog topics folder (part 2)
  src/_includes/inventory-cli.md
  src/catalog/inventory-about-order-status-reservation.md
  src/catalog/inventory-about-product-types.md
  src/catalog/inventory-about-sources-stocks.md
  src/catalog/inventory-about-ssa.md
  src/catalog/inventory-backorders.md
  src/catalog/inventory-bulk-assign-sources.md
  src/catalog/inventory-bulk-transfer-inventory.md
  src/catalog/inventory-bulk-unassign-sources.md
  src/catalog/inventory-configure-distance-priority.md
  src/catalog/inventory-configure-inventory-management.md
  src/catalog/inventory-configure-source-priority.md
  src/catalog/inventory-expand-restructure-inventory.md
  src/catalog/inventory-get-started.md
  src/catalog/inventory-import-export.md
  src/catalog/inventory-manage-inventory-quantities.md
  src/catalog/inventory-merchant-type.md
  src/catalog/inventory-migration.md
  src/catalog/inventory-options-global.md
  src/catalog/inventory-orders-shipment.md
  src/catalog/inventory-product-alert-run-settings.md
  src/catalog/inventory-product-alerts.md
  src/catalog/inventory-product-quantity.md
  src/catalog/inventory-product-sources.md
  src/catalog/inventory-product-stock-options.md
  src/catalog/inventory-shipment-create.md
  src/catalog/inventory-sources-add.md
  src/catalog/inventory-sources-disable.md
  src/catalog/inventory-sources.md
  src/catalog/inventory-stock-add.md
  src/catalog/inventory-stock-delete.md
  src/catalog/inventory-stock-message-scenarios.md
  src/catalog/inventory-stock-priority.md
  src/catalog/inventory-stock.md
  src/catalog/inventory.md
Labels: Editorial

#333 Create COMMUNITY_ISSUE_TEMPLATE.md
  .github/COMMUNITY_ISSUE_TEMPLATE.md
Labels: Site improvements

#323 Base URL (Secure) config fields
  src/configuration/general/web.md
  src/images/images/config-general-web-base-urls-secure.png
  src/stores/store-urls.md
Labels: Minor update, Progress: approved, Security, internal-dev

#350 Added URL to fix sitemap errors
  _config.yml
Labels: Site improvements

#337 Update shipping-labels.md
  src/shipping/shipping-labels.md
Labels: Partner: Rave Digital, bug, partners-contribution

#348 Markdown linting: MD003
  _checks/styles/style-rules-prod
  src/catalog/settings-advanced-custom-options.md
Labels: Editorial, Site improvements

#338 Tier prices - Add note to clarify discount calculation
  src/catalog/product-price-tier.md
Labels: Minor update

#353 Fix incorrect git url for Windows installation
  README.md
Labels: Minor update, Waiting for response, bug

#352 GH#240 update steps for creating cart price rule
  src/images/images/price-rule-cart-condition-products-subselection3.png
  src/images/images/price-rule-cart-condition-products-subselection4.png
  src/marketing/price-rules-cart-create.md
Labels: Minor update

#351 GH#347 Clarify Pending vs Processing Statuses
  src/sales/order-processing.md
  src/sales/order-update.md
Labels: Editorial, Minor update

#360 Markdown linting: MD004
  _checks/styles/style-rules-prod
  src/cms/editor-insert-link.md
  src/cms/page-builder-add-content-block.md
  src/payment/paypal-payflow-link.md
  src/payment/paypal-payments-pro.md
  src/payment/paypal-payments-standard.md
  src/payment/purchase-order.md
  src/payment/zero-subtotal-checkout.md
  src/sales-channels/amazon/creating-editing-overrides.md
  src/sales-channels/amazon/intelligent-repricing-rules.md
  src/shipping/magento-shipping-batch-create.md
Labels: Editorial, Site improvements

#355 Corrected tables of Grouped and Configurable complex data
  src/system/data-complex.md
Labels: Minor update

#358 Fix the link to Magento Keys information
  src/design/theme-install.md
Labels: Partner: Atwix, bug, partners-contribution

#359 Additional info for Cron configuration settings.
  src/system/cron.md
Labels: Minor update, Partner: Atwix, partners-contribution

#354 Format updates in catalog topics folder (part 3)
  src/_includes/inventory-assign-sources-quantities.md
  src/catalog/media-gallery.md
  src/catalog/navigation-accessibility.md
  src/catalog/navigation-breadcrumb-trail.md
  src/catalog/navigation-layered-configuration.md
  src/catalog/navigation-layered-filterable-attributes.md
  src/catalog/navigation-layered-price.md
  src/catalog/navigation-layered.md
  src/catalog/navigation-pagination.md
  src/catalog/navigation-product-listings.md
  src/catalog/navigation-top.md
  src/catalog/navigation.md
  src/catalog/pricing-advanced.md
  src/catalog/product-attributes-add.md
  src/catalog/product-attributes.md
  src/catalog/product-autosettings.md
  src/catalog/product-bundle-items.md
  src/catalog/product-configurations.md
  src/catalog/product-content.md
  src/catalog/product-create-bundle.md
  src/catalog/product-create-configurable.md
  src/catalog/product-create-downloadable.md
  src/catalog/product-create-grouped.md
  src/catalog/product-create-simple.md
  src/catalog/product-create-virtual.md
  src/catalog/product-create.md
  src/catalog/product-download-options.md
  src/catalog/product-downloadable-information.md
  src/catalog/product-fields-autogenerated.md
  src/catalog/product-gift-card-account-configuration.md
  src/catalog/product-gift-card-accounts.md
  src/catalog/product-gift-card-create.md
  src/catalog/product-gift-card-information.md
  src/catalog/product-gift-card-workflow.md
  src/catalog/product-gift-card.md
  src/catalog/product-gift-options.md
  src/catalog/product-grouped-products.md
  src/catalog/product-image-placeholders.md
  src/catalog/product-image-resizing.md
  src/catalog/product-image-upload.md
  src/catalog/product-image-watermarks.md
  src/catalog/product-images-and-video.md
Labels: Editorial

#362 Move and rename the engcom issue template
  .github/ISSUE_TEMPLATE/ENGCOM_EFFORT.md
Labels: maintenance

#364 Views definition clarification
  src/marketing/recommendation-metrics.md
Labels: 2.3.3, Progress: approved, internal-dev

#366 Added Sync option description to the docs
  src/catalog/inventory-options-global.md
  src/images/images/config-catalog-catalog-inventory-stock-options.png
Labels: 2.3.5, Minor update, Progress: review

#369 Updating metrics with vCTR description
  src/marketing/recommendation-metrics.md
Labels: 2.3.3, Progress: approved, internal-dev

#370 Adding information about backup recommendations
  src/marketing/product-recommendations.md
Labels: 2.3.3, Progress: approved, internal-dev

#367 Marketplace merchdocs migration
  src/_data/b2b/main-nav.yml
  src/_data/b2b/toc/getting-started.yml
  src/_data/b2b/toc/operations.yml
  src/_data/ce/main-nav.yml
  src/_data/ce/toc/getting-started.yml
  src/_data/ce/toc/operations.yml
  src/_data/ee/main-nav.yml
  src/_data/ee/toc/getting-started.yml
  src/_data/ee/toc/operations.yml
  src/images/images-ee/web-setup-system-config-credentials-saved.png
  src/images/images/magento-connect-download-language-pack.png
  src/images/images/magento-connect-extension-ready-to-install.png
  src/images/images/magento-connect-magento2-extensions.png
  src/images/images/magento-connect-output.png
  src/images/images/magento-marketplace-access-keys.png
  src/images/images/magento-marketplace-account-profile.png
  src/images/images/magento-marketplace-profile.png
  src/images/images/magento-marketplace-purchase.png
  src/images/images/magento-marketplace-system-config.png
  src/images/images/magento-marketplace.png
  src/images/images/system-cache-management-invalid.png
  src/images/images/system-web-setup-wizard-tiles.png
  src/images/images/system-web-setup-wizard.png
  src/images/images/web-setup-extension-manager-access-key.png
  src/images/images/web-setup-extension-manager-ready-to-install.png
  src/images/images/web-setup-extension-manager-step1-complete.png
  src/images/images/web-setup-extension-manager-step1.png
  src/images/images/web-setup-extension-manager-step2-complete.png
  src/images/images/web-setup-extension-manager-step2.png
  src/images/images/web-setup-extension-manager-success.png
  src/images/images/web-setup-extension-manager-summary-detail.png
  src/images/images/web-setup-extension-summary.png
  src/images/images/web-setup-extensions-grid.png
  src/images/images/web-setup-wizard-extension-manager.png
  src/magento/change-log.md
  src/magento/magento-marketplace-credentials.md
  src/magento/magento-marketplace-install-extension.md
  src/magento/magento-marketplace-synchronize-store.md
  src/magento/magento-marketplace.md
  src/system/web-setup-extension-manager.md
  src/system/web-setup-system-configuration.md
  src/system/web-setup-wizard.md
Labels: Progress: review, internal-dev, maintenance

#376 Markdown linting: MD006
  _checks/styles/style-rules-prod
  src/design/design-menu.md
Labels: Editorial, Progress: approved, Site improvements

#375 Removing currency limitation
  src/marketing/product-recs-limitations.md
Labels: 2.3.3, Progress: approved, internal-dev

#374 Updated format of URLs
  src/catalog/catalog-urls.md
Labels: Minor update

#377 Updates to onboarding for Amazon Sales Channel
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/marketing.yml
  src/sales-channels/asc/about-amazon-marketplace.md
  src/sales-channels/asc/about-amazon-sales-channel.md
  src/sales-channels/asc/about-listings-and-catalog.md
  src/sales-channels/asc/amazon-getting-started.md
  src/sales-channels/asc/amazon-manually-update-incomplete-listing.md
  src/sales-channels/asc/amazon-onboarding-home.md
  src/sales-channels/asc/amazon-order-details.md
  src/sales-channels/asc/amazon-pre-setup-tasks.md
  src/sales-channels/asc/amazon-sales-channel.md
  src/sales-channels/asc/amazon-verify-api-key.md
  src/sales-channels/asc/assets/amazon-ob-listing-preview.png
  src/sales-channels/asc/assets/amazon-store-integration.png
  src/sales-channels/asc/assets/asc-dashboard-after-2fa.png
  src/sales-channels/asc/business-pricing.md
  src/sales-channels/asc/catalog-search.md
  src/sales-channels/asc/competitor-conditional-variances.md
  src/sales-channels/asc/creating-assigning-catalog-products.md
  src/sales-channels/asc/creating-attributes.md
  src/sales-channels/asc/creating-editing-overrides.md
  src/sales-channels/asc/floor-price.md
  src/sales-channels/asc/fulfilled-by.md
  src/sales-channels/asc/intelligent-repricing-rules.md
  src/sales-channels/asc/listing-price.md
  src/sales-channels/asc/listing-rules.md
  src/sales-channels/asc/ob-create-listing-rule.md
  src/sales-channels/asc/ob-creating-magento-attributes.md
  src/sales-channels/asc/optional-ceiling-price.md
  src/sales-channels/asc/order-settings.md
  src/sales-channels/asc/price-adjustment.md
  src/sales-channels/asc/pricing-rule-general-settings.md
  src/sales-channels/asc/product-listing-condition.md
  src/sales-channels/asc/sales-channel-settings.md
  src/sales-channels/asc/standard-price-rules.md
  src/sales-channels/asc/store-integration.md
  src/sales-channels/asc/third-party-listing-settings.md
  src/sales-channels/asc/workspace-controls.md
Labels: Major update, Progress: approved

#372 Update attributes-rating.md
  src/stores/attributes-rating.md
Labels: Minor update, Progress: approved
