Repository magento/merchdocs, pull requests merged in 2020-01, with the labels that each got.

#203 Update inventory.md
  src/configuration/catalog/inventory.md
Labels: Minor update, Partner: Rave Digital, partners-contribution

#200 Update permissions-role-resources.md
  src/system/permissions-role-resources.md
Labels: Major update, Partner: Rave Digital, Progress: approved, partners-contribution

#214 Corrected the Setting path of Gift Options
  src/sales/gift-options.md
Labels: Minor update

#205 Setup shipping origin step added in UPS configuration
  src/images/images/shipping-origin-magento.png
  src/shipping/ups.md
Labels: Major update, Partner: Ziffity, Progress: approved, partners-contribution

#226 Clarify how to add block to page
  src/cms/block-add.md
  src/images/images-ee/blocks-workspace.png
  src/images/images/block-detail.png
  src/images/images/block-editor-hidden.png
  src/images/images/block-editor.png
  src/images/images/blocks-workspace.png
  src/images/images/cms-new-block-save-and-close.png
Labels: Minor update, Progress: approved

#233 update link to devdocs
  src/catalog/inventory-configure-distance-priority.md
Labels: Editorial, Progress: approved, internal-dev

#234 BUNDLE-2372-klarna
  src/configuration/sales/klarna.md
  src/images/images/config-sales-payment-methods-klarna-api.png
  src/images/images/config-sales-payment-methods-klarna-payments-design.png
  src/images/images/config-sales-payment-methods-klarna-payments.png
  src/images/images/payments-klarna-dashboard-playground-env.png
  src/images/images/payments-klarna-dashboard-playground-settings.png
  src/images/images/payments-klarna-merchant-account-create.png
  src/images/images/payments-klarna-portal-brand.png
  src/payment/klarna-setup.md
Labels: 2.3.4, Major update

#227 Adobe Stock: removed references to "Adobe IMS" and instead just used "Adobe account"
  src/cms/adobe-stock-manage.md
  src/cms/adobe-stock.md
  src/cms/editor-insert-image.md
Labels: Progress: approved, asi-1.0

#245 Yotpo Updates 2.3.4
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/marketing.yml
  src/marketing/yotpo-reporting.md
  src/marketing/yotpo-reviews-intro.md
  src/reports/business-intelligence.md
  src/reports/review-reports.md
Labels: 2.3.4, Minor update, New topic, Progress: review

#252 Updates to Privacy Regulation (CCPA/GDPR) topics
  src/stores/compliance-ccpa-guide.md
  src/stores/compliance-ccpa.md
  src/stores/compliance-gdpr.md
  src/stores/compliance-industry.md
Labels: Progress: approved

#215 Remove duplicate "about"
  src/stores/admin-signin.md
Labels: Editorial, small changes

#216 Fix minor typo
  src/stores/admin-menu.md
Labels: Editorial, Progress: approved, small changes

#241 Minor typo issue
  src/marketing/invitations-configure.md
Labels: Editorial, small changes

#242 Update email-template-list.md. minor typo issue.
  src/marketing/email-template-list.md
Labels: Editorial, Progress: approved, small changes

#235 Added space between text
  src/stores/admin-grid-layout.md
Labels: Editorial, Progress: approved, small changes

#243 Update pages-core.md. Added Customer Service title
  src/cms/pages-core.md
Labels: Editorial, Progress: approved, small changes

#244 Update page-home-new.md. Link content change
  src/cms/page-home-new.md
Labels: Editorial, Progress: approved, small changes

#246 Update footer.md. minor typo issue.
  src/design/footer.md
Labels: Editorial, Progress: approved, small changes

#251 Update account-create.md. Change Sign in redirection link.
  src/customers/account-create.md
Labels: Editorial, Progress: approved, small changes

#253 Update customer-segment-attributes.md
  src/marketing/customer-segment-attributes.md
Labels: Editorial, Progress: approved, small changes

#256 Update carriers.md. typo issue.
  src/shipping/carriers.md
Labels: Editorial, Progress: approved

#257 Update ups.md. Corrected link redirection
  src/shipping/ups.md
Labels: Editorial, Progress: approved

#259 Update shipping-label-workflow.md. minor issue
  src/shipping/shipping-label-workflow.md
Labels: Editorial, Progress: approved

#255 [WIP] Small changes
  src/cms/page-home-new.md
  src/cms/pages-core.md
  src/customers/account-create.md
  src/design/footer.md
  src/marketing/customer-segment-attributes.md
  src/marketing/email-template-list.md
  src/marketing/invitations-configure.md
  src/stores/admin-grid-layout.md
  src/stores/admin-menu.md
  src/stores/admin-signin.md
Labels: Progress: approved

#206 Update data-import-product-images.md
  src/system/data-import-product-images.md
Labels: Minor update, Progress: review

#260 price-rules-cart.md. minor typo issue
  src/marketing/price-rules-cart.md
Labels: Editorial, Progress: approved

#261 Update sales.md minor typo issue.
  src/sales.md
Labels: Editorial, Progress: approved

#262 Update category-root.md minor typo issue
  src/catalog/category-root.md
Labels: Editorial, Progress: approved

#264 Update store-urls.md. minor typo issue.
  src/stores/store-urls.md
Labels: Editorial, Progress: approved

#266 Update vat-configure.md.
  src/tax/vat-configure.md
Labels: Editorial, Progress: approved

#263 Update product-translate.md
  src/catalog/product-translate.md
Labels: Editorial

#272 Update Yotpo links in Reports
  src/reports/business-intelligence.md
Labels: 2.3.4, Progress: approved

#268 Removed duplicate information
  src/payment/paypal-express-checkout.md
Labels: Editorial, Progress: approved

#254 Add url params in template hints option
  src/images/images/config-advanced-developer-debug.png
  src/system/template-path-hints.md
Labels: Minor update, Partner: Ziffity, Progress: changes requested, partners-contribution

#280 BUNDLE-2372-klarna-updates
  src/payment/klarna-setup.md
  src/payment/klarna.md
Labels: 2.3.4, Progress: approved

#267 Update attributes-customer.md. Link Change.
  src/stores/attributes-customer.md
  src/system/data-schedule-import.md
  src/system/integrations.md
Labels: Minor update, Progress: approved

#284 Dotmailer updates
  src/configuration/engagement-cloud/developer.md
  src/configuration/engagement-cloud/email-templates.md
  src/images/images/config-engagement-cloud-developer-import-settings.png
  src/images/images/config-engagement-cloud-email-templates.png
  src/magento/change-log.md
  src/marketing/engagement-cloud.md
Labels: Progress: approved

#282 Vertex updates
  src/_data/b2b/toc/getting-started.yml
  src/_data/b2b/toc/operations.yml
  src/_data/ce/toc/getting-started.yml
  src/_data/ce/toc/operations.yml
  src/_data/ee/toc/getting-started.yml
  src/_data/ee/toc/operations.yml
  src/configuration/sales/address-validation.md
  src/configuration/sales/tax.md
  src/images/images/config-sales-address-validation.png
  src/images/images/config-sales-payment-methods-authorize-net-basic-settings.png 
  src/images/images/customer-account-stored-payment-methods copy.png
  src/images/images/customer-journey.png
  src/images/images/engagement-cloud-campaign-block-delete.png
  src/images/images/product-image-detail-jewel-tee.png
  src/images/images/shipping-origin-magento.png
  src/images/images/tax-vertex-cloud-address-verify-store.png
  src/images/images/tax-vertex-cloud-magento-config-valid.png
  src/magento/change-log.md
  src/tax/vertex-configure-address.md
  src/tax/vertex-configure-magento.md
  src/tax/vertex-configure.md
  src/tax/vertex-field-mapping.md
  src/tax/vertex-setup-customer-exceptions.md
  src/tax/vertex-setup-products.md
  src/tax/vertex-setup.md
  src/tax/vertex-test-configuration.md
  src/tax/vertex.md
Labels: 2.3.4, New topic, Progress: review, internal-dev

#276 Added line break
  src/stores/admin-actions-control.md
Labels: Editorial, Progress: approved

#281 Removing info about BI essentials
  src/_data/b2b/toc/operations.yml
  src/_data/ce/toc/operations.yml
  src/_data/ee/toc/operations.yml
  src/reports/business-intelligence.md
  src/sales-channels/google-ads/google-reporting.md
Labels: 2.3.3, Minor update, Progress: approved, internal-dev

#279 Update default value of "Default No-route URL" field
  src/configuration/general/web.md
Labels: Editorial, Minor update, Progress: approved

#289 magento/merchdocs#: 2.3.4. Import products images. Updates.
  src/images/images/data-import-images-file-to-import.png
  src/system/data-import-product-images.md
Labels: 2.3.4, Minor update, Partner: Atwix, Progress: review, partners-contribution

#285 Customer attribute description added and minor changes.
  src/system/data-attributes-customer.md
  src/system/data-import-history.md
Labels: Minor update

#291 Product Variation Attribute Input Types
  src/catalog/product-create-configurable.md
Labels: Minor update, Progress: approved, internal-dev

#293 Add CLA requirement and link to Contributing page
  .github/CONTRIBUTING.md
Labels: Progress: approved, Site improvements

#290 Clarifies pending/processing order options
  src/images/images-ee/order-button-bar-processing.png
  src/images/images/order-button-bar-pending.png
  src/images/images/order-button-bar-processing.png
  src/sales/order-processing.md
  src/sales/order-update.md
Labels: Major update, Progress: approved, internal-dev

#295 password-options.md Minor improvement.
  src/customers/password-options.md
Labels: Minor update, Progress: approved

#300 Adding EAP MerchDoc content for Product Recommendations
  _config.yml
  src/_data/ee/toc/marketing.yml
  src/_includes/layout/page-header.html
  src/css/merchdocs.css
  src/marketing/create-new-rec.md
  src/marketing/edit-existing-rec.md
  src/marketing/product-recommendations.md
  src/marketing/product-recs-limitations.md
  src/marketing/recommendation-best-practices.md
  src/marketing/recommendation-metrics.md
Labels: 2.3.3, New topic, Progress: approved, internal-dev

#298 Fix Category Permissions formatting
  src/catalog/category-permissions.md
Labels: Editorial, Progress: approved, internal-dev

#301 Add the Magento Copyright file
  COPYING.txt
Labels: Progress: approved

#202 Update documentation related to Google reCAPTCHA
  src/configuration/security/google-recaptcha.md
  src/images/images/config-2fa-google-recaptcha-backend-v3.png
  src/images/images/config-2fa-google-recaptcha-backend.png
  src/images/images/config-2fa-google-recaptcha-frontend.png
  src/images/images/config-2fa-google-recaptcha-v2-invisible-backend.png
  src/images/images/config-2fa-google-recaptcha-v2-invisible-frontend.png
  src/images/images/config-2fa-google-recaptcha-v3-backend.png
  src/images/images/config-2fa-google-recaptcha-v3-frontend.png
  src/images/images/config-google-recaptcha-general.png
  src/images/images/config-security-recaptcha-keys.png
  src/images/images/config-security-recaptcha-type-v2.png
  src/images/images/config-security-recaptcha-type-v3.png
  src/images/images/recaptcha-keys.png
  src/images/images/recaptcha-register-new-site.png
  src/stores/security-google-recaptcha.md
Labels: Major update, Progress: changes requested, internal-dev
