Repository magento/merchdocs, pull requests merged in 2020-08, with the labels that each got.

#647 Small changes 2.3.x
  src/getting-started.md
  src/getting-started/login-credentials.md
  src/magento/magento-account-share.md
  src/quick-tour/engage.md
  src/quick-tour/market-opportunities.md
  src/quick-tour/self-service-tools.md
Labels: 2.3.x, Editorial, Progress: approved

#645 Clarifying pricing rules for POs
  src/customers/account-dashboard-my-purchase-orders.md
Labels: 2.4.0, Editorial, Progress: changes requested

#650 Updated "Password Reset Protection Type" section
  src/customers/password-options.md
Labels: 2.4.x, Minor update, Progress: changes requested

#653 Bumping theme number/revision
  Gemfile.lock
Labels: Progress: approved, Site improvements, internal-dev

#652 MC-36350: Update documentation about Adjustment Refund option on Cred…
  src/sales/credit-memo-create.md
Labels: 2.4.x, Minor update, Port change, Progress: approved, stakeholder

#657 Update inventory-configure-distance-priority.md
  src/shipping/shipping-in-store-delivery.md
Labels: 2.4.0, Minor update, Progress: changes requested, Stakeholder

#665 Fix the issue with failing Markdown test (mdl 0.10.0)
  .github/workflows/main.yml
Labels: Progress: review, maintenance

#663 Update shipping-in-store-delivery.md
  src/shipping/shipping-in-store-delivery.md
Labels: 2.4.x, Editorial, Progress: approved

#654 Add Login as Customer inforrmation
  src/customers/account-company-update.md
  src/images/images-b2b/company-update.png
Labels: 2.4.1, Editorial, Progress: approved

#664 Equitable terminology standards
  src/configuration/advanced/developer.md
  src/configuration/dotdigital/developer.md
  src/configuration/sales/amazon-pay.md
  src/magento/change-log.md
  src/magento/magento-security-best-practices.md
  src/marketing/dotdigital/contacts.md
  src/marketing/email-template-message.md
  src/marketing/price-rules-cart-coupon.md
  src/marketing/variables-custom.md
  src/marketing/variables-predefined.md
  src/payment/amazon-pay-setup.md
  src/system/developer-client-restrictions.md
  src/system/developer-tools.md
  src/system/template-path-hints.md
Labels: 2.3.x, Editorial, Port change, Progress: approved

#666 Equitable terminology standards - 2.4
  src/configuration/advanced/developer.md
  src/configuration/dotdigital/developer.md
  src/configuration/sales/amazon-pay.md
  src/magento/magento-security-best-practices.md
  src/marketing/dotdigital/contacts.md
  src/marketing/email-template-message.md
  src/marketing/price-rules-cart-coupon.md
  src/marketing/variables-custom.md
  src/marketing/variables-predefined.md
  src/payment/amazon-pay-setup.md
  src/system/developer-client-restrictions.md
  src/system/developer-tools.md
  src/system/template-path-hints.md
Labels: 2.4.x, Editorial, Forward port, Progress: approved

#656 Update checkout-payment-failed-emails.md
  src/sales/checkout-payment-failed-emails.md
Labels: Community, Minor update, Port change, Progress: changes requested

#655 Add the from cart method
  src/customers/account-dashboard-requisition-lists.md
  src/images/images-b2b/requisition-list-add-from-cart.png
Labels: 2.4.1, Major update, Progress: changes requested

#669 Update README.md
  README.md
Labels: Progress: approved, maintenance

#670 Fixing link in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Progress: approved, maintenance

#671 GH661, Fix incorrect file name
  src/marketing/google-tag-manager.md
Labels: 2.4.x, Editorial, Port change, Progress: approved

#667 Update documentation product video configuration
  src/catalog/product-video.md
Labels: 2.4.x, Major update, Partner: PHPro, Port change, Progress: on hold, partners-contribution

#672 Update multiple URL rewrites
  src/_data/toc/marketing.yml
  src/images/images/url-rewrites-update.png
  src/marketing/url-rewrite-update-all.md
  src/marketing/url-rewrite.md
Labels: 2.3.x, Minor update, Progress: approved

#673 URL rewrite update for 2.4
  src/_data/toc/marketing.yml
  src/images/images/url-rewrites-update.png
  src/marketing/url-rewrite-update-all.md
  src/marketing/url-rewrite.md
Labels: 2.4.x, Minor update, Progress: approved

#674 Fix formatting and update page title
  src/customers/login-as-customer.md
Labels: 2.4.x, Editorial, Progress: approved

#675 Remove old hotjar feedback description
  src/getting-started/contribute.md
Labels: 2.4.x, Editorial, Port change, Progress: approved

#676 Update contact setup in 2.4
  src/stores/contact-us.md
Labels: 2.4.0, Community, Major update, Progress: changes requested

#677 Fixes #104-Added cross reference to Event Updates.
  src/marketing/event-create.md
  src/marketing/event-restrict-sales.md
Labels: 2.4.x, Minor update, Progress: approved

#679 Remove old banners content
  src/_data/toc/content.yml
  src/_data/toc/customers.yml
  src/cms/banner-create.md
  src/cms/banner-rotator.md
  src/cms/banners-price-rules.md
  src/cms/banners.md
  src/cms/content-menu.md
  src/cms/dynamic-blocks-price-rules.md
  src/cms/dynamic-blocks-rotate.md
  src/cms/dynamic-blocks.md
  src/images/images-ee/banner-10-pct.png
  src/images/images-ee/banner-default-content.png
  src/images/images-ee/banner-price-rule.png
  src/images/images-ee/banner-properties-customer-segment.png
  src/images/images-ee/banner-properties-default-content.png
  src/images/images-ee/banner-properties.png
  src/images/images-ee/banner-related-cart-price-rule.png
  src/images/images-ee/banner-related-promotions.png
  src/images/images-ee/banner-specify-types.png
  src/images/images-ee/banners-customer-segment.png
  src/images/images-ee/banners-grid.png
  src/images/images-ee/banners-list.png
  src/images/images-ee/banners.png
  src/images/images-ee/storefront-banner.png
  src/images/images/price-rules-catalog-related-banner-10-pct.png
  src/marketing/customer-segment-banner.md
  src/marketing/customer-segment-dynamic-block.md
  src/marketing/customer-segment-price-rule.md
  src/marketing/price-rules-cart-create.md
  src/marketing/price-rules-catalog-create.md
Labels: 2.3.x, Major update, Progress: review

#680 B2B Enhancements
  src/configuration/general/b2b-features.md
  src/images/images-b2b/config-general-b2b-features.png
  src/quick-tour/b2b-quick-start.md
  src/quick-tour/build-loyalty.md
  src/quick-tour/self-service-tools.md
  src/stores/b2b-features.md
Labels: 2.4.x, Editorial, Progress: changes requested

#681 Swat tool 2.4.1
  src/_data/toc/operations.yml
  src/images/images-ee/admin-menu-reports.png
  src/images/images-ee/reports-swat-dashboard.png
  src/reports.md
  src/reports/reports-menu.md
  src/reports/site-wide-analysis-tool.md
  src/system/permissions-role-resources.md
Labels: 2.4.1, Major update, Progress: approved

#686 Mark as available to Commerce version
  src/catalog/category-products-sort.md
Labels: 2.4.x, Community, Forward port, Progress: approved

#687 Remove outdated statement about bundle products
  src/catalog/inventory-sources.md
Labels: 2.4.x, Minor update, Progress: on hold, internal-dev

#682 Updating Checkout Options topic
  src/images/images-b2b/storefront-checkout-step2-b2b.png
  src/images/images-ee/config-sales-checkout-checkout-options.png
  src/sales/checkout-options.md
  src/sales/checkout-process.md
Labels: 2.4.x, Major update, Progress: changes requested

#713 Whats new update
  src/_data/home-sections.yml
  src/_data/whats-new.yml
Labels: 2.4.x, Minor update, Progress: approved

#690 Fix for GTM universal tags
  src/marketing/google-enhanced-ecommerce.md
Labels: 2.4.x, Minor update, Port change, Progress: approved

#688 Un-necessary angle bracket
  src/tax/guidelines-eu.md
Labels: 2.4.x, Community, Editorial, Progress: approved

#714 Back port changes to 2.3.x
  src/catalog/product-video.md
  src/customers/password-options.md
  src/getting-started/contribute.md
  src/magento/change-log.md
  src/marketing/google-enhanced-ecommerce.md
  src/marketing/google-tag-manager.md
  src/sales/checkout-payment-failed-emails.md
  src/sales/credit-memo-create.md
Labels: 2.3.x, Back port, Progress: approved

#712 Adding Visual similarity rec and reorganizing types
  src/_data/toc/marketing.yml
  src/images/images-ee/trending-homepage.png
  src/images/images-ee/trending-pdp.png
  src/images/images-ee/visual-sim-pdp.png
  src/images/images-ee/visual-sim-unit.png
  src/marketing/prex-type-boughtbought.md
  src/marketing/prex-type-morelikethis.md
  src/marketing/prex-type-mostaddcart.md
  src/marketing/prex-type-mostpurchase.md
  src/marketing/prex-type-mostviewed.md
  src/marketing/prex-type-rcmdforyou.md
  src/marketing/prex-type-trending.md
  src/marketing/prex-type-viewbought.md
  src/marketing/prex-type-viewview.md
  src/marketing/prex-type-visualsim.md
  src/marketing/prex-types.md
  src/marketing/product-recommendations.md
Labels: 2.4.x, New topic, Progress: review, Stakeholder
