Repository magento/merchdocs, pull requests merged in 2020-03, with the labels that each got.

#380 Update Change Log
  src/magento/change-log.md
Labels: Minor update, Progress: approved

#381 Updates to Amazon Sales Channel Home
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/marketing.yml
  src/sales-channels/asc/about-amazon-sales-channel.md
  src/sales-channels/asc/amazon-getting-started.md
  src/sales-channels/asc/amazon-matching-attributes-values.md
  src/sales-channels/asc/amazon-order-details.md
  src/sales-channels/asc/amazon-sales-channel-home.md
  src/sales-channels/asc/amazon-sales-channel.md
  src/sales-channels/asc/amazon-store-dashboard.md
  src/sales-channels/asc/amazon-verify-api-key.md
  src/sales-channels/asc/assets/amazon-api-verification-prompt.png
  src/sales-channels/asc/assets/amazon-attribute-settings-create.png
  src/sales-channels/asc/assets/amazon-attribute-settings-edit.png
  src/sales-channels/asc/assets/amazon-attributes-view.png
  src/sales-channels/asc/assets/amazon-sales-channel-home-tabs.png
  src/sales-channels/asc/attributes-view.md
  src/sales-channels/asc/business-pricing.md
  src/sales-channels/asc/creating-attributes.md
  src/sales-channels/asc/fulfilled-by.md
  src/sales-channels/asc/learning-preparation.md
  src/sales-channels/asc/listing-price.md
  src/sales-channels/asc/listing-rule-preview.md
  src/sales-channels/asc/listing-rules.md
  src/sales-channels/asc/listing-settings.md
  src/sales-channels/asc/managing-attributes.md
  src/sales-channels/asc/managing-listings-by-tab.md
  src/sales-channels/asc/managing-orders.md
  src/sales-channels/asc/managing-product-listings.md
  src/sales-channels/asc/managing-stores.md
  src/sales-channels/asc/ob-create-listing-rule.md
  src/sales-channels/asc/ob-creating-magento-attributes.md
  src/sales-channels/asc/order-settings.md
  src/sales-channels/asc/pricing-products.md
  src/sales-channels/asc/pricing-rule-actions.md
  src/sales-channels/asc/pricing-rule-conditions.md
  src/sales-channels/asc/pricing-rule-general-settings.md
  src/sales-channels/asc/product-listing-actions.md
  src/sales-channels/asc/product-listing-condition.md
  src/sales-channels/asc/stock-quantity.md
  src/sales-channels/asc/store-integration-settings.md
  src/sales-channels/asc/third-party-listing-settings.md
  src/sales-channels/asc/workspace-controls.md
Labels: Progress: approved

#382 Marketplace Buyers FAQ content
  src/magento/magento-marketplace.md
Labels: Progress: approved, internal-dev

#385 Update Amazon store dashboard
  src/sales-channels/asc/amazon-onboarding-home.md
  src/sales-channels/asc/amazon-sales-channel-home.md
  src/sales-channels/asc/amazon-store-dashboard.md
  src/sales-channels/asc/creating-attributes.md
  src/sales-channels/asc/learning-preparation.md
  src/sales-channels/asc/ob-store-review.md
Labels: Progress: approved

#386 Remove Marketplace User Guide from federated search
  src/_includes/layout/header-scripts.html
Labels: Progress: approved, Site improvements

#388 Update listing settings section for ASC 4.0
  src/_includes/amazon-listing-settings-sections.md
  src/sales-channels/asc/add-pricing-rule.md
  src/sales-channels/asc/amazon-logs-reports.md
  src/sales-channels/asc/amazon-onboarding-home.md
  src/sales-channels/asc/amazon-sales-channel-home.md
  src/sales-channels/asc/amazon-store-dashboard.md
  src/sales-channels/asc/business-pricing.md
  src/sales-channels/asc/catalog-search.md
  src/sales-channels/asc/fulfilled-by.md
  src/sales-channels/asc/listing-price.md
  src/sales-channels/asc/listing-rules.md
  src/sales-channels/asc/listing-settings.md
  src/sales-channels/asc/managing-orders.md
  src/sales-channels/asc/managing-product-listings.md
  src/sales-channels/asc/managing-stores.md
  src/sales-channels/asc/ob-create-listing-rule.md
  src/sales-channels/asc/ob-store-review.md
  src/sales-channels/asc/order-settings.md
  src/sales-channels/asc/product-listing-actions.md
  src/sales-channels/asc/product-listing-condition.md
  src/sales-channels/asc/sales-channel-settings.md
  src/sales-channels/asc/stock-quantity.md
  src/sales-channels/asc/store-integration-settings.md
  src/sales-channels/asc/store-integration.md
  src/sales-channels/asc/third-party-listing-settings.md
Labels: Progress: approved

#387 Magento Marketplace Credentials Numbering Fix
  src/magento/magento-marketplace-credentials.md
Labels: Editorial, Progress: approved

#389 Update order settings for ASC 4.0
  src/sales-channels/asc/assets/amazon-order-settings.png
  src/sales-channels/asc/order-settings.md
Labels: Progress: approved

#390 Price rule multiple skus
  src/images/images/price-rule-catalog-multiple-skus-condition1.png
  src/images/images/price-rule-catalog-multiple-skus-condition1a.png
  src/images/images/price-rule-catalog-multiple-skus-condition1b.png
  src/images/images/price-rule-catalog-multiple-skus-condition2.png
  src/images/images/price-rule-catalog-multiple-skus-condition2b.png
  src/marketing/price-rule-multiple-sku.md
  src/price-rule-catalog-multiple-skus-condition2.png
Labels: Minor update, Progress: approved

#384 Correct minor spelling mistake in search-engine-robots.md
  src/marketing/search-engine-robots.md
Labels: Editorial

#393 Update listing and pricing rules
  src/sales-channels/asc/about-amazon-sales-channel.md
  src/sales-channels/asc/add-pricing-rule.md
  src/sales-channels/asc/amazon-matching-attributes-values.md
  src/sales-channels/asc/amazon-pre-setup-tasks.md
  src/sales-channels/asc/assets/amazon-listing-rule-preview.png
  src/sales-channels/asc/assets/ob-listing-rules.png
  src/sales-channels/asc/attributes-view.md
  src/sales-channels/asc/buy-box-competitor-pricing.md
  src/sales-channels/asc/competitor-conditional-variances.md
  src/sales-channels/asc/floor-price.md
  src/sales-channels/asc/fulfilled-by.md
  src/sales-channels/asc/intelligent-repricing-rules.md
  src/sales-channels/asc/listing-rule-preview.md
  src/sales-channels/asc/listing-rules.md
  src/sales-channels/asc/lowest-competitor-pricing.md
  src/sales-channels/asc/managing-attributes.md
  src/sales-channels/asc/ob-define-condition-example.md
  src/sales-channels/asc/optional-ceiling-price.md
  src/sales-channels/asc/order-settings.md
  src/sales-channels/asc/price-adjustment.md
  src/sales-channels/asc/price-priority-logic.md
  src/sales-channels/asc/price-rule-examples.md
  src/sales-channels/asc/price-scope.md
  src/sales-channels/asc/pricing-products.md
  src/sales-channels/asc/pricing-rule-actions.md
  src/sales-channels/asc/pricing-rule-conditions.md
  src/sales-channels/asc/pricing-rule-general-settings.md
  src/sales-channels/asc/product-listing-details.md
  src/sales-channels/asc/standard-price-rules.md
  src/sales-channels/asc/stock-quantity.md
  src/sales-channels/asc/store-integration-settings.md
Labels: Progress: approved

#391 Grouped Product Images
  src/catalog/product-create-grouped.md
  src/images/images/product-grouped-create-choose-attribute-set.png
  src/images/images/product-grouped-create-store-view-choose.png
  src/images/images/product-grouped-products.png
Labels: Minor update, Progress: approved, internal-dev

#394 Apply the devdocs theme update #55
  Gemfile.lock
Labels: Progress: approved, Site improvements

#392 Updates for dynamic block and promotional rule associations
  src/cms/dynamic-blocks-price-rules.md
Labels: Minor update, Progress: approved

#395 Adding viewable impressions metric
  src/marketing/recommendation-metrics.md
Labels: 2.3.3, Progress: approved, internal-dev

#397 Updates to managing listings by action
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/marketing.yml
  src/_includes/amazon-assign-catalog-product-action.md
  src/_includes/amazon-create-new-catalog-product-action.md
  src/_includes/amazon-create-new-catalog-product-s-action.md
  src/_includes/amazon-create-override-action.md
  src/_includes/amazon-edit-assigned-asin-action.md
  src/_includes/amazon-edit-listing-overrides-action.md
  src/_includes/amazon-end-lising-action.md
  src/_includes/amazon-end-listing-s-action.md
  src/_includes/amazon-publish-on-amazon-action.md
  src/_includes/amazon-publish-to-amazon-action.md
  src/_includes/amazon-switch-to-fulfillment-action.md
  src/sales-channels/asc/active-listings.md
  src/sales-channels/asc/amazon-order-details.md
  src/sales-channels/asc/amazon-store-dashboard.md
  src/sales-channels/asc/amazon-verify-api-key.md
  src/sales-channels/asc/catalog-search.md
  src/sales-channels/asc/create-alias-seller-sku.md
  src/sales-channels/asc/creating-assigning-catalog-products.md
  src/sales-channels/asc/creating-attributes.md
  src/sales-channels/asc/creating-editing-overrides.md
  src/sales-channels/asc/edit-assigned-asin.md
  src/sales-channels/asc/end-listings-manually.md
  src/sales-channels/asc/ended-listings.md
  src/sales-channels/asc/inactive-listings.md
  src/sales-channels/asc/incomplete-listings.md
  src/sales-channels/asc/ineligible-listings.md
  src/sales-channels/asc/listing-rules.md
  src/sales-channels/asc/managing-listings-by-action.md
  src/sales-channels/asc/managing-listings-by-tab.md
  src/sales-channels/asc/managing-stores.md
  src/sales-channels/asc/new-third-party-listings.md
  src/sales-channels/asc/overrides.md
  src/sales-channels/asc/product-listing-condition.md
  src/sales-channels/asc/product-listing-details.md
  src/sales-channels/asc/publish-listings-manually.md
  src/sales-channels/asc/ready-to-list.md
  src/sales-channels/asc/store-integration.md
Labels: Progress: approved

#398 Update orders
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/marketing.yml
  src/_includes/amazon-workspace-controls.md
  src/sales-channels/asc/amazon-order-details.md
  src/sales-channels/asc/assets/amazon-order-details-header.png
  src/sales-channels/asc/assets/amazon-order-number-payment-info.png
  src/sales-channels/asc/assets/amazon-order-processing.png
  src/sales-channels/asc/assets/amazon-recent-orders-imported.png
  src/sales-channels/asc/assets/amazon-recent-orders-not-imported.png
  src/sales-channels/asc/cancel-unshipped-order.md
  src/sales-channels/asc/common-order-processing.md
  src/sales-channels/asc/managing-orders.md
  src/sales-channels/asc/order-settings.md
Labels: Progress: approved

#399 Customer name and address options
  src/configuration/customers/customer-configuration.md
  src/customers/name-address-options.md
  src/images/images-ee/config-customer-configuration-scope.png
  src/images/images-ee/config-customers-customer-configuration-name-address-options-ee.png
  src/images/images-ee/config-customers-customer-configuration-name-address-options.png
  src/images/images-ee/storefront-customer-account-address-book.png
  src/images/images/config-customer-configuration-scope.png
  src/images/images/config-customers-customer-configuration-name-address-options.png
  src/images/images/storefront-customer-account-date-of-birth.png
  src/images/images/storefront-customer-account-gender.png
  src/images/images/storefront-customer-account-prefix.png
  src/images/images/storefront-customer-account-signup.png
Labels: Progress: approved

#402 Amazon 4.0 edits
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/marketing.yml
  src/configuration/sales-channels.md
  src/configuration/sales-channels/global-settings.md
  src/images/images/config-sales-channels.png
  src/sales-channels/amazon/amazon-getting-started.md
  src/sales-channels/amazon/amazon-sales-channel.md
  src/sales-channels/asc/about-amazon-marketplace.md
  src/sales-channels/asc/about-amazon-sales-channel.md
  src/sales-channels/asc/active-listings.md
  src/sales-channels/asc/amazon-getting-started.md
  src/sales-channels/asc/amazon-logs-reports.md
  src/sales-channels/asc/amazon-matching-attributes-values.md
  src/sales-channels/asc/amazon-onboarding-home.md
  src/sales-channels/asc/amazon-sales-channel.md
  src/sales-channels/asc/assets/amazon-store-settings.png
  src/sales-channels/asc/assets/config-sales-channel-global-settings.png
  src/sales-channels/asc/attributes-view.md
  src/sales-channels/asc/buy-box-competitor-pricing.md
  src/sales-channels/asc/competitive-price-analysis.md
  src/sales-channels/asc/competitor-conditional-variances.md
  src/sales-channels/asc/creating-attributes.md
  src/sales-channels/asc/floor-price.md
  src/sales-channels/asc/listing-price.md
  src/sales-channels/asc/managing-attributes.md
  src/sales-channels/asc/managing-listings-by-action.md
  src/sales-channels/asc/managing-listings-by-tab.md
  src/sales-channels/asc/managing-product-listings.md
  src/sales-channels/asc/managing-stores.md
  src/sales-channels/asc/ob-create-listing-rule.md
  src/sales-channels/asc/price-adjustment.md
  src/sales-channels/asc/pricing-products.md
  src/sales-channels/asc/product-listing-details.md
  src/sales-channels/asc/sales-channel-settings.md
  src/sales-channels/asc/store-integration-settings.md
  src/sales-channels/asc/store-integration.md
  src/sales-channels/asc/store-reports.md
Labels: Progress: approved

#410 Add Google EOL page
  src/sales-channels/google-ads/google-eol.md
Labels: Minor update, Progress: approved

#409 Credit memo refunds
  src/images/images-ee/orders-grid.png
  src/images/images/config-engagement-cloud-chat-settings-teams.png
  src/images/images/config-payment-methods-braintree-payment-action-authorize-capture.png
  src/images/images/credit-memo-from-invoice.png
  src/images/images/credit-memo-order-total-refund.png
  src/images/images/invoice-credit-memo-items-to-refund.png
  src/images/images/invoice-order-totals-capture-online.png
  src/images/images/order-button-bar.png
  src/images/images/order-invoice-capture-online.png
  src/images/images/order-invoices-grid.png
  src/images/images/orders-grid.png
  src/sales/credit-memo-create.md
Labels: Minor update, Progress: changes requested, internal-dev

#404 Cart price rules screenshot update
  src/images/images-ee/price-rule-cart-actions.png
  src/images/images-ee/price-rule-cart-condition-products-subselection.png
  src/images/images/price-rule-cart-actions.png
  src/images/images/price-rule-cart-condition-products-subselection.png
  src/marketing/price-rules-cart-create.md
Labels: Minor update, Progress: approved, internal-dev

#413 Google eol messaging
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/marketing.yml
  src/_includes/layout/page-header.html
  src/sales-channels/google-ads/about-google-magento-catalogs.md
  src/sales-channels/google-ads/about-google.md
  src/sales-channels/google-ads/account-resolve-errors.md
  src/sales-channels/google-ads/account-settings.md
  src/sales-channels/google-ads/acct-settings.md
  src/sales-channels/google-ads/ads-acct-create.md
  src/sales-channels/google-ads/ads-edit.md
  src/sales-channels/google-ads/ads-management.md
  src/sales-channels/google-ads/ads-service-terms.md
  src/sales-channels/google-ads/attribute-mapping.md
  src/sales-channels/google-ads/create-campaign.md
  src/sales-channels/google-ads/getting-started-google.md
  src/sales-channels/google-ads/gmc-acct-create.md
  src/sales-channels/google-ads/gmc-service-terms.md
  src/sales-channels/google-ads/gmc-unlink-gmc.md
  src/sales-channels/google-ads/google-account-managment.md
  src/sales-channels/google-ads/google-ad-channel.md
  src/sales-channels/google-ads/google-best-practices.md
  src/sales-channels/google-ads/google-eol.md
  src/sales-channels/google-ads/google-reporting.md
  src/sales-channels/google-ads/link-accounts.md
  src/sales-channels/google-ads/manually-verify-claim-site.md
  src/sales-channels/google-ads/onboarding-google.md
  src/sales-channels/google-ads/product-managment.md
  src/sales-channels/google-ads/product-resolve-errors.md
  src/sales-channels/google-ads/products-edit-mappings.md
  src/sales-channels/google-ads/shipping-tax.md
  src/sales-channels/google-ads/smart-shopping-campaign.md
  src/sales-channels/google-ads/url-verify.md
  src/sales-channels/google-ads/verify-api-key.md
Labels: Major update, Progress: approved

#415 Payment Integration Deprecation Notes
  src/_data/b2b/toc/sales.yml
  src/_data/ce/toc/sales.yml
  src/_data/ee/toc/sales.yml
  src/payment/authorize-net-direct-post.md
  src/payment/authorize-net.md
  src/payment/cybersource.md
  src/payment/eway.md
  src/payment/gateways.md
  src/payment/worldpay.md
Labels: Minor update, Progress: approved

#412 Update ups.md
  src/shipping/ups.md
Labels: Minor update

#411 remove empty line
  src/catalog/product-types.md
Labels: Editorial, Progress: approved

#418 ASC-4-order-changes
  src/sales-channels/asc/amazon-store-dashboard.md
  src/sales-channels/asc/assets/amazon-store-dashboard.png
  src/sales-channels/asc/managing-orders.md
  src/sales-channels/asc/store-integration.md
Labels: Progress: review

#417 improve best practices
  src/marketing/recommendation-best-practices.md
Labels: 2.3.3, Editorial, Progress: review

#407 Adding content about filtering recommendations
  src/marketing/product-recommendations.md
Labels: 2.3.4, Progress: approved, internal-dev

#420 Documenting the trending recommendation type
  src/marketing/product-recommendations.md
  src/marketing/recommendation-best-practices.md
Labels: 2.3.3, Minor update, Progress: approved

#416 Custom layout update changes
  src/_data/b2b/toc/content.yml
  src/_data/ce/toc/content.yml
  src/_data/ee/toc/content.yml
  src/catalog/categories-custom-design.md
  src/cms/blocks.md
  src/cms/page-add.md
  src/design/block-layout-standard.md
  src/design/layout-update-examples.md
  src/design/layout-update-place-block.md
  src/design/layout-update-syntax.md
  src/design/layout-updates.md
  src/images/images-ee/pages-new-page.png
  src/images/images-ee/pages.png
  src/images/images/category-design.png
  src/images/images/page-content.png
  src/images/images/page-design-custom-layout-update.png
  src/images/images/page-design.png
  src/images/images/pages-new-page.png
  src/images/images/pages.png
  src/magento/change-log.md
Labels: 2.3.4, Minor update, Progress: review

#430 Documenting Sensei and adding rec unit screenshot
  src/images/images-ee/p-rex-unit.png
  src/marketing/create-new-rec.md
  src/marketing/product-recommendations.md
Labels: 2.3.3, Minor update, Progress: approved

#357 Markdown linting: MD010
  _checks/styles/style-rules-prod
  src/design/layout-update-examples.md
  src/payment/paypal-express-checkout.md
  src/shipping/magento-shipping-attributes.md
  src/stores/compliance-privacy-google.md
Labels: Site improvements

#431 Update attributes-customer.md
  src/stores/attributes-customer.md
Labels: Editorial, Progress: approved

#432 Removing internal name description
  src/marketing/create-new-rec.md
Labels: 2.3.3, Editorial, Progress: approved
