Repository magento/merchdocs, pull requests merged in 2020-09, with the labels that each got.

#718 Updating content about using visual recs in testing environment
  src/marketing/prex-type-visualsim.md
Labels: 2.4.x, Progress: approved, Stakeholder

#689 Adding the Path where "Display out of Stock products" Setting resides
  src/catalog/inventory-product-alerts.md
Labels: 2.4.x, Community, Minor update, Progress: changes requested

#722 Revert "Add GraphQL CORS screen"
  src/_data/toc/config-ref.yml
  src/configuration/services/graphql.md
  src/images/images/config-services-graphql-cors.png
Labels: 2.4.1, Progress: approved, internal-dev

#723 Remove `n` from `Google Authenticatorn`
  src/stores/security-two-factor-authentication-use.md
Labels: 2.4.x, Community, Editorial, Progress: approved

#724 Update promotions.md
  src/marketing/promotions.md
Labels: 2.4.x, Community, Minor update, Partner: PHPro, Progress: on hold, partners-contribution

#715 Small fixes and additions to the security best practices
  src/magento/magento-security-best-practices.md
Labels: 2.4.x, Community, Progress: review

#726 Update b2b-features.md
  src/stores/b2b-features.md
Labels: Editorial, Progress: approved

#727 Update quotes.md
  src/sales/quotes.md
Labels: 2.4.x, Community, Editorial, Progress: approved

#719 Update yotpo-reviews-intro.md
  src/marketing/yotpo-reviews-intro.md
Labels: 2.4.1, Community, Minor update, Progress: approved

#730 Update web wizard deprecation message for 2.3
  src/_includes/web-setup-deprecate.md
Labels: 2.3.6, Community, Minor update, Progress: approved

#735 magento/merchdocs#729 2FA configuration docs
  src/images/images/config-2fa-general.png
Labels: 2.4.x, Community, Minor update, Progress: approved

#732 B2B updates for 2.4.1
  src/configuration/security/google-recaptcha-storefront.md
  src/customers/account-company-create.md
  src/customers/account-dashboard-approval-rules.md
  src/customers/account-dashboard-my-purchase-orders.md
  src/images/images-b2b/config-general-b2b-shipping-methods.png
  src/images/images-b2b/storefront-create-approval-rule.png
  src/images/images-b2b/storefront-my-purchase-orders.png
  src/images/images/config-security-google-recaptcha-storefront.png
  src/stores/b2b-features.md
Labels: 2.4.1, Minor update, Progress: review

#739 OMCONNECT-815: Move Commerce Admin Connector-related content from OMS Docs to user guide
  src/_data/toc/catalog.yml
  src/catalog/export-full-catalog.md
  src/catalog/products.md
  src/images/images-ee/products-export-full.png
  src/images/images-ee/system-report-new.png
  src/mcom/message-log.md
  src/system/support-system-report.md
Labels: 2.3.x, 2.4.x, New topic, Port change, Progress: approved

#740 Update account-dashboard-requisition-lists.md
  src/customers/account-dashboard-requisition-lists.md
Labels: 2.3.x, Community, Minor update, Progress: approved

#743 Add SuperLinter
  .github/linters/.markdownlint.json
  .github/linters/.ruby-lint.yml
  .github/workflows/linter.yml
  .github/workflows/main.yml
  .markdownlint.json
  Rakefile
  _plugins/github_path.rb
  _plugins/last_modified_at.rb
  bin/image_optim
  bin/jekyll
  bin/mdl
  bin/whatsup_github
  lib/double_slash_check.rb
  lib/link_checker.rb
  rakelib/build.rake
  rakelib/check.rake
  rakelib/preview.rake
  rakelib/test.rake
Labels: Progress: approved, Site improvements

#745 CAPTCHA checkout storefront
  src/configuration/customers/customer-configuration.md
  src/images/images-ee/config-customer-configuration-captcha.png
  src/images/images-ee/storefront-checkout-payment-captcha.png
  src/images/images/config-customer-configuration-captcha.png
  src/stores/security-captcha.md
Labels: 2.4.1, Minor update, Progress: approved, Security

#747 Remove outdated links #721
  src/_includes/web-setup-deprecate.md
Labels: 2.4.x, Community, Minor update, Progress: approved

#748 Misc edits
  src/magento/security-scan.md
Labels: 2.4.1, Minor update, Progress: approved

#746 CMS folder cleaning - Pt 1
  src/cms/page-builder-add-content-block.md
  src/cms/page-builder-add-content-products.md
  src/cms/page-builder-add-content.md
  src/cms/page-builder-add-dynamic-block.md
  src/cms/page-builder-elements-buttons.md
  src/cms/page-builder-elements-divider.md
  src/cms/page-builder-elements-heading.md
  src/cms/page-builder-elements-html-code.md
  src/cms/page-builder-elements-text.md
  src/cms/page-builder-elements.md
  src/cms/page-builder-layout-column.md
  src/cms/page-builder-layout-row.md
  src/cms/page-builder-layout-tabs.md
  src/cms/page-builder-layout.md
  src/cms/page-builder-learn.md
  src/cms/page-builder-media-banner.md
  src/cms/page-builder-media-image.md
  src/cms/page-builder-media-map.md
  src/cms/page-builder-media-slider.md
  src/cms/page-builder-media-video.md
  src/cms/page-builder-media.md
  src/cms/page-builder-setup.md
  src/cms/page-builder-templates.md
  src/cms/page-builder-tutorial1-simple-page.md
  src/cms/page-builder-tutorial2-blocks.md
  src/cms/page-builder-tutorial3-catalog-content.md
  src/cms/page-builder-workspace.md
  src/cms/page-builder.md
  src/images/images-ee/icon-pb-add-image.png
  src/images/images-ee/page-builder-elements-heading-drag.png
  src/images/images-ee/page-builder-elements-text-editor-tools.png
  src/images/images-ee/page-builder-row-layout.png
  src/images/images-ee/page-builder-tabs-toolbox-settings.png
  src/images/images-ee/pagebuilder-templates-apply-slideout-withfilters.png
Labels: 2.3.x, Editorial, Progress: review

#750 Fix caption formatting
  src/stores/admin-signin.md
Labels: 2.4.x, Editorial, Progress: approved

#752 Stored Payment Methods is available in OpenSource
  src/customers/account-dashboard-stored-payment-methods.md
Labels: 2.4.x, Community, Minor update, Port change, Progress: approved

#754 Updated "Changes in the latest release" for 2.4.1
  src/tax/vertex.md
Labels: 2.4.1, Minor update, Progress: approved

#756 dotdigital - Updated "Changes in the latest release" for 2.4.1
  src/marketing/dotdigital/engagement-cloud.md
Labels: 2.4.1, Minor update, Progress: approved

#755 CMS folder topic tune up GH 547 - content elements
  src/_data/toc/content.yml
  src/cms/adobe-stock-manage.md
  src/cms/adobe-stock.md
  src/cms/block-add.md
  src/cms/block-position.md
  src/cms/blocks.md
  src/cms/content-elements.md
  src/cms/content-menu.md
  src/cms/dynamic-blocks-price-rules.md
  src/cms/dynamic-blocks-rotate.md
  src/cms/dynamic-blocks.md
  src/cms/editor-configure.md
  src/cms/editor-insert-image.md
  src/cms/editor-insert-link.md
  src/cms/editor-insert-variable.md
  src/cms/editor-widget.md
  src/cms/editor.md
  src/cms/lightboxes-and-sliders.md
  src/cms/media-storage.md
  src/cms/page-actions.md
  src/cms/page-add.md
  src/cms/page-duplicate.md
  src/cms/page-hierarchy-configure.md
  src/cms/page-hierarchy-node-add.md
  src/cms/page-hierarchy.md
  src/cms/page-home-new.md
  src/cms/page-scheduled-changes.md
  src/cms/page-translate.md
  src/cms/pages-core.md
  src/cms/pages-default.md
  src/cms/pages-grid-columns.md
  src/cms/pages-search.md
  src/cms/pages-workspace.md
  src/cms/pages.md
  src/cms/widget-create.md
  src/cms/widget-event-carousel.md
  src/cms/widget-new-products-list.md
  src/cms/widget-orders-returns.md
  src/cms/widget-static-block.md
  src/cms/widget-types.md
  src/cms/widgets.md
  src/images/images-ee/admin-menu-content-ee.png
  src/images/images-ee/page-builder-workspace-block.png
  src/images/images/content-insert-variable.png
  src/images/images/editor-menu-widget-button.png
  src/images/images/editor-toolbar/editor-dialog-insert-image.png
  src/images/images/editor-toolbar/editor-dialog-insert-link.png
  src/images/images/editor-toolbar/editor-menu-image-button.png
  src/images/images/editor-toolbar/editor-menu-link-button.png
  src/images/images/editor-toolbar/editor-menu-variable-button.png
  src/images/images/editor-toolbar/editor-menu-widget-button.png
  src/images/images/media-storage-insert-file.png
Labels: 2.3.x, Editorial, Progress: review

#751 Sales folder topic tune up GH 725 - cart and checkout topics
  src/_data/toc/marketing.yml
  src/_data/toc/sales.yml
  src/configuration/sales/sales.md
  src/images/images/config-sales-sales-minimum-order-amount.png
  src/images/images/storefront-cart-full.png
  src/images/images/storefront-cart-minimum-order-amount.png
  src/images/images/storefront-checkout-totals.png
  src/images/images/storefront-mini-cart-watch.png
  src/images/images/storefront-my-cart-link.png
  src/magento/prelaunch-checklist.md
  src/payment/amazon-pay-customer-experience.md
  src/quick-tour/reduce-ordering-errors.md
  src/sales/batches.md
  src/sales/billing-agreements.md
  src/sales/cart-configuration.md
  src/sales/cart-link.md
  src/sales/cart-minimum-order-amount.md
  src/sales/cart-persistent-configuration.md
  src/sales/cart-persistent-workflow.md
  src/sales/cart-persistent.md
  src/sales/cart-quote-lifetime.md
  src/sales/cart-redirect.md
  src/sales/cart-sidebar.md
  src/sales/cart-thumbnails.md
  src/sales/cart.md
  src/sales/checkout-address-search.md
  src/sales/checkout-configuration.md
  src/sales/checkout-guest.md
  src/sales/checkout-instant-purchase.md
  src/sales/checkout-onepage.md
  src/sales/checkout-options.md
  src/sales/checkout-order-confirmation.md
  src/sales/checkout-payment-failed-emails.md
  src/sales/checkout-process.md
  src/sales/checkout-step1-shipping.md
  src/sales/checkout-step2-payment-review.md
  src/sales/checkout-totals-sort-order.md
  src/sales/minimum-order-amount.md
  src/sales/reorders-allow.md
  src/stores/attributes-customer-address.md
  src/stores/store-scope-reference.md
Labels: 2.3.x, Editorial, Progress: review

#760 Updated media gallery configuration information
  src/cms/media-gallery.md
  src/configuration/advanced/system.md
  src/images/images/enhanced-media-gallery/system-enhanced-media-gallery.png
Labels: 2.4.1, Minor update, Progress: on hold, Stakeholder

#758 Updates for shipping methods B2B config ref and synch with procedures
  src/configuration/general/b2b-features.md
  src/customers/account-company-create.md
  src/images/images-b2b/config-general-b2b-features-default-payment-methods.png
  src/images/images-b2b/config-general-b2b-features-enable-company.png
  src/images/images-b2b/config-general-b2b-features.png
  src/images/images-b2b/config-general-b2b-shipping-methods.png
  src/images/images-b2b/customers-company-create-advanced-settings-customer-group-admin.png
  src/stores/b2b-features.md
Labels: 2.4.1, Major update, Progress: review

#759 Add clear cart config option
  src/configuration/sales/checkout.md
  src/images/images-b2b/config-sales-checkout-shopping-cart.png
  src/sales/checkout-options.md
Labels: 2.4.1, Minor update, Progress: approved

#757 Amazon Pay - Updated "Changes in latest release"
  src/payment/amazon-pay.md
Labels: 2.4.1, Minor update, Progress: approved

#761 Update category-modify.md
  src/catalog/category-modify.md
Labels: 2.4.x, Community, Minor update, Port change, Progress: approved

#765 CMS folder topic tune up GH 547 - content staging
  src/_data/toc/content.yml
  src/cms/content-staging-add-item.md
  src/cms/content-staging-dashboard-view-edit.md
  src/cms/content-staging-dashboard.md
  src/cms/content-staging-preview.md
  src/cms/content-staging-scheduled-update.md
  src/cms/content-staging-workflow.md
  src/cms/content-staging.md
  src/images/images-ee/content-staging-assign-existing-category-imagepng.png
  src/images/images-ee/content-staging-assign-to-existing-campaign.png
  src/images/images-ee/content-staging-campaign-edit-products.png
  src/images/images-ee/content-staging-campaign-info.png
  src/images/images-ee/content-staging-campaign-product-schedule-new-update.png
  src/images/images-ee/content-staging-campaign-schedule-update.png
  src/images/images-ee/content-staging-category-image-preview.png
  src/images/images-ee/content-staging-dashboard-duffle-bag-special.png
  src/images/images-ee/content-staging-dashboard-grid.png
  src/images/images-ee/content-staging-dashboard-summary.png
  src/images/images-ee/content-staging-dashboard-timeline.png
  src/images/images-ee/content-staging-dashboard-view-edit.png
  src/images/images-ee/content-staging-existing-category-image.png
  src/images/images-ee/content-staging-grid-view.png
  src/images/images-ee/content-staging-preview.png
  src/images/images-ee/content-staging-price-rule-catalog-scheduled-change.png
  src/images/images-ee/content-staging-product-calendar-share-link.png
  src/images/images-ee/content-staging-product-duffle-bag-edit.png
  src/images/images-ee/content-staging-product-preview-calendar.png
  src/images/images-ee/content-staging-product-schedule-new-update.png
  src/images/images-ee/content-staging-product-schedule-update.png
  src/images/images-ee/content-staging-product-scheduled-update-preview-rope.png
  src/images/images-ee/content-staging-product-scheduled-update-preview.png
  src/images/images-ee/content-staging-product-section-edit.png
  src/images/images-ee/content-staging-scheduled-changes.png
  src/images/images-ee/content-staging-timeline-4-week-view.png
Labels: 2.3.x, Editorial, Progress: review

#764 763 Removed Quote from the link url
  src/tax/vat.md
Labels: 2.4.x, Editorial, Progress: approved

#770 Updates for Page Builder preview for product and category forms
  src/_data/toc/catalog.yml
  src/catalog/categories-content-settings.md
  src/catalog/category-create.md
  src/catalog/product-content.md
  src/configuration/general/content-management.md
  src/images/images-ee/catalog-product-content.png
  src/images/images-ee/category-content.png
  src/images/images-ee/product-category-content-preview.png
  src/images/images/category-content-ce.png
  src/images/images/config-general-content-management-advanced-content-tools.png
  src/images/images/product-simple-content.png
Labels: 2.4.1, Major update, Progress: review

#774 Remove URL to obsolete video
  src/payment/amazon-pay-setup.md
Labels: 2.4.x, Editorial, Port change, Progress: review

#773 Swat tool update
  src/images/images-ee/reports-swat-dashboard.png
  src/images/images-ee/reports-swat-information-tab.png
  src/images/images-ee/reports-swat-report-settings.png
  src/images/images-ee/reports-swat-tos.png
  src/reports/site-wide-analysis-tool.md
Labels: 2.4.1, Minor update, Progress: approved

#776 Added "Changes in this release"
  src/payment/braintree.md
Labels: 2.4.1, Minor update, Progress: approved

#777 Updated "Changes in the latest release"
  src/payment/klarna.md
Labels: 2.4.1, Minor update, Progress: approved

#778 Updated "Changes in the latest release"
  src/marketing/yotpo-reviews-intro.md
Labels: 2.4.1, Minor update, Progress: approved
