Repository magento/merchdocs, pull requests merged in 2020-11, with the labels that each got.

#835 Update admin-dashboard.md
  src/stores/admin-dashboard.md
Labels: 2.4.x, Minor update, Port change, Progress: approved, Stakeholder

#826 Changes to dynamic block creation process
  src/cms/dynamic-blocks.md
Labels: 2.4.x, Progress: on hold, hacktoberfest_accepted

#830 Back port changes to 2.3.x
  src/cms/adobe-stock.md
  src/cms/widget-new-products-list.md
  src/marketing/google-universal-analytics.md
  src/sales/reorders-allow.md
  src/stores/store-urls-custom-admin.md
Labels: 2.3.x, Back port, Progress: approved, hacktoberfest_accepted

#843 Fix misleading description of robots functionality
  src/marketing/search-engine-robots.md
Labels: 2.4.x, Community, Minor update, Partner: Something Digital, Progress: approved, partners-contribution

#841 Fixed incorrect section label
  src/marketing/price-rules-cart-create.md
Labels: 2.4.x, Editorial, Progress: approved, internal-dev

#845 Fix "user system value" typo in country options
  src/stores/country-options.md
Labels: 2.4.x, Community, Editorial, Partner: Vaimo, Progress: approved, partners-contribution

#812 Improve link reference for client-side optimization info
  src/system/file-optimization.md
Labels: 2.x, Editorial, Progress: approved, hacktoberfest_accepted

#846 Update products grid page
  src/catalog/products.md
Labels: 2.4.x, Community, Editorial, Partner: Webjump, Progress: approved, partners-contribution

#849 Update customer-groups.md
  src/customers/customer-groups.md
Labels: 2.4.x, Community, Minor update, Port change, Progress: approved

#853 Added caveat for cart price rules
  src/marketing/price-rule-cart-scheduled-changes.md
Labels: Editorial, Progress: approved

#854 Duplicated word removal
  src/getting-started/contribute.md
Labels: Editorial, Progress: approved

#855 Update price-rules-catalog.md
  src/marketing/price-rules-catalog.md
Labels: Partner: Pinpoint, Progress: approved, partners-contribution

#847 Topic tuneup - payment folder, pt 1 - GH 831
  src/_data/toc/sales.yml
  src/_includes/VBE-note.md
  src/images/images/config-sales-payment-methods-amazon-pay-account-setup.png
  src/images/images/config-sales-payment-methods-paypal-express-checkout-settings.png
  src/images/images/config-sales-payment-methods-paypal-express-required.png
  src/images/images/config-sales-payment-methods-paypal-payments-standard-display.png
  src/images/images/config-sales-payment-methods-paypal-payments-standard-required.png
  src/images/images/payments-amazon-pay-seller-central-copy-keys.png
  src/images/images/payments-amazon-pay-seller-central-copy-your-keys.png
  src/images/images/payments-amazon-pay-seller-central-dashboard.png
  src/images/images/payments-amazon-pay-seller-central-integration-central-keys.png
  src/images/images/payments-amazon-pay-seller-central-integration-central.png
  src/images/images/payments-amazon-pay-seller-central-integration-menu.png
  src/images/images/payments-amazon-pay-seller-central-integration-mws-access-keys.png
  src/images/images/payments-amazon-pay-seller-central-sandbox-view.png
  src/images/images/payments-amazon-pay-seller-central-view-chooser.png
  src/images/images/payments-amazon-pay-seller-central-view-production.png
  src/images/images/payments-klarna-dashboard-playground-env.png
  src/images/images/payments-klarna-merchant-account-create.png
  src/magento/change-log.md
  src/magento/prelaunch-checklist.md
  src/payment/amazon-pay-customer-experience.md
  src/payment/amazon-pay-manage.md
  src/payment/amazon-pay-resources.md
  src/payment/amazon-pay-seller-central.md
  src/payment/amazon-pay-setup.md
  src/payment/amazon-pay.md
  src/payment/bank-transfer.md
  src/payment/cash-on-delivery.md
  src/payment/check-money-order.md
  src/payment/gateways.md
  src/payment/klarna-customer-experience.md
  src/payment/klarna-manage.md
  src/payment/klarna-setup.md
  src/payment/merchant-location.md
  src/payment/offline-payment-methods.md
  src/payment/online-payment-methods.md
  src/payment/payment-methods.md
  src/payment/payment-on-account.md
  src/payment/payments.md
  src/payment/paypal-billing-agreements.md
  src/payment/paypal-business-account.md
  src/payment/paypal-countries.md
  src/payment/paypal-credit.md
  src/payment/paypal-express-checkout.md
  src/payment/paypal-fraud-management-filter.md
  src/payment/paypal-in-context-checkout.md
  src/payment/paypal-payflow-link.md
  src/payment/paypal-payflow-pro.md
  src/payment/paypal-payment-solutions.md
  src/payment/paypal-payments-advanced.md
  src/payment/paypal-payments-pro.md
  src/payment/paypal-payments-standard.md
  src/payment/paypal-settlement-reports.md
  src/payment/paypal.md
  src/payment/purchase-order.md
  src/payment/recommended-solutions.md
  src/payment/zero-subtotal-checkout.md
Labels: 2.3.x, Editorial, Progress: review

#858 Update email-template-message.md
  src/marketing/email-template-message.md
Labels: 2.4.x, Editorial, Progress: approved

#852 PAY-658: Payout report view
  src/images/images/btn-download.png
  src/magento-payments/payouts.md
Labels: Progress: approved

#865 Adding info in General Tax Settings doc
  src/images/images/config-sales-tax-orders-fixed-product-taxes.png
  src/tax/tax-settings-general.md
Labels: 2.4.x, Community, Minor update, Progress: approved

#866 Adding info in Configuring Tax Classes doc
  src/images/images/config-sales-tax-tax-classes.png
  src/tax/tax-class-configure.md
Labels: 2.4.x, Community, Minor update, Progress: approved

#867 Adding info in Creating a Customer Segment doc
  src/marketing/customer-segment-create.md
Labels: 2.4.x, Community, Editorial, Progress: approved, small changes

#869 Fixing typo in Order Actions doc
  src/sales/order-actions.md
Labels: 2.4.x, Community, Editorial, Progress: approved, small changes

#863 Adding info in Creating a Catalog Price Rule doc
  src/marketing/price-rules-catalog-create.md
Labels: 2.4.x, Community, Minor update, Progress: approved

#864 Adding info in Password Options doc
  src/customers/password-options.md
  src/images/images/config-customers-customer-configuration-password-options.png
Labels: 2.4.x, Community, Minor update, Progress: approved

#868 Adding info in Configuring a Persistent Cart doc
  src/images/images/config-customers-persistent-shopping-cart-general-options.png
  src/sales/cart-persistent-configuration.md
Labels: 2.4.x, Community, Major update, Progress: approved

#862 Adding info in Requisition Lists doc
  src/configuration/customers/requisition-lists.md
Labels: Progress: review

#861 Update documentation for async coupon usage processing
  src/marketing/price-rules-cart-coupon.md
Labels: 2.4.x, Minor update, Port change, Progress: approved, Stakeholder

#872 added authentication locks config info
  src/configuration/services/oauth.md
  src/images/images/config-services-oauth-authentication-locks.png
Labels: 2.4.x, Community, Major update, Partner: EY, Progress: approved, partners-contribution

#873 added internal link towards maximum qty discount formula
  src/marketing/price-rules-cart-buy-x-get-y-free.md
Labels: 2.4.x, Community, Minor update, Partner: EY, Progress: approved, partners-contribution

#877 ISSUE-499 - Update images for data export
  src/images/images/data-transfer-csv-notepad++customer.png
  src/images/images/data-transfer-csv-openoffice.png
  src/images/images/data-transfer-csv-product-notepad++.png
  src/images/images/data-transfer-cvs-customer-openoffice.png
  src/system/data-csv.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#875 Added documentation for gift options
  src/configuration/sales/sales.md
  src/images/images/config-sales-sales-gift-options.png
Labels: 2.4.x, Community, Major update, Partner: EY, Progress: approved, partners-contribution

#840 B2B 2.4.2 additions
  src/_data/toc/getting-started.yml
  src/images/images-b2b/purchase-order-flow.png
  src/marketing/price-rules-cart-create.md
  src/stores/b2b-basics.md
  src/stores/b2b-purchase-order-flow.md
Labels: 2.4.2, New topic, Progress: approved

#876 issue-857-added a disclaimer for the gift registry inactivation info
  src/marketing/gift-registry-information.md
Labels: 2.4.x, Community, Minor update, Partner: EY, Progress: approved, partners-contribution
