Repository magento/merchdocs, pull requests merged in 2020-10, with the labels that each got.

#762 Added Media Gallery Image Optimization Documenation
  src/_data/toc/content.yml
  src/cms/media-gallery-image-optimization.md
  src/cms/media-gallery.md
  src/configuration/advanced/system.md
  src/images/images/enhanced-media-gallery/system-image-optimization.png
Labels: 2.4.2, New topic, Progress: review, Stakeholder

#781 Back port changes to 2.3.x
  src/_data/toc/catalog.yml
  src/catalog/category-modify.md
  src/catalog/export-full-catalog.md
  src/catalog/products.md
  src/customers/account-dashboard-stored-payment-methods.md
  src/images/images-ee/products-export-full.png
  src/images/images-ee/system-report-new.png
  src/magento/change-log.md
  src/marketing/price-rules-catalog-create.md
  src/marketing/promotions.md
  src/mcom/message-log.md
  src/payment/amazon-pay-setup.md
  src/sales/quotes.md
  src/system/support-system-report.md
Labels: 2.3.x, Back port, Progress: approved

#771 Commit Search skeleton
  _config.yml
  src/_data/main-nav.yml
  src/_data/toc/marketing.yml
  src/live-search/api-ref.md
  src/live-search/connect.md
  src/live-search/customize.md
  src/live-search/data-types.md
  src/live-search/facet-behavior.md
  src/live-search/facet-create.md
  src/live-search/facet-delete.md
  src/live-search/facet-edit.md
  src/live-search/facet-example.md
  src/live-search/facet-manage.md
  src/live-search/facet-setup.md
  src/live-search/facets.md
  src/live-search/getting-started.md
  src/live-search/install.md
  src/live-search/live-search.md
  src/live-search/overview.md
  src/live-search/performance.md
  src/live-search/requirements.md
  src/live-search/rules-create.md
  src/live-search/rules-delete.md
  src/live-search/rules-details.md
  src/live-search/rules-duplicate.md
  src/live-search/rules-edit.md
  src/live-search/rules.md
  src/live-search/saas.md
  src/live-search/sdk-ref.md
  src/live-search/synonyms-create.md
  src/live-search/synonyms-delete.md
  src/live-search/synonyms-edit.md
  src/live-search/synonyms-manage.md
  src/live-search/synonyms-one-way.md
  src/live-search/synonyms-setup.md
  src/live-search/synonyms-two-way.md
  src/live-search/synonyms-types.md
  src/live-search/synonyms.md
Labels: Progress: approved, Search

#783 Amazon 4.3.0
  src/sales-channels/asc/amazon-matching-attributes-values.md
  src/sales-channels/asc/amazon-order-details.md
  src/sales-channels/asc/amazon-orders-all.md
  src/sales-channels/asc/amazon-sales-channel-home.md
  src/sales-channels/asc/amazon-verify-api-key.md
  src/sales-channels/asc/assets/amazon-order-details-header.png
  src/sales-channels/asc/assets/amazon-order-details.png
  src/sales-channels/asc/assets/amazon-order-item-details.png
  src/sales-channels/asc/assets/amazon-order-tracking-details.png
  src/sales-channels/asc/attributes-view.md
  src/sales-channels/asc/cancel-unshipped-order.md
  src/sales-channels/asc/creating-attributes.md
  src/sales-channels/asc/managing-listings-by-action.md
  src/sales-channels/asc/managing-listings-by-tab.md
  src/sales-channels/asc/managing-product-listings.md
  src/sales-channels/asc/ob-store-review.md
  src/sales-channels/asc/store-integration.md
Labels: Progress: approved, asc-non-release

#784 Update the Lint Code Base check
  .github/workflows/linter.yml
Labels: Progress: review, maintenance

#786 Updated Adobe Stock Integration configuration instructions
  src/cms/adobe-stock.md
Labels: 2.4.x, Minor update, Port change, Progress: on hold

#788 Whats New update
  src/_data/whats-new.yml
Labels: 2.4.x, Progress: approved, Site improvements

#789 Adding link to Commerce topic
  src/cms/widget-new-products-list.md
Labels: 2.4.x, Community, Progress: approved

#797 Introduction of the new admin user email template
  src/marketing/email-template-list.md
Labels: 2.4.2, Minor update, Progress: approved

#799 Note for blocking nested links for banner and slider
  src/cms/page-builder-media-banner.md
  src/cms/page-builder-media-slider.md
  src/images/images-ee/page-builder-nested-link-blocked.png
Labels: 2.4.1, Minor update, Progress: approved

#790 Update obsolete info on changing the Admin Path trough CLI and add recovery option
  src/stores/store-urls-custom-admin.md
Labels: 2.4.x, Major update, Port change, Progress: approved, Stakeholder

#803 Update What's New for 2.4.1 GA docs
  src/_data/whats-new.yml
Labels: 2.4.1, Progress: review, maintenance

#809 Add redirect to handle 404
  src/reports/advanced-reporting.md
Labels: 2.4.x, Progress: approved, bug

#800 Update Rakefile with latest
  Rakefile
Labels: Progress: changes requested, maintenance

#811 Remove incorrect permissions link on magento.com account share page
  src/magento/magento-account-share.md
Labels: 2.4.x, Community, Minor update, Port change, Progress: approved

#791 Update quote-workflow.md
  src/sales/quote-workflow.md
Labels: Community, Editorial, Event: Distributed CD India 2020, Partner: Wagento, Progress: approved, partners-contribution, small changes

#793 Update sitemap-xml.md
  src/marketing/sitemap-xml.md
Labels: Community, Editorial, Event: Distributed CD India 2020, Partner: Wagento, Progress: approved, partners-contribution, small changes

#794 Update inventory-management.md
  src/catalog/inventory-management.md
Labels: Community, Editorial, Event: Distributed CD India 2020, Partner: Wagento, Progress: approved, partners-contribution, small changes

#806 MC-37830: [Documentation] New Products List
  src/cms/widget-new-products-list.md
Labels: 2.4.x, Editorial, Port change, Progress: on hold, Stakeholder

#796 Clarifying Execution Time
  src/system/data-import-history.md
Labels: 2.4.x, Minor update, Progress: changes requested

#813 Small changes
  src/catalog/inventory-management.md
  src/marketing/sitemap-xml.md
  src/sales/quote-workflow.md
Labels: Progress: approved, maintenance

#815 Magento folder content tune up
  src/images/images/magento-marketplace.png
  src/magento/installation-modes.md
  src/magento/installation.md
  src/magento/magento-account-create.md
  src/magento/magento-account-secure.md
  src/magento/magento-account-share.md
  src/magento/magento-account.md
  src/magento/magento-extensions.md
  src/magento/magento-marketplace-credentials.md
  src/magento/magento-marketplace-install-extension.md
  src/magento/magento-marketplace-synchronize-store.md
  src/magento/magento-marketplace.md
  src/magento/magento-security-best-practices.md
  src/magento/prelaunch-checklist.md
  src/magento/security-action-plan.md
  src/magento/security-scan.md
Labels: 2.3.x, Editorial, Port change, Progress: review

#817 getting-started folder content tune up
  src/_data/toc/getting-started.yml
  src/getting-started/contribute.md
  src/getting-started/login-credentials.md
  src/getting-started/magento-ecosystem.md
  src/getting-started/quick-tour.md
  src/getting-started/resources.md
Labels: 2.3.x, Editorial, Port change, Progress: approved

#795 Update inventory-orders-shipment.md
  src/catalog/inventory-orders-shipment.md
Labels: Community, Editorial, Event: Distributed CD India 2020, Partner: Wagento, Progress: changes requested, partners-contribution

#821 Change the logo to Adobe
  Gemfile.lock
  _config.yml
Labels: Progress: approved, Site improvements, maintenance

#814 Expanding SaaS Content
  src/_data/toc/operations.yml
  src/configuration/services/saas.md
  src/system/saas.md
Labels: 2.4.x, New topic, Progress: approved, Stakeholder

#824 magento/merchdocs#: Updates Criteria for Reorder
  src/sales/reorders-allow.md
Labels: 2.4.x, Event: MageCONF CD 2020, Minor update, Partner: Atwix, Port change, Progress: on hold, partners-contribution

#825 magento/merchdocs#: Add a notice about Google Analytics and Cookie Restriction Mode
  src/marketing/google-universal-analytics.md
Labels: 2.4.x, Event: MageCONF CD 2020, Minor update, Partner: Atwix, Port change, Progress: approved, partners-contribution

#818 OMCONNECT-911: Create New Order doc etc. changes
  src/customers/customer-account-create-order.md
  src/sales/orders-workspace.md
  src/sales/orders.md
  src/stores/configuration-overview.md
Labels: Editorial, Progress: approved

#827 Magento Identity Manager
  src/images/images/id-manager-2fa.png
  src/images/images/id-manager-adobe-create.png
  src/images/images/id-manager-adobe-login.png
  src/images/images/id-manager-email-link.png
  src/images/images/id-manager-mccom-login.png
  src/images/images/id-manager-mccom-mim-login.png
  src/images/images/id-manager-mim-add-message.png
  src/images/images/id-manager-mim-dropdown-closed.png
  src/images/images/id-manager-mim-dropdown-open.png
  src/images/images/id-manager-mim-link.png
  src/images/images/id-manager-mim-one.png
  src/images/images/id-manager-mim-remove-confirm.png
  src/images/images/id-manager-mim-remove.png
  src/images/images/id-manager-mim-reorder.png
  src/images/images/id-manager-mim-reorder2.png
  src/images/images/id-manager-mim-success.png
  src/images/images/id-manager-mim-zero.png
  src/magento/magento-identity-manager.md
Labels: Progress: approved

#823 Topic tuneup - design folder - GH 768
  src/design/configuration.md
  src/design/copyright-notice.md
  src/design/demo-notice.md
  src/design/design-menu.md
  src/design/design-theme.md
  src/design/favicon.md
  src/design/footer.md
  src/design/header.md
  src/design/html-head.md
  src/design/layout-update-place-block.md
  src/design/layout-updates.md
  src/design/logo-upload.md
  src/design/merge-css.md
  src/design/merge-javascript.md
  src/design/page-layout-examples.md
  src/design/page-layout-standard.md
  src/design/page-layout.md
  src/design/page-setup.md
  src/design/schedule.md
  src/design/storefront-branding.md
  src/design/theme-assets.md
  src/design/theme-default.md
  src/design/theme-install.md
  src/design/themes.md
  src/design/welcome-message.md
  src/images/images/admin-menu-content-design.png
  src/images/images/config-design-footer.png
  src/images/images/config-design-header.png
  src/images/images/config-design-html-head.png
  src/images/images/config-design-theme-edit.png
  src/images/images/design-configuration-footer.png
  src/images/images/design-configuration-header.png
  src/images/images/design-configuration-html-head.png
  src/images/images/favicon-upload.png
  src/images/images/marketplace-themes.png
  src/images/images/storefront-demo-notice.png
  src/images/images/storefront-favicon.png
  src/images/images/storefront-footer-copyright.png
  src/images/images/storefront-header-logo.png
  src/images/images/storefront-home-html-inspect.png
  src/images/images/storefront-home-page-branding.png
  src/images/images/storefront-welcome-message.png
Labels: 2.3.x, Editorial, Event: MageCONF CD 2020, Progress: review

#828 Magento Identity Manager
  src/_data/main-nav.yml
  src/_data/toc/getting-started.yml
  src/images/images/id-manager-2fa.png
  src/images/images/id-manager-adobe-create.png
  src/images/images/id-manager-adobe-login.png
  src/images/images/id-manager-email-link.png
  src/images/images/id-manager-mccom-login.png
  src/images/images/id-manager-mccom-mim-login.png
  src/images/images/id-manager-mim-add-message.png
  src/images/images/id-manager-mim-dropdown-closed.png
  src/images/images/id-manager-mim-dropdown-open.png
  src/images/images/id-manager-mim-link.png
  src/images/images/id-manager-mim-one.png
  src/images/images/id-manager-mim-remove-confirm.png
  src/images/images/id-manager-mim-remove.png
  src/images/images/id-manager-mim-reorder.png
  src/images/images/id-manager-mim-reorder2.png
  src/images/images/id-manager-mim-success.png
  src/images/images/id-manager-mim-zero.png
  src/magento/magento-identity-manager.md
Labels: New topic, Progress: approved
