Repository magento/merchdocs, pull requests merged in 2020-07, with the labels that each got.

#568 Added a note for product grid filter control option
  src/stores/attributes-product.md
Labels: Minor update, Partner: Ziffity, Progress: approved

#570 Adding link to Page Builder install page
  src/marketing/page-builder-add-product-recs.md
  src/marketing/product-recommendations.md
Labels: 2.3.3, Editorial, Progress: approved

#572 Update rma-customer-experience.md
  src/sales/rma-customer-experience.md
Labels: Editorial

#573 Update login-as-customer.md
  src/configuration/customers/login-as-customer.md
Labels: Progress: approved

#522 Markdown linting: MD030
  _checks/styles/style-rules-dev
  _checks/styles/style-rules-prod
  src/cms/page-builder-templates.md
  src/marketing/create-new-rec.md
  src/marketing/dotdigital/data-mapping.md
  src/marketing/dotdigital/engagement-cloud.md
  src/marketing/edit-existing-rec.md
  src/marketing/page-builder-add-product-recs.md
  src/marketing/price-rules-cart-coupon.md
  src/marketing/price-rules-cart.md
  src/marketing/product-recommendations.md
  src/marketing/recommendation-best-practices.md
  src/marketing/recommendation-change-source.md
  src/marketing/recommendation-metrics.md
  src/mcom/integration.md
  src/payment/klarna.md
  src/sales-channels/amazon/creating-assigning-catalog-products.md
  src/shipping/magento-shipping-carriers.md
  src/shipping/magento-shipping-experience-rules.md
  src/shipping/magento-shipping-locations.md
  src/shipping/magento-shipping-packaging.md
  src/shipping/magento-shipping-pre-packaged.md
  src/shipping/point-of-origin.md
  src/shipping/shipping-free.md
  src/shipping/shipping-label-workflow.md
  src/shipping/shipping-multiaddress.md
  src/shipping/shipping-policy-parameters.md
  src/stores/b2b-configure-quotes.md
  src/system/data-transfer-bundle-products.md
  src/system/data-transfer-examples.md
Labels: Editorial, Progress: approved, Site improvements

#575 Magento account 2fa
  src/_data/toc/getting-started.yml
  src/images/images/magento-account-2fa-disable-confirmation.png
  src/images/images/magento-account-2fa-enable-verify-password.png
  src/images/images/magento-account-2fa-enable.png
  src/images/images/magento-account-2fa-generate-recovery-codes.png
  src/images/images/magento-account-2fa-login-recovery-code.png
  src/images/images/magento-account-2fa-login-recovery-email.png
  src/images/images/magento-account-2fa-login-verification-code.png
  src/images/images/magento-account-2fa-manage-verify-password.png
  src/images/images/magento-account-2fa-manage.png
  src/images/images/magento-account-2fa-set-recovery-email.png
  src/images/images/magento-account-2fa-setup-app.png
  src/images/images/magento-account-2fa-store-recovery-codes.png
  src/images/images/magento-account-2fa-view-recovery-codes.png
  src/images/images/magento-account-login.png
  src/magento/magento-account-secure.md
Labels: New topic, Progress: approved

#576 Edit to fix grammar
  src/magento/magento-account-secure.md
Labels: Editorial, Progress: approved

#579 Removed extra "your"
  src/stores/compliance-gdpr.md
Labels: Editorial, Minor update, Progress: approved

#584 MC-35842: Add changes in Magento user guide
  src/system/cron.md
Labels: Minor update, Progress: approved

#578 Yotpo Updates for 2.4
  src/configuration/yotpo/reviews-visual-marketing.md
  src/images/images/config-yotpo.png
  src/images/images/yotpo-config-setup-default.png
  src/images/images/yotpo-config-setup.png
  src/marketing/yotpo-connect.md
  src/marketing/yotpo-reviews-intro.md
  src/marketing/yotpo-settings.md
Labels: 2.4.0, Minor update, Progress: approved

#558 2.4.0 Purchase Orders for B2B
  src/_data/toc/customers.yml
  src/configuration/general/b2b-features.md
  src/configuration/sales/sales-emails.md
  src/customers/account-company-roles-permissions.md
  src/customers/account-dashboard-approval-rules.md
  src/customers/account-dashboard-my-purchase-orders.md
  src/customers/account-dashboard-quotes-negotiate.md
  src/customers/account-dashboard.md
  src/images/images-b2b/config-general-b2b-features-order_approval_config.png
  src/images/images-b2b/config-sales-sales-emails-purchase-order-approval.png
  src/images/images-b2b/storefront-approval-rule-number-skus.png
  src/images/images-b2b/storefront-approval-rule-order-total.png
  src/images/images-b2b/storefront-approval-rule-shipping-cost.png
  src/images/images-b2b/storefront-approval-rules.png
  src/images/images-b2b/storefront-my-purchase-orders.png
Labels: 2.4.0, Major update, New topic, Progress: approved

#580 Google re captcha
  src/_data/toc/config-ref.yml
  src/configuration/security/google-recaptcha-admin.md
  src/configuration/security/google-recaptcha-storefront.md
  src/configuration/security/google-recaptcha.md
  src/images/images/config-security-google-recaptcha-admin-v2-invisible.png
  src/images/images/config-security-google-recaptcha-admin-v2-not-robot.png
  src/images/images/config-security-google-recaptcha-admin-v3-invisible.png
  src/images/images/config-security-google-recaptcha-admin.png
  src/images/images/config-security-google-recaptcha-storefront-v2-invisible.png
  src/images/images/config-security-google-recaptcha-storefront-v2-not-robot.png
  src/images/images/config-security-google-recaptcha-storefront-v3-invisible.png
  src/images/images/config-security-google-recaptcha-storefront.png
  src/stores/security-captcha.md
  src/stores/security-google-recaptcha.md
Labels: 2.4.0, New topic, Progress: review

#563 Login as Customer for 2.4.0
  src/_data/toc/config-ref.yml
  src/_data/toc/customers.yml
  src/configuration/customers/login-as-customer.md
  src/customers/account-dashboard-my-orders.md
  src/customers/login-as-customer.md
  src/images/images-b2b/config-customers-login-as-customer.png
  src/images/images-ee/customer-account-order-invoices.png
  src/images/images-ee/customer-account-order-shipments.png
  src/images/images-ee/customers-login-as-customer-log-filter.png
  src/images/images-ee/customers-login-as-customer-role-resources.png
  src/images/images/customers-login-as-customer-use.png
  src/system/permissions-role-resources.md
Labels: 2.4.0, New topic, Progress: review

#581 Date time product attribute
  src/stores/attributes-input-types.md
Labels: 2.4.0, Minor update, Progress: approved

#585 Elasticsearch
  src/catalog/search-configuration.md
  src/configuration/catalog/catalog.md
  src/images/images-ee/config-catalog-catalog-search-elasticsearch-2.png
  src/images/images-ee/config-catalog-catalog-search.png
  src/images/images/config-catalog-catalog-search-elasticsearch-2.png
  src/images/images/config-catalog-catalog-search.png
Labels: 2.4.0, Minor update, Progress: review

#588 Adding whatsnew files and updating gitignore
  .gitignore
  src/_data/whats-new.yml
  src/whats-new.md
  src/whatsnew-feed.xml
Labels: 2.4.0, New topic, Progress: approved

#593 Hidden tax document
  src/_data/toc/operations.yml
  src/images/images/hidden-tax.png
  src/tax/hidden-tax-calculation.md
Labels: New topic, Progress: approved

#595 Adding content about out of stock products in recs
  src/marketing/product-recommendations.md
Labels: 2.3.5, Minor update, Progress: approved

#591 Media gallery terminology fix
  src/_data/toc/catalog.yml
  src/_data/toc/content.yml
  src/catalog/media-browser.md
  src/catalog/media-gallery.md
  src/catalog/search-configuration.md
  src/cms/adobe-stock-license-image.md
  src/cms/adobe-stock-manage.md
  src/cms/adobe-stock-save-preview.md
  src/cms/content-menu.md
  src/cms/media-gallery-asset-management.md
  src/cms/media-gallery-folder-management.md
  src/cms/media-gallery.md
  src/configuration/advanced/system.md
  src/stores/attributes-input-types.md
Labels: 2.4.0, Editorial, Progress: approved

#589 MC29863 - newsletter subscription management
  src/configuration/customers/newsletter.md
  src/customers/account-options-new.md
  src/customers/customer-account-manage.md
  src/images/images/config-customers-newsletter-general-options.png
  src/images/images/newsletter-customer-multi-site.png
  src/images/images/newsletter-customer-multi-store.png
  src/images/images/newsletter-customer-single-store.png
  src/images/images/newsletter-subscribers-export.png
  src/images/images/newsletter-unsubscribe.png
  src/marketing/newsletter-configuration.md
  src/marketing/newsletter-subscribers.md
Labels: 2.4.0, Major update, Progress: review

#597 Minor typo
  src/cms/page-hierarchy-node-add.md
Labels: 2.3.3, Editorial, Progress: approved

#599 Remove banners
  src/_data/toc/content.yml
  src/_data/toc/customers.yml
  src/cms/banner-create.md
  src/cms/banner-rotator.md
  src/cms/banners-price-rules.md
  src/cms/banners.md
  src/cms/content-menu.md
  src/cms/dynamic-blocks.md
  src/cms/widget-types.md
  src/images/images-ee/banner-10-pct.png
  src/images/images-ee/banner-default-content.png
  src/images/images-ee/banner-price-rule.png
  src/images/images-ee/banner-properties-customer-segment.png
  src/images/images-ee/banner-properties-default-content.png
  src/images/images-ee/banner-properties.png
  src/images/images-ee/banner-related-cart-price-rule.png
  src/images/images-ee/banner-related-promotions.png
  src/images/images-ee/banner-specify-types.png
  src/images/images-ee/banners-customer-segment.png
  src/images/images-ee/banners-grid.png
  src/images/images-ee/banners-list.png
  src/images/images-ee/banners.png
  src/images/images-ee/storefront-banner-free-shipping.png
  src/images/images-ee/storefront-banner.png
  src/images/images/price-rules-catalog-related-banner-10-pct.png
  src/marketing/customer-segment-banner.md
  src/marketing/customer-segment-create.md
  src/marketing/customer-segment-price-rule.md
  src/marketing/customer-segments.md
  src/marketing/markup-tags-links.md
  src/marketing/price-rules-cart-create.md
  src/marketing/price-rules-catalog-create.md
  src/quick-tour/catalog-page.md
Labels: Major update, Progress: review

#606 Deprecate native Braintree integration
  src/configuration/sales/braintree.md
  src/payment/braintree.md
Labels: 2.3.6, Minor update, Progress: approved

#605 2fa connect the dots
  src/_data/toc/getting-started.yml
  src/images/images/google-authenticator-iphone.png
  src/magento/magento-account-secure.md
  src/magento/magento-account.md
  src/stores/security-two-factor-authentication.md
Labels: 2.4.0, Minor update, Progress: approved

#604 MC-33183: New In-store delivery feature. Updated existing information and added new topics.
  src/_data/toc/catalog.yml
  src/_data/toc/sales.yml
  src/catalog/inventory-management.md
  src/catalog/inventory-migration.md
  src/catalog/inventory-sources-add.md
  src/catalog/inventory-sources.md
  src/catalog/settings-advanced-design.md
  src/catalog/settings-other.md
  src/catalog/settings.md
  src/catalog/sources.md
  src/configuration/sales/delivery-methods.md
  src/configuration/sales/sales-emails.md
  src/images/images-ee/order-view-in-store-delivery.png
  src/images/images-ee/product-settings-include-sources.png
  src/images/images/catalog-sources-list.png
  src/images/images/config-sales-emails-order-ready-pickup.png
  src/images/images/in-store-delivery.png
  src/images/images/luma-in-store-example.png
  src/images/images/order-view-in-store-delivery.png
  src/images/images/product-settings-include-sources.png
  src/images/images/select-in-store-delivery-populated.png
  src/images/images/select-in-store-delivery.png
  src/images/images/stores-inventory-pickup-location.png
  src/images/images/stores-inventory-source-general.png
  src/images/images/stores-inventory-sources.png
  src/marketing/email-template-list.md
  src/mcom.md
  src/sales/checkout-step1-shipping.md
  src/sales/order-processing.md
  src/shipping/methods-basic.md
  src/shipping/shipping-in-store-delivery.md
Labels: 2.4.0, Major update

#601 Klarna - Updated for 2.4 release
  src/payment/klarna.md
Labels: Progress: review

#602 Klarna Setup - Update for 2.4 release
  src/payment/klarna-setup.md
Labels: Progress: review

#607 AmazonPay setup guide changes to support new Integration Central pages
  src/images/images/payments-amazon-pay-seller-central-integration-central-keys.png
  src/images/images/payments-amazon-pay-seller-central-integration-central.png
  src/images/images/payments-amazon-pay-seller-central-integration-menu.png
  src/images/images/payments-amazon-pay-seller-central-view-production.png
  src/payment/amazon-pay-seller-central.md
Labels: Major update, Progress: approved

#611 Fix typo in page title
  src/tax/hidden-tax-calculation.md
Labels: Editorial, Progress: approved

#609 Update managing-orders.md
  src/sales-channels/asc/managing-orders.md
Labels: Editorial, Progress: approved

#608 Update amazon-sales-channel.md
  src/sales-channels/asc/amazon-sales-channel.md
Labels: Editorial, Progress: approved

#610 Update amazon-onboarding-home.md
  src/sales-channels/asc/amazon-onboarding-home.md
Labels: Editorial, Progress: approved

#613 Update change log for 2.3.x
  src/magento/change-log.md
Labels: Minor update, Progress: approved

#615 Initial build of whatsnew topic
  src/_data/main-nav.yml
  src/_data/toc/getting-started.yml
  src/_data/whats-new.yml
  src/getting-started.md
  src/magento/whats-new.md
  src/whats-new.md
Labels: 2.4.0, Progress: approved

#612 Klarna fix numbering
  src/images/images/config-sales-payment-methods-klarna-on-site-messaging.png
  src/payment/klarna-setup.md
Labels: 2.4.0, Editorial, Progress: approved

#614 Klarna On-Site Messaging Config
  src/configuration/sales/klarna.md
  src/images/images/config-sales-payment-methods-klarna-payments-on-site-messaging.png
Labels: 2.4.0, Minor update, Progress: approved

#616 Markdown linting: MD032
  _checks/styles/style-rules-prod
  src/catalog/catalog-urls.md
  src/catalog/settings-advanced-up-sells.md
  src/configuration/dotdigital/data-mapping.md
  src/getting-started/login-credentials.md
  src/magento/about-this-release.md
  src/sales-channels/amazon/create-alias-seller-sku.md
  src/sales-channels/amazon/creating-editing-overrides.md
  src/sales-channels/amazon/ended-listings.md
  src/sales-channels/amazon/managing-orders.md
  src/sales-channels/amazon/managing-stores.md
  src/sales-channels/amazon/ob-creating-magento-attributes.md
  src/sales-channels/amazon/ob-store-review.md
  src/sales-channels/amazon/store-integration-settings.md
  src/sales-channels/asc/amazon-orders-all.md
Labels: Editorial, Progress: approved, maintenance

#598 Added Store selection option specific to EE
  src/system/permissions-user-roles.md
Labels: Minor update, Progress: changes requested

#619 Markdown linting: MD036
  README.md
  _checks/styles/style-rules-dev
  _checks/styles/style-rules-prod
  src/_includes/inventory-assign-sources-quantities.md
  src/catalog/product-create-configurable.md
  src/catalog/product-create-downloadable.md
  src/catalog/product-create-simple.md
  src/catalog/product-create-virtual.md
  src/catalog/product-price-tier.md
  src/cms/media-storage.md
  src/cms/page-builder-media-map.md
  src/cms/page-builder-tutorial1-simple-page.md
  src/cms/page-builder-tutorial3-catalog-content.md
  src/design/copyright-notice.md
  src/design/layout-update-block-order.md
  src/design/layout-update-examples.md
  src/magento/magento-security-best-practices.md
  src/marketing/url-rewrite-category.md
  src/marketing/url-rewrite-cms-page.md
  src/marketing/url-rewrite-custom.md
  src/marketing/url-rewrite-product.md
  src/marketing/yotpo-reporting.md
  src/reports/review-reports.md
  src/sales-channels/amazon/about-amazon-marketplace.md
  src/sales-channels/amazon/listing-rules.md
  src/sales-channels/asc/about-amazon-marketplace.md
  src/sales-channels/asc/amazon-pre-setup-tasks.md
  src/sales-channels/asc/listing-rules.md
  src/sales/cart-persistent-workflow.md
  src/sales/checkout-instant-purchase.md
  src/sales/gift-wrap.md
  src/system/data-validation.md
Labels: Editorial, Progress: approved, maintenance

#620 Add version switcher
  Gemfile.lock
  _config.yml
  src/_includes/layout/version-switcher.html
Labels: Progress: approved, Site improvements

#569 Update release information for 2.2 doc archive
  src/magento/about-this-release.md
Labels: 2.3.x, Minor update, Progress: approved

#622 VBE Braintree 2.4.0
  src/configuration/sales/braintree.md
  src/images/images/config-sales-payment-methods-braintree-3d-secure-verification-configuration.png
  src/images/images/config-sales-payment-methods-braintree-Paypal-checkout-configuration.png
  src/images/images/config-sales-payment-methods-braintree-Paypal-minicart-and-cart-configuration.png
  src/images/images/config-sales-payment-methods-braintree-Paypal-payment-method-configuration.png
  src/images/images/config-sales-payment-methods-braintree-Paypal-product-page-configuration.png
  src/images/images/config-sales-payment-methods-braintree-ach-payment-method-configuration.png
  src/images/images/config-sales-payment-methods-braintree-advance-configuration.png
  src/images/images/config-sales-payment-methods-braintree-applepay-payment-method-configuration.png
  src/images/images/config-sales-payment-methods-braintree-basic-configuration.png
  src/images/images/config-sales-payment-methods-braintree-country-specific-configuration.png
  src/images/images/config-sales-payment-methods-braintree-dynamic-description-configuration.png
  src/images/images/config-sales-payment-methods-braintree-googlepay-payment-method-configuration.png
  src/images/images/config-sales-payment-methods-braintree-kount-configuration.png
  src/images/images/config-sales-payment-methods-braintree-local-payment-method-configuration.png
  src/images/images/config-sales-payment-methods-braintree-venmo-payment-method-configuration.png
  src/payment/braintree.md
  src/stores/compliance-payment-services-directive.md
Labels: 2.4.0, Major update, Partner: Gene, Progress: review, partners-contribution

#623 VBE Vertex 2.4.0
  src/_data/toc/config-ref.yml
  src/_data/toc/operations.yml
  src/configuration/sales/address-cleansing.md
  src/configuration/sales/address-validation.md
  src/configuration/sales/tax.md
  src/images/images/config-sales-address-validation.png
  src/images/images/config-sales-tax-vertex-company-information.png
  src/images/images/config-sales-tax-vertex-delivery-terms.png
  src/images/images/config-sales-tax-vertex-dev-support.png
  src/images/images/config-sales-tax-vertex-flexible-fields.png
  src/images/images/config-sales-tax-vertex-integration.png
  src/images/images/config-sales-tax-vertex-logging.png
  src/images/images/config-sales-tax-vertex-seller-details.png
  src/images/images/config-sales-tax-vertex-settings-all.png
  src/images/images/config-sales-tax-vertex-settings-valid.png
  src/images/images/config-sales-tax-vertex-settings.png
  src/images/images/config-sales-tax-vertex-shipping-product-codes.png
  src/images/images/config-sales-tax-vertex-tax-classes-adjustment-fees.png
  src/images/images/config-sales-tax-vertex-tax-classes-default-settings.png
  src/images/images/tax-vertex-cloud-magento-config-valid.png
  src/images/images/tax-vertex-magento-config-valid.png
  src/images/images/vertex-error.png
  src/tax/vertex-configure-address.md
  src/tax/vertex-configure-magento.md
  src/tax/vertex.md
Labels: 2.4.0, Major update, Progress: review

#625 Markdown linting: MD038
  _checks/styles/style-rules-dev
  _checks/styles/style-rules-prod
  src/reports/new-relic-reporting.md
Labels: Progress: approved, maintenance

#627 Markdown linting: MD040
  _checks/styles/style-rules-dev
  _checks/styles/style-rules-prod
  src/tax/hidden-tax-calculation.md
Labels: Progress: review, maintenance

#621 Version support
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/NEW_FEATURE.md
  .github/ISSUE_TEMPLATE/NEW_TOPIC.md
  .github/ISSUE_TEMPLATE/TOPIC_CLARIFICATION.md
  .github/PROCESS_GUIDELINES.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Progress: review, maintenance

#626 ASI Documentation: User deletes images in bulk from Media Gallery
  src/cms/media-gallery-asset-management.md
  src/images/images/enhanced-media-gallery/bulk-delete-asset-confirmation.png
  src/images/images/enhanced-media-gallery/delete-asset-confirmation.png
  src/images/images/enhanced-media-gallery/selected-asset.png
Labels: 2.4.1, Major update, Progress: review

#630 About this Release - 2.4.0 updates
  src/magento/about-this-release.md
Labels: 2.4.0, Minor update, Progress: approved

#631 Updating with latest whatsnew
  src/_data/whats-new.yml
Labels: 2.4.0, Minor update, Progress: approved

#632 Add Markdown testing on pull requests to production and develop branches
  .github/workflows/main.yml
Labels: Progress: approved, maintenance

#634 ASI Documentation: Filtering
  src/cms/media-gallery-asset-management.md
  src/images/images/enhanced-media-gallery/filter-duplicates.png
  src/images/images/enhanced-media-gallery/filtered-by-category.png
  src/images/images/enhanced-media-gallery/filters.png
Labels: 2.4.1, Major update, Progress: changes requested

#636 Enable Markdown test workflow for 2.3 branches
  .github/workflows/main.yml
Labels: 2.3.x, Progress: approved, maintenance

#633 Update versioned devdocs links
  .github/CONTRIBUTING.md
  .github/PROCESS_GUIDELINES.md
  src/_includes/backup-deprecated.md
  src/_includes/inventory-async-queues.md
  src/_includes/inventory-cli.md
  src/_includes/new-price-rule.md
  src/_includes/unassign-source.md
  src/catalog/inventory-about-ssa.md
  src/catalog/inventory-configure-distance-priority.md
  src/catalog/inventory-migration.md
  src/catalog/navigation-accessibility.md
  src/cms/blocks.md
  src/cms/page-add.md
  src/configuration/general/advanced-reporting.md
  src/configuration/security/google-recaptcha-admin.md
  src/configuration/security/google-recaptcha-storefront.md
  src/customers/account-create.md
  src/customers/password-reset.md
  src/design/design-menu.md
  src/design/layout-update-place-block.md
  src/design/layout-updates.md
  src/design/theme-install.md
  src/design/themes.md
  src/magento/installation-modes.md
  src/magento/magento-extensions.md
  src/magento/security-scan.md
  src/marketing/google-tag-manager.md
  src/marketing/sitemap-xml.md
  src/reports/advanced-reporting.md
  src/reports/business-intelligence.md
  src/reports/new-relic-reporting.md
  src/stores/b2b-basics.md
  src/stores/security-admin.md
  src/stores/security-browser-capabilities-detection.md
  src/stores/security-google-recaptcha.md
  src/stores/security-session-validation.md
  src/system/cache-full-page.md
  src/system/cache-management.md
  src/system/cron.md
  src/system/developer-client-restrictions.md
  src/system/encryption-key.md
  src/system/file-optimization.md
  src/system/frontend-development-workflow.md
  src/system/index-management.md
  src/system/integrations.md
  src/system/media-storage-content-delivery-network.md
  src/system/static-file-signature.md
  src/system/template-path-hints.md
  src/system/translate-inline.md
Labels: 2.4.0, Minor update, Progress: approved

#635 2.3 GitHub edit page link
  _config.yml
Labels: 2.3.x, Progress: changes requested, bug

#637 Add GraphQL CORS screen
  src/_data/toc/config-ref.yml
  src/configuration/services/graphql.md
  src/images/images/config-services-graphql-cors.png
Labels: 2.4.1, New topic, Progress: approved, internal-dev

#639 Update getting-started.md
  src/getting-started.md
Labels: 2.4.x, Editorial, Partner: PHPro, Progress: approved, small changes

#640 Update login-credentials.md
  src/getting-started/login-credentials.md
Labels: 2.4.x, Editorial, small changes

#641 Update magento-account-share.md
  src/magento/magento-account-share.md
Labels: 2.4.x, Editorial, small changes

#642 Update engage.md
  src/quick-tour/engage.md
Labels: 2.4.x, Editorial, small changes

#643 Update self-service-tools.md
  src/quick-tour/self-service-tools.md
Labels: 2.4.x, Editorial, small changes

#644 Update market-opportunities.md
  src/quick-tour/market-opportunities.md
Labels: 2.4.x, Editorial, Progress: approved, small changes

#646 Small changes
  src/getting-started.md
  src/getting-started/login-credentials.md
  src/magento/magento-account-share.md
  src/quick-tour/engage.md
  src/quick-tour/market-opportunities.md
  src/quick-tour/self-service-tools.md
Labels: 2.4.x, Progress: review, maintenance
