Repository magento/merchdocs, pull requests merged in 2020-04, with the labels that each got.

#434 Update change log for March
  src/magento/change-log.md
Labels: Minor update, Progress: approved

#435 Fix placement of condition under table
  src/configuration/advanced/admin.md
Labels: Progress: approved, bug

#437 Add countries list for Klarna
  src/payment/klarna-setup.md
Labels: Partner: Comwrap, Progress: approved, partners-contribution

#436 Whitelisted variables
  src/images/email-template-insert-varilable.png
  src/images/email-template-message-information.png
  src/images/images-ee/ariable-custom-insert-select.png
  src/images/images-ee/pagebuilder-variable-inserted.png
  src/images/images-ee/variable-custom-insert-select.png
  src/images/images-ee/variable-custom-pagebuilder-stage.png
  src/images/images/editor4-toolbar/btn-insert-variable.png
  src/images/images/email-template-content.png
  src/images/images/email-template-new-pickup-order-predefined-variables.png
  src/images/images/email-template-new-pickup-order-preview.png
  src/images/images/variable-custom-add.png
  src/images/images/variable-custom-insert-content.png
  src/images/images/variable-custom-insert-select.png
  src/marketing/email-template-message.md
  src/marketing/variables-custom.md
  src/marketing/variables-predefined.md
Labels: 2.3.4, Minor update, Progress: approved

#438 Update to Google EOL page
  src/sales-channels/google-ads/google-eol.md
Labels: Minor update, Progress: approved

#439 Change log updates for 2.3.5, deprecate Signifyd
  src/_data/b2b/toc/sales.yml
  src/_data/ce/toc/sales.yml
  src/_data/ee/toc/sales.yml
  src/magento/change-log.md
  src/sales/fraud-protection-signifyd.md
Labels: 2.3.5, Minor update, Progress: approved

#440 Remove `Use SID on Frontend` option
  src/configuration/general/web.md
  src/images/images/config-general-web-session-validation-settings.png
  src/magento/change-log.md
  src/stores/security-session-validation.md
Labels: 2.3.5, Minor update, Progress: approved

#442 Feature/issue429
  src/customers/customer-groups.md
  src/images/images/stores-customer-group-discounts.png
Labels: Event: Global-Contribution-Day, Major update, Partner: Webjump, Progress: changes requested, partners-contribution

#441 update new section list in change log
  src/magento/change-log.md
Labels: Event: Global-Contribution-Day, Minor update, Progress: approved

#445 Contribution Day
  src/customers/customer-groups.md
  src/images/images/stores-customer-group-discounts.png
Labels: Progress: approved, maintenance

#450 Adding Magento services topic
  src/_data/b2b/toc/getting-started.yml
  src/_data/ce/toc/getting-started.yml
  src/_data/ee/toc/getting-started.yml
  src/configuration/services/saas.md
  src/images/images/api-key-saas.png
  src/images/images/config-services.png
  src/images/images/saas-env-saas.png
  src/images/images/stores-customer-group-discounts.png
Labels: 2.3.5, New topic, Progress: approved

#453 GH #11 User Expiration Date
  src/images/images/permissions-role-edit.png
  src/images/images/system-permissions-user-new.png
  src/stores/admin-account.md
  src/system/permissions-user-roles.md
  src/system/permissions-users-all.md
Labels: 2.4, Minor update, Progress: approved

#454 Updates for Change Log and deprecated config reference items
  src/_data/b2b/toc/getting-started.yml
  src/_data/ce/toc/getting-started.yml
  src/_data/ee/toc/getting-started.yml
  src/configuration/sales/authorize-net-direct-post.md
  src/configuration/sales/authorize-net.md
  src/configuration/sales/cybersource.md
  src/configuration/sales/eway.md
  src/configuration/sales/fraud-protection.md
  src/configuration/sales/payment-methods-other.md
  src/configuration/sales/worldpay.md
  src/magento/change-log.md
  src/payment/authorize-net-direct-post.md
  src/payment/authorize-net.md
  src/payment/cybersource.md
  src/payment/eway.md
Labels: 2.3.5, Minor update, Progress: review

#455 Removing EAP banner
  src/_includes/layout/page-header.html
Labels: Minor update, Progress: approved

#458 Adding Magento services topic for pre-release
  src/_data/b2b/toc/getting-started.yml
  src/_data/ce/toc/getting-started.yml
  src/_data/ee/toc/getting-started.yml
  src/configuration/services/saas.md
  src/images/images/api-key-saas.png
  src/images/images/config-services.png
  src/images/images/saas-env-saas.png
  src/images/images/stores-customer-group-discounts.png
Labels: 2.3.5, Progress: approved

#448 Vertex Updates for 2.3.5
  src/configuration/sales/tax.md
  src/images/images/tile-vertex-calculations-returns.png
  src/images/images/tile-vertex-consumer-use-tax.png
  src/images/images/tile-vertex-exemption-certificates.png
  src/images/images/tile-vertex-prepare-returns.png
  src/magento/change-log.md
  src/tax/vertex-configure-address.md
  src/tax/vertex-configure-magento.md
  src/tax/vertex.md
Labels: 2.3.5, Minor update, Progress: approved

#452 Format updates in tax topics folder
  src/tax/display-settings.md
  src/tax/eu-place-of-supply.md
  src/tax/fixed-product-tax-configuration.md
  src/tax/fixed-product-tax.md
  src/tax/guidelines-canada.md
  src/tax/guidelines-eu.md
  src/tax/international-tax-guidelines.md
  src/tax/quick-reference.md
  src/tax/tax-class-configure.md
  src/tax/tax-class-new.md
  src/tax/tax-cross-border-price.md
  src/tax/tax-destination-default.md
  src/tax/tax-rules.md
  src/tax/tax-settings-general.md
  src/tax/tax-zones-rates.md
  src/tax/vat-configure.md
  src/tax/vat-validation-configure.md
  src/tax/vat-validation.md
  src/tax/vat.md
  src/tax/vertex-account.md
  src/tax/vertex-configure-address.md
  src/tax/vertex-configure-magento.md
  src/tax/vertex-configure.md
  src/tax/vertex-field-mapping.md
  src/tax/vertex-setup-customer-exceptions.md
  src/tax/vertex-setup-products.md
  src/tax/vertex-setup.md
  src/tax/vertex.md
  src/tax/warning-messages.md
Labels: Editorial, Progress: review

#460 Add Temando messaging to all Magento Shipping pages
  src/_includes/shipping-status-note.md
  src/shipping/magento-shipping-attributes.md
  src/shipping/magento-shipping-batch-create.md
  src/shipping/magento-shipping-carriers.md
  src/shipping/magento-shipping-click-collect.md
  src/shipping/magento-shipping-collection-points.md
  src/shipping/magento-shipping-countries.md
  src/shipping/magento-shipping-customer-experience.md
  src/shipping/magento-shipping-experience-rules.md
  src/shipping/magento-shipping-experience.md
  src/shipping/magento-shipping-international.md
  src/shipping/magento-shipping-locations.md
  src/shipping/magento-shipping-packaging.md
  src/shipping/magento-shipping-pre-packaged.md
  src/shipping/magento-shipping-preview-experience.md
  src/shipping/magento-shipping-quick-look.md
  src/shipping/magento-shipping-setup.md
  src/shipping/magento-shipping-shipment-workflow.md
  src/shipping/magento-shipping-troubleshooting.md
  src/shipping/magento-shipping.md
Labels: Minor update, Progress: review

#461 klarna-2.3.5-updates
  src/_includes/layout/page-header.html
  src/configuration/sales/klarna.md
  src/images/images/config-sales-payment-methods-klarna-api.png
  src/images/images/config-sales-payment-methods-klarna-payments-design.png
  src/images/images/config-sales-payment-methods-klarna-payments.png
  src/magento/change-log.md
  src/payment/klarna-setup.md
  src/payment/klarna.md
Labels: 2.3.5, Minor update, Progress: review

#463 Markdown linting: MD012
  _checks/styles/style-rules-dev
  _checks/styles/style-rules-prod
  src/cms/page-builder-elements-divider.md
  src/configuration/customers/customer-configuration.md
  src/configuration/sales/paypal-payflow-link.md
  src/payment/worldpay.md
  src/sales-channels/amazon/amazon-order-details.md
  src/sales-channels/amazon/listing-price.md
  src/sales-channels/amazon/managing-listings-by-tab.md
  src/sales-channels/amazon/pricing-rule-general-settings.md
  src/sales-channels/google-ads/gmc-unlink-gmc.md
  src/sales-channels/google-ads/onboarding-google.md
Labels: Progress: approved, Site improvements

#467 Markdown linting: MD018 and MD019
  _checks/styles/style-rules-dev
  _checks/styles/style-rules-prod
  src/cms/dynamic-blocks.md
Labels: Progress: approved, Site improvements

#456 Updates to remove references to maintainers
  .github/PROCESS_GUIDELINES.md
Labels: Progress: review, maintenance

#451 Inventory: Add support for bundle products 2
  src/catalog/inventory-about-product-types.md
  src/catalog/product-create-bundle.md
Labels: 2.4, Major update, Progress: changes requested, internal-dev

#469 Updates from PMM
  src/getting-started/introduction.md
Labels: Editorial, Progress: approved

#470 Clarifying How to Generate API Key
  src/configuration/services/saas.md
  src/images/images/get-api-key.png
Labels: 2.3.5, Editorial, Progress: approved

#474 Markdown linting: MD023
  _checks/styles/style-rules-dev
  _checks/styles/style-rules-prod
  src/payment/paypal-credit.md
Labels: Editorial, Progress: approved, Site improvements

#475 Bundle 2503 dotdigital
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/marketing.yml
  src/configuration/engagement-cloud/data-mapping.md
  src/configuration/engagement-cloud/developer.md
  src/configuration/engagement-cloud/sync-settings.md
  src/images/images-b2b/config-dotdigital-sync-settings-sync.png
  src/images/images-b2b/config-engagement-cloud-sync-settings-sync.png
  src/images/images-b2b/config-engagement-data-fields-mapping-b2b-data.png
  src/images/images/config-dotdigital-developer-sync-settings-manually-run-sync.png
  src/images/images/price-rule-cart-coupon-url-builder.png
  src/images/images/price-rule-cart-manage-coupon-codes-grid.png
  src/magento/change-log.md
  src/marketing/engagement-cloud-data-mapping.md
  src/marketing/engagement-cloud.md
  src/marketing/price-rules-cart-coupon.md
Labels: 2.3.5, Major update, Progress: approved

#473 Amazon Pay release updates and formatting
  src/magento/change-log.md
  src/payment/amazon-pay-customer-experience.md
  src/payment/amazon-pay-manage.md
  src/payment/amazon-pay-resources.md
  src/payment/amazon-pay-seller-central.md
  src/payment/amazon-pay-setup.md
  src/payment/amazon-pay.md
Labels: 2.3.5, Minor update, Progress: approved

#471 Rake improvements
  Rakefile
  rakelib/check.rake
  rakelib/test.rake
Labels: Progress: changes requested, maintenance

#478 Updates to Yotpo for 2.3.5
  src/configuration/yotpo/reviews-visual-marketing.md
  src/images/images/yotpo-config-setup-default.png
  src/images/images/yotpo-config-setup.png
  src/images/images/yotpo-config-widget.png
  src/marketing/yotpo-reviews-intro.md
  src/marketing/yotpo-settings.md
Labels: 2.3.5, Minor update, Progress: approved

#477 Added ASC Renewed Product Info
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/marketing.yml
  src/magento/change-log.md
  src/sales-channels/asc/product-listing-condition.md
  src/sales-channels/asc/renewed-products.md
Labels: Minor update, New topic, Progress: approved, asc-non-release

#481 PB-518: Update to Background Video section for Row.
  src/cms/page-builder-layout-row.md
Labels: 2.3.5, Minor update, Progress: approved

#483 Markdown linting: MD025 and MD029
  .github/ISSUE_TEMPLATE/BUG.md
  README.md
  _checks/styles/style-rules-dev
  _checks/styles/style-rules-prod
  src/_includes/amazon-listing-rules-configure.md
  src/cms/banner-rotator.md
  src/configuration/scope-change.md
  src/customers/account-dashboard-order-by-sku.md
  src/design/favicon.md
  src/payment/braintree.md
  src/payment/eway.md
  src/payment/paypal-settlement-reports.md
  src/payment/worldpay.md
  src/sales/orders-search.md
  src/shipping/carriers.md
  src/shipping/magento-shipping-attributes.md
  src/shipping/magento-shipping-shipment-workflow.md
  src/shipping/usps.md
Labels: Editorial, Progress: approved, Site improvements

#476 Fixed typos/markup on Configuration > Services/Advanced
  src/configuration/advanced/admin.md
  src/configuration/advanced/developer.md
  src/configuration/advanced/system.md
  src/configuration/services/oauth.md
  src/configuration/services/saas.md
Labels: Editorial, Progress: approved
