Repository magento/merchdocs, pull requests merged in 2020-05, with the labels that each got.

#486 Update PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Progress: approved, maintenance

#490 Adobe Stock Integration configuration instructions update
  src/cms/adobe-stock.md
Labels: Minor update, Progress: approved, Technical

#488 Klarna API Configuration Merchant ID
  src/configuration/sales/klarna.md
  src/images/images/config-sales-payment-methods-recommended-solutions-klarna.png
  src/magento/change-log.md
  src/payment/klarna-setup.md
Labels: Minor update, Progress: approved

#493 Spectrum redesign
  Gemfile.lock
  src/_includes/layout/nav-item.html
  src/_includes/layout/navigation.html
  src/_includes/layout/page-header.html
  src/_includes/layout/page-info.html
  src/_includes/layout/sidebar.html
  src/_includes/layout/version-switcher.html
  src/css/merchdocs.css
Labels: Progress: approved, Site improvements

#496 Bump the theme to fix mobile issue on some devices
  Gemfile.lock
Labels: Progress: approved

#497 Fix the github link to point to the right source page
  _config.yml
  _plugins/github-path.rb
Labels: Progress: approved

#495 Add Contributor page
  src/_data/b2b/toc/getting-started.yml
  src/_data/ce/toc/getting-started.yml
  src/_data/ee/toc/getting-started.yml
  src/_data/home-sections.yml
  src/getting-started/assets/commit-changes.png
  src/getting-started/assets/edit-github.png
  src/getting-started/assets/feedback-icon.png
  src/getting-started/assets/log-issue.png
  src/getting-started/assets/pencil-icon.png
  src/getting-started/assets/submit-new-issue.png
  src/getting-started/contribute.md
Labels: New topic, Progress: review

#491 Add basic template to repo
  .github/TOPIC_TEMPLATE
Labels: Progress: review, Site improvements

#487 Amazon Sales Channel 4.1.0
  src/_data/b2b/toc/marketing.yml
  src/_data/ce/toc/marketing.yml
  src/_data/ee/toc/marketing.yml
  src/_includes/amazon-managing-listings-intro.md
  src/magento/change-log.md
  src/sales-channels/asc/amazon-order-details.md
  src/sales-channels/asc/amazon-orders-all.md
  src/sales-channels/asc/amazon-store-dashboard.md
  src/sales-channels/asc/assets/amazon-orders-filter-view.png
  src/sales-channels/asc/assets/amazon-orders-list-all.png
  src/sales-channels/asc/assets/amazon-recent-orders-imported.png
  src/sales-channels/asc/assets/amazon-store-dashboard.png
  src/sales-channels/asc/cancel-unshipped-order.md
  src/sales-channels/asc/fulfilled-by.md
  src/sales-channels/asc/managing-listings-by-action.md
  src/sales-channels/asc/managing-listings-by-tab.md
  src/sales-channels/asc/managing-orders.md
  src/sales-channels/asc/managing-product-listings.md
  src/sales-channels/asc/ob-create-listing-rule.md
  src/sales-channels/asc/order-settings.md
  src/sales-channels/asc/product-listing-condition.md
Labels: Major update, New topic, Progress: approved, asc-4.1.0

#503 Change tense of Google End of Life topic
  src/_includes/layout/page-header.html
  src/sales-channels/google-ads/google-eol.md
Labels: Editorial, Minor update, Progress: approved

#501 Remember category pagination
  src/catalog/navigation-product-listings.md
  src/configuration/catalog.md
  src/configuration/catalog/catalog.md
  src/images/images-ee/config-catalog.png
  src/images/images/config-catalog-catalog-storefront.png
  src/magento/change-log.md
Labels: Minor update, Progress: approved

#502 Delete unused images
  src/images/images/x-config-sales-shipping-methods-magento-shipping.png
  src/images/images/x-engagement-cloud-automation-studio.png
  src/images/images/xx-config-sales-shipping-methods-magento-shipping.png
  src/price-rule-catalog-multiple-skus-condition2.png
Labels: Progress: approved, maintenance

#504 Added information on newly added field as on 2.3.5 Commerce
  src/configuration/catalog/inventory.md
Labels: 2.3.5, Minor update, Progress: approved

#494 OM-739: Add OMS Connector to System Reports topic
  src/system/support-system-report.md
Labels: Minor update, OMS, Progress: approved

#509 RMA Lifecycle docs created
  src/_data/b2b/toc/sales.yml
  src/_data/ee/toc/sales.yml
  src/sales/rma-lifecycle.md
Labels: New topic, Partner: Ziffity, Progress: approved, partners-contribution

#510 Fixed Google Adwords Typo
  src/marketing/google-adwords.md
Labels: Editorial, Progress: approved

#508 Integrating Product Recs into Page Builder
  src/_data/b2b/toc/content.yml
  src/_data/ee/toc/content.yml
  src/_data/ee/toc/marketing.yml
  src/cms/page-builder-add-content.md
  src/images/images-ee/page-builder-add-prex-drag.png
  src/images/images-ee/page-builder-add-prex-name.png
  src/images/images-ee/page-builder-add-prex-select.png
  src/images/images-ee/page-builder-add-prex-selected.png
  src/images/images-ee/page-builder-add-prex-toolbox.png
  src/marketing/create-new-rec.md
  src/marketing/page-builder-add-product-recs.md
Labels: 2.3.4, New topic, Progress: changes requested

#516 Bump theme to update app switcher link
  Gemfile.lock
Labels: Progress: approved

#518 Update adobe stock integration configuration instructions
  src/cms/adobe-stock.md
Labels: Minor update, Progress: review

#520 Web setup wizard deprecation
  src/_includes/web-setup-deprecate.md
  src/magento/magento-marketplace-synchronize-store.md
  src/system/web-setup-extension-manager.md
  src/system/web-setup-module-manager.md
  src/system/web-setup-system-configuration.md
  src/system/web-setup-system-upgrade.md
  src/system/web-setup-wizard.md
Labels: Minor update, Progress: approved

#519 Dashboard
  src/images/images-ee/page-builder-add-prex-drag.png
  src/images/images-ee/page-builder-add-prex-toolbox.png
  src/images/images/dashboard-advanced-reporting.png
  src/images/images/dashboard-full.png
  src/stores/admin-dashboard.md
Labels: 2.4, Progress: approved

#521 Update currency service information
  src/configuration/general/currency-setup.md
  src/images/images-ee/config-general-currency-setup-scheduled-import-settings.png
  src/images/images/config-general-currency-setup-converter.png
  src/images/images/config-general-currency-setup-fixerio.png
  src/images/images/config-general-currency-setup-scheduled-import-settings.png
  src/images/images/config-general-currency-setup-webservicex.png
  src/images/images/config-general-currency-setup-yahoo-finance-exchange.png
  src/images/images/stores-currency-rate-update.png
  src/stores/currency-configuration.md
  src/stores/currency-update.md
Labels: Major update, Progress: review

#523 Adding compatibility information between recommendations, Magento, and Page Builder
  src/marketing/create-new-rec.md
  src/marketing/page-builder-add-product-recs.md
Labels: 2.3.5, Minor update, Progress: review
