Repository magento/merchdocs, pull requests merged in 2020-12, with the labels that each got.

#885 Issue-5- Changed the set product as new section
  src/cms/widget-new-products-list.md
  src/images/images/product-set-as-new.png
Labels: Partner: EY, Progress: review, partners-contribution

#881 Deleted labels which sing functionality available as EE and B2B
  src/customers/account-dashboard-account-information.md
  src/customers/account-dashboard-address-book.md
  src/customers/account-dashboard-gift-cards.md
  src/customers/account-dashboard-my-downloadable-products.md
  src/customers/account-dashboard-my-invitations.md
  src/customers/account-dashboard-my-orders.md
  src/customers/account-dashboard-my-product-reviews.md
  src/customers/account-dashboard-my-wish-list.md
  src/customers/account-dashboard-newsletter-subscriptions.md
  src/customers/account-dashboard-store-credit.md
Labels: 2.4.x, Community, Minor update, Partner: Atwix, Port change, Progress: approved, partners-contribution

#883 added more detail to the quantity to be deducted field
  src/catalog/inventory-shipment-create.md
Labels: 2.4.x, Community, Minor update, Partner: EY, Port change, Progress: approved, partners-contribution

#880 Update screenshot from Magento 1
  src/images/images/storefront-cart-table-rate.png
Labels: 2.4.x, Community, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#886 added updated information
  src/system/data-export.md
Labels: 2.4.x, Community, Minor update, Partner: EY, Progress: approved, partners-contribution

#856 Extend Import/Export documentation with Remote Storage
  src/images/images-ee/data-transfer-scheduled-export-file-information.png
  src/images/images-ee/data-transfer-scheduled-import-file-informaition.png
  src/images/images-ee/data-transfer-scheduled-import-file-information.png
  src/images/images/data-import-downloadable-links.png
  src/images/images/data-import-downloadable-samples.png
  src/images/images/data-import-file-to-import.png
  src/system/data-export.md
  src/system/data-import-history.md
  src/system/data-import-product-images.md
  src/system/data-import.md
  src/system/data-schedule-export.md
  src/system/data-schedule-import.md
  src/system/data-transfer-downloadable-products.md
  src/system/data-transfer-examples.md
Labels: Progress: approved

#860 Update braintree.md
  src/payment/braintree.md
Labels: 2.3.x, Minor update, Progress: approved, Stakeholder

#887 Adding missing image in In-store Delivery doc
  src/images/images/config-sales-shipping-methods-in-store.png
  src/shipping/shipping-in-store-delivery.md
Labels: 2.4.x, Community, Minor update, Progress: approved

#893 Adding missing info in Stores Menu doc
  src/images/images/admin-menu-stores-ee.png
  src/stores/stores-menu.md
Labels: 2.4.x, Community, Major update, Port change, Progress: approved

#874 Requisition list improvements
  src/_data/toc/getting-started.yml
  src/configuration/customers/requisition-lists.md
  src/customers/account-dashboard-requisition-lists.md
  src/images/images-b2b/config-general-b2b-features.png
  src/stores/b2b-configure-requisition-lists.md
  src/stores/b2b-features.md
Labels: 2.4.x, New topic, Progress: review

#894 Add short description
  src/configuration/customers/persistent-shopping-cart.md
Labels: 2.4.x, Community, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#897 2.3 deprecate Braintree
  src/payment/braintree.md
Labels: 2.3.x, Progress: approved

#859 Adding Content for Inclusion and Exclusion Rules
  src/_data/toc/marketing.yml
  src/marketing/create-new-rec.md
  src/marketing/edit-existing-rec.md
  src/marketing/product-recommendations.md
  src/marketing/recommendation-incl-excl.md
Labels: 2.4.x, New topic, Progress: approved, Stakeholder

#772 Documenting Catalog Sync Feature
  src/_data/toc/operations.yml
  src/system/catalog-sync.md
  src/system/data-transfer.md
Labels: 2.4.x, New topic, Progress: approved, Stakeholder

#895 Adding new pages inside Stores Menu doc
  src/_data/toc/operations.yml
  src/stores/inventory-add-new-source.md
  src/stores/inventory-add-new-stock.md
  src/stores/inventory-deleting-stocks.md
  src/stores/inventory-disabling-sources.md
  src/stores/inventory-manage-sources.md
  src/stores/inventory-manage-stocks.md
  src/stores/inventory-prioritizing-sources-for-a-stock.md
  src/stores/inventory.md
  src/stores/stores.md
Labels: Progress: ready for review

#901 Adding visual similarity rec type and content reorg
  _plugins/page_to_api.rb
  src/_data/toc/marketing.yml
  src/images/images-ee/trending-homepage.png
  src/images/images-ee/visual-sim-pdp.png
  src/images/images-ee/visual-sim-unit.png
  src/marketing/create-new-rec.md
  src/marketing/prex-type-boughtbought.md
  src/marketing/prex-type-morelikethis.md
  src/marketing/prex-type-mostaddcart.md
  src/marketing/prex-type-mostpurchase.md
  src/marketing/prex-type-mostviewed.md
  src/marketing/prex-type-rcmdforyou.md
  src/marketing/prex-type-trending.md
  src/marketing/prex-type-viewbought.md
  src/marketing/prex-type-viewview.md
  src/marketing/prex-type-visualsim.md
  src/marketing/prex-types.md
  src/marketing/product-recommendations.md
Labels: 2.4.x, Major update, New topic, Progress: approved, Stakeholder

#890 PAY-226: Magento Payments info architecture
  _config.yml
  src/_data/main-nav.yml
  src/_data/toc/sales.yml
  src/magento-payments/configure-payments.md
  src/magento-payments/financial-reporting.md
  src/magento-payments/fraud-protection.md
  src/magento-payments/installing-payments.md
  src/magento-payments/managing-payments.md
  src/magento-payments/onboarding-payments.md
  src/magento-payments/payments-options.md
  src/magento-payments/payments.md
  src/magento-payments/pci.md
  src/magento-payments/refunds.md
  src/magento-payments/security.md
  src/magento-payments/testing-validating.md
  src/magento-payments/voids.md
Labels: Progress: approved, Site improvements

#878 Adding info in Basic Payment Methods doc
  src/payment/payment-methods.md
Labels: 2.4.x, Community, Minor update, Progress: approved

#900 Import/Export updates for Remote storage
  src/images/images-ee/data-transfer-scheduled-export-file-information.png
  src/images/images-ee/data-transfer-scheduled-import-file-informaition.png
  src/images/images-ee/data-transfer-scheduled-import-file-information.png
  src/images/images/data-import-downloadable-links.png
  src/images/images/data-import-downloadable-samples.png
  src/images/images/data-import-file-to-import.png
  src/system/data-export.md
  src/system/data-import-history.md
  src/system/data-import-product-images.md
  src/system/data-import.md
  src/system/data-schedule-export.md
  src/system/data-schedule-import.md
  src/system/data-transfer-downloadable-products.md
  src/system/data-transfer-examples.md
Labels: 2.4.2, New topic, Progress: approved, internal-dev

#908 Cleaning MDL errors
  src/images/images-ee/rec-conditions.png
  src/marketing/create-new-rec.md
  src/marketing/prex-type-boughtbought.md
  src/marketing/prex-type-morelikethis.md
  src/marketing/prex-type-mostaddcart.md
  src/marketing/prex-type-mostpurchase.md
  src/marketing/prex-type-mostviewed.md
  src/marketing/prex-type-rcmdforyou.md
  src/marketing/prex-type-trending.md
  src/marketing/prex-type-viewbought.md
  src/marketing/prex-type-viewview.md
  src/marketing/prex-type-visualsim.md
  src/marketing/prex-types.md
  src/marketing/recommendation-incl-excl.md
Labels: 2.4.x, Editorial, Progress: approved, Stakeholder

#892 Adding missing info in Tax Rules doc
  src/tax/tax-rules.md
Labels: 2.4.x, Community, Minor update, Progress: ready for review

#909 Fixing links to old catalog filtering content
  src/marketing/prex-type-mostaddcart.md
  src/marketing/prex-type-mostpurchase.md
  src/marketing/prex-type-mostviewed.md
  src/marketing/product-recommendations.md
  src/marketing/recommendation-incl-excl.md
  src/system/catalog-sync.md
Labels: 2.4.x, Editorial, Progress: approved, Stakeholder

#911 PAY-744: Order payment status reports
  src/_data/toc/sales.yml
  src/magento-payments/order-payment-status.md
Labels: Progress: review

#903 Issue-464-added a disclaimer for the requested information to be added
  src/magento/magento-account-share.md
Labels: 2.4.x, Community, Minor update, Partner: EY, Progress: approved, partners-contribution

#913 Replacing screenshot and decoupling stock status
  src/images/images-ee/rec-conditions.png
  src/marketing/recommendation-incl-excl.md
Labels: 2.4.x, Editorial, Progress: approved, Stakeholder

#914 Prex dec integration into master
  src/_data/toc/marketing.yml
  src/_data/toc/operations.yml
  src/images/images-ee/rec-conditions.png
  src/images/images-ee/trending-homepage.png
  src/images/images-ee/visual-sim-pdp.png
  src/images/images-ee/visual-sim-unit.png
  src/marketing/create-new-rec.md
  src/marketing/edit-existing-rec.md
  src/marketing/prex-type-boughtbought.md
  src/marketing/prex-type-morelikethis.md
  src/marketing/prex-type-mostaddcart.md
  src/marketing/prex-type-mostpurchase.md
  src/marketing/prex-type-mostviewed.md
  src/marketing/prex-type-rcmdforyou.md
  src/marketing/prex-type-trending.md
  src/marketing/prex-type-viewbought.md
  src/marketing/prex-type-viewview.md
  src/marketing/prex-type-visualsim.md
  src/marketing/prex-types.md
  src/marketing/product-recommendations.md
  src/marketing/recommendation-incl-excl.md
  src/system/catalog-sync.md
  src/system/data-transfer.md
Labels: 2.4.x, Progress: approved, Stakeholder

#915 Update yotpo-reviews-intro.md
  src/marketing/yotpo-reviews-intro.md
Labels: 2.4.2, Minor update, Progress: approved, VBE

#904 Adding missing info in the Tax Settings doc
  src/images/images/config-sales-tax-orders-invoices-credit-memos-display-settings.png
  src/images/images/config-sales-tax-shopping-cart-display-settings.png
  src/tax/tax-settings-general.md
Labels: 2.4.2, Community, Major update, Progress: approved

#919 Enable MD linter in SuperLinter
  .github/workflows/linter.yml
Labels: Progress: approved, maintenance

#927 Update release version
  src/marketing/recommendation-incl-excl.md
Labels: 2.4.x, Editorial, Progress: approved, Stakeholder

#905 Adding info in Custom Order Status doc
  src/sales/order-status-custom.md
Labels: 2.4.x, Minor update, Progress: approved

#928 Adding prex entries to whatsnew
  src/_data/whats-new.yml
Labels: 2.4.x, Minor update, Progress: approved, Stakeholder

#930 Removed EE only
  src/customers/account-dashboard.md
Labels: 2.3.x, 2.4.x, Minor update, Progress: approved

#912 Adding info in Configuring VAT doc
  src/images/images/configuring-vat-add-new-tax-class.png
  src/images/images/configuring-vat-apply-tax-classes-to-products.png
  src/images/images/configuring-vat-set-up-tax-rules.png
  src/images/images/configuring-vat-set-up-tax-zones-and-rates.png
  src/images/images/configuring-vat-tax-zones-and-rates.png
  src/tax/tax-settings-general.md
  src/tax/vat-configure.md
Labels: 2.4.x, Community, Minor update, Progress: approved

#931 Adding link to catalog sync CLI
  src/system/catalog-sync.md
Labels: 2.4.x, Editorial, Progress: approved, Stakeholder

#916 Adding info in Customer Reports doc
  src/images/images/reports-customers-segments.png
  src/images/images/reports-customers-wish-list.png
  src/reports/customer-reports.md
Labels: Progress: approved

#942 Fixes existing linting errors seen in GitHub actions
  src/marketing/price-rules-cart-create.md
  src/system/data-import-product-images.md
Labels: 2.4.2, Progress: approved, internal-dev, maintenance

#943 Fix nav and topic for downloadable products
  src/_data/toc/operations.yml
  src/system/data-transfer-downloadable-products.md
Labels: 2.4.2, Editorial, Progress: approved

#906 Adding missing info in Order Status doc
  src/sales/order-status.md
Labels: Progress: approved

#937 PB-429: User can add content to the Stage directly
  src/cms/page-builder-add-content-products.md
  src/cms/page-builder-layout-column.md
  src/cms/page-builder-layout-row.md
  src/cms/page-builder-layout-tabs.md
  src/cms/page-builder-layout.md
  src/cms/page-builder-workspace.md
Labels: 2.4.2, Major update, Progress: approved, internal-dev

#938 PB-636: Responsive breakpoint switcher
  src/cms/page-builder-workspace.md
  src/images/images-ee/page-builder-workspace-viewport-buttons.png
  src/images/images-ee/page-builder-workspace-viewport-desktop.png
  src/images/images-ee/page-builder-workspace-viewport-field-breakpoint.png
  src/images/images-ee/page-builder-workspace-viewport-mobile.png
Labels: 2.4.2, Major update, Progress: approved, internal-dev

#907 Adding info in Price Display Settings doc
  src/tax/display-settings.md
Labels: Progress: approved

#945 Clarified Customer tax classes for VAT ID validation failure
  src/tax/vat-validation-configure.md
Labels: 2.4.x, Minor update, Port change, Progress: approved

#950 Whats New updates for UG
  src/_data/whats-new.yml
Labels: Progress: approved

#917 Adding info in Product Reports doc
  src/reports/product-reports.md
Labels: 2.4.x, Community, Minor update, Progress: approved

#918 Adding info in Private Sales Reports doc
  src/reports/private-sales-reports.md
Labels: 2.4.x, Community, Minor update, Progress: approved

#921 819 tax warning message page update
  src/tax/warning-messages.md
Labels: 2.4.x, Community, Minor update, Partner: EY, Port change, Progress: approved, partners-contribution

#929 Typo error - Updated coverts => converts
  src/configuration/general/web.md
Labels: 2.4.x, Community, Editorial, Port change, Progress: approved

#946 Extend import product images section with image resize info
  src/system/data-import-product-images.md
Labels: 2.4.2, Minor update, Progress: approved

#952 Updating whatsnew rake task and template
  Rakefile
  src/_data/whats-new.yml
  src/whats-new.md
Labels: Progress: approved, maintenance

#922 898 small change klarna setup
  src/payment/klarna-setup.md
Labels: 2.4.x, Community, Minor update, Partner: EY, Port change, Progress: approved, partners-contribution

#896 dotdigital section updates for 2.4.2 release
  src/_data/toc/config-ref.yml
  src/configuration/dotdigital.md
  src/configuration/dotdigital/abandoned-carts.md
  src/configuration/dotdigital/chat-settings.md
  src/configuration/dotdigital/configuration.md
  src/configuration/dotdigital/developer.md
  src/configuration/dotdigital/email-templates.md
  src/configuration/dotdigital/transactional-emails.md
  src/configuration/dotdigital/transactional-sms.md
  src/images/images/config-engagement-cloud-accounts-settings-yes.png
  src/images/images/config-engagement-cloud-configuration-image-types.png
  src/images/images/config-engagement-cloud-configuration-tracking.png
  src/images/images/config-engagement-cloud-sms-templates.png
  src/images/images/config-engagement-cloud-transactional-emails.png
  src/images/images/config-engagement-cloud-transactional-sms.png
  src/images/images/dotdigital-dash-systemalerts.png
Labels: 2.4.2, Major update, Progress: approved, Technology Partner: dotdigital, VBE, tech-partners-contribution

#925 Adding info in Catalog doc
  src/configuration/catalog/catalog.md
  src/images/images/config-catalog-catalog-product-reviews.png
  src/images/images/config-catalog-catalog-product-video.png
Labels: 2.4.x, Community, Minor update, Progress: approved

#926 Removing excess tab from Security doc
  src/_data/toc/config-ref.yml
Labels: 2.4.x, Community, Editorial, Progress: approved

#954 Update linting
  .github/workflows/linter.yml
  .github/workflows/main.yml
Labels: Progress: approved, maintenance

#934 Add short description for wishlist
  src/configuration/customers/wishlist.md
Labels: Partner: Atwix, Progress: approved, Progress: review, partners-contribution

#935 Issue-70- Added additional information on deferred stock update field
  src/configuration/catalog/inventory.md
Labels: 2.4.x, Community, Minor update, Partner: EY, Port change, Progress: approved, partners-contribution

#939 Add short description for newsletter
  src/configuration/customers/newsletter.md
Labels: 2.4.x, Community, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#940 Update catalog-shared.md
  src/catalog/catalog-shared.md
Labels: Partner: EY, Progress: approved, partners-contribution

#949 Adding info in OAuth doc
  src/configuration/services/oauth.md
  src/images/images/config-services-oauth-authentication-locks.png
Labels: 2.4.x, Community, Major update, Progress: approved

#948 Updated manage subscriber page in 2.4.x
  src/marketing/newsletter-subscribers.md
Labels: 2.3.x, Community, Minor update, Partner: EY, Progress: approved, partners-contribution

#944 Clarify cancel order process
  src/sales/order-processing.md
  src/sales/orders-workspace.md
  src/sales/orders.md
Labels: 2.4.x, Minor update, Port change, Progress: approved

#956 Unignore .whatsup.yml
  .gitignore
  .whatsup.yml
Labels: Progress: approved, maintenance
