Repository magento/merchdocs, pull requests merged in 2020-06, with the labels that each got.

#525 Update ruby version and gem dependencies
  .ruby-version
  Gemfile.lock
Labels: Progress: approved, maintenance

#526 Adding topic about switching SaaS environments
  src/_data/toc/marketing.yml
  src/marketing/page-builder-add-product-recs.md
  src/marketing/recommendation-change-source.md
Labels: 2.3.5, New topic, Progress: approved

#529 Revert ruby to 2.6.5
  .ruby-version
Labels: Progress: approved, maintenance

#530 Update change log for May
  src/magento/change-log.md
Labels: Minor update, Progress: approved

#527 dotdigital updates for 2.4
  src/configuration/dotdigital/data-mapping.md
  src/configuration/dotdigital/sync-settings.md
  src/images/images-b2b/config-engagement-data-fields-mapping-b2b-data.png
  src/images/images/config-engagement-cloud-data-mapping-data-fields-mapping-system-values.png
  src/images/images/config-engagement-cloud-transactional-emails.png
Labels: 2.4, Technology Partner: dotdigital, tech-partners-contribution

#517 Provide edit and improvements to contribute.md
  src/getting-started/contribute.md
Labels: Editorial, Progress: approved

#528 Remove deprecated payment method topics
  src/_data/toc/config-ref.yml
  src/_data/toc/sales.yml
  src/configuration/sales/3d-secure.md
  src/configuration/sales/authorize-net-direct-post.md
  src/configuration/sales/authorize-net.md
  src/configuration/sales/cardinalcommerce.md
  src/configuration/sales/cybersource.md
  src/configuration/sales/eway.md
  src/configuration/sales/payment-methods-other.md
  src/configuration/sales/worldpay.md
  src/images/images-ee/config-sales-payment-methods-cybersource.png
  src/images/images-ee/config-sales-payment-methods-cybersource1.png
  src/images/images-ee/config-sales-payment-methods-cybersource2.png
  src/images/images-ee/config-sales-payment-methods-cybersource3.png
  src/images/images-ee/config-sales-payment-methods-cybersource4.png
  src/images/images-ee/config-sales-payment-methods-eway.png
  src/images/images-ee/config-sales-payment-methods-eway1-enabled.png
  src/images/images-ee/config-sales-payment-methods-eway1.png
  src/images/images-ee/config-sales-payment-methods-eway2.png
  src/images/images-ee/config-sales-payment-methods-eway3.png
  src/images/images-ee/config-sales-payment-methods-eway4.png
  src/images/images-ee/config-sales-payment-methods-worldpay-sort-order.png
  src/images/images-ee/config-sales-payment-methods-worldpay.png
  src/images/images-ee/config-sales-payment-methods-worldpay1.png
  src/images/images-ee/config-sales-payment-methods-worldpay2.png
  src/images/images-ee/config-sales-payment-methods-worldpay3.png
  src/images/images-ee/config-sales-payment-methods-worldpay4.png
  src/images/images-ee/config-sales-payment-methods-worldpay5.png
  src/images/images-ee/config-sales-payment-methods-worldpay6.png
  src/images/images-ee/config-sales-payment-methods-worldpay7.png
  src/images/images/config-sales-3dsecure-cardinalcommerce.png
  src/images/images/config-sales-payment-methods-authorize-net-advanced-settings.png
  src/images/images/config-sales-payment-methods-authorize-net-basic-settings-enabled.png
  src/images/images/config-sales-payment-methods-authorize-net-basic-settings.png
  src/images/images/config-sales-payment-methods-authorize-net-basic-settings.png 
  src/images/images/config-sales-payment-methods-authorize-net-direct-post.png
  src/images/images/payments-authorize-net-direct-post1.png
  src/images/images/payments-authorize-net-direct-post2.png
  src/images/images/payments-authorize-net-direct-post3.png
  src/images/images/payments-authorize-net-direct-post4.png
  src/images/images/payments-authorize-net-direct-post5.png
  src/payment/authorize-net-direct-post.md
  src/payment/authorize-net.md
  src/payment/cybersource.md
  src/payment/eway.md
  src/payment/gateways.md
  src/payment/payments.md
  src/payment/worldpay.md
  src/stores/compliance-payment-services-directive.md
Labels: 2.4, Major update, Progress: review

#532 2FA User Guide Updates
  src/configuration/security/2fa.md
  src/images/images/admin-login-2fa-google.png
  src/images/images/admin-login-google-auth-setup.png
  src/images/images/admin-security-2fa-config-reset-providers.png
  src/images/images/admin-sign-in-2fa-u2f-key.png
  src/images/images/config-security-2fa-authy.png
  src/images/images/config-security-2fa-duo-security.png
  src/images/images/config-security-2fa-duo.png
  src/images/images/config-security-2fa-general.png
  src/images/images/config-security-2fa-google.png
  src/images/images/config-security-2fa-u2f-key.png
  src/images/images/config-security.png
  src/images/images/permissions-user-2fa.png
  src/images/images/system-permissions-user-new.png
  src/stores/admin-signin.md
  src/stores/security-two-factor-authentication-manage.md
  src/stores/security-two-factor-authentication-use.md
  src/stores/security-two-factor-authentication.md
  src/system/permissions-users-all.md
Labels: 2.4, Progress: approved

#537 fixed typo: whee to where
  src/marketing/search-synonyms.md
Labels: Editorial, Progress: approved

#542 Adding whatsnew infrastructure files
  Gemfile
  Gemfile.lock
  Rakefile
  bin/whatsup_github
Labels: 2.4, Progress: approved, Site improvements

#540 Remove Extension Manager from user guide
  src/_data/toc/operations.yml
  src/_includes/web-setup-deprecate.md
  src/cms/lightboxes-and-sliders.md
  src/images/images/web-setup-extension-manager-access-key.png
  src/images/images/web-setup-extension-manager-extensions-ready-to-install.png
  src/images/images/web-setup-extension-manager-install-extensions-step1-readiness-check.png
  src/images/images/web-setup-extension-manager-new-updates.png
  src/images/images/web-setup-extension-manager-ready-to-install.png
  src/images/images/web-setup-extension-manager-step1-complete.png
  src/images/images/web-setup-extension-manager-step1.png
  src/images/images/web-setup-extension-manager-step2-complete.png
  src/images/images/web-setup-extension-manager-step2.png
  src/images/images/web-setup-extension-manager-success.png
  src/images/images/web-setup-extension-manager-summary-detail.png
  src/images/images/web-setup-extension-manager-summary.png
  src/images/images/web-setup-extension-manager.png
  src/images/images/web-setup-extension-summary.png
  src/images/images/web-setup-extensions-grid.png
  src/magento/change-log.md
  src/magento/magento-marketplace-install-extension.md
  src/stores/store-language-add.md
  src/system/backups.md
  src/system/permissions-role-resources.md
  src/system/web-setup-extension-manager.md
  src/system/web-setup-wizard.md
Labels: Major update, Progress: review

#545 Remove additional "include"
  src/reports.md
Labels: 2.4, Editorial

#544 Format updates in customers topics folder
  src/_data/toc/customers.yml
  src/customers/account-companies.md
  src/customers/account-company-admin.md
  src/customers/account-company-approve.md
  src/customers/account-company-create.md
  src/customers/account-company-customer-group.md
  src/customers/account-company-manage.md
  src/customers/account-company-roles-permissions.md
  src/customers/account-company-sales-representative.md
  src/customers/account-company-structure.md
  src/customers/account-company-teams.md
  src/customers/account-company-update.md
  src/customers/account-company-users-role.md
  src/customers/account-company-users-team.md
  src/customers/account-company-users.md
  src/customers/account-create.md
  src/customers/account-dashboard-account-information.md
  src/customers/account-dashboard-company-profile.md
  src/customers/account-dashboard-company-structure.md
  src/customers/account-dashboard-my-downloadable-products.md
  src/customers/account-dashboard-my-orders.md
  src/customers/account-dashboard-my-wish-list.md
  src/customers/account-dashboard-quotes-negotiate.md
  src/customers/account-dashboard-quotes.md
  src/customers/account-dashboard-requisition-lists-manage.md
  src/customers/account-dashboard-requisition-lists.md
  src/customers/account-dashboard-store-credit.md
  src/customers/account-dashboard.md
  src/customers/account-options-new.md
  src/customers/account-scope.md
  src/customers/address-templates.md
  src/customers/customer-account-create-order.md
  src/customers/customer-account-manage.md
  src/customers/customer-account-update.md
  src/customers/customer-account.md
  src/customers/customer-assign-company.md
  src/customers/customer-groups.md
  src/customers/customer-online-options.md
  src/customers/customer-sign-in.md
  src/customers/login-landing-page.md
  src/customers/name-address-options.md
  src/customers/now-online.md
  src/customers/password-options.md
  src/customers/password-reset.md
  src/marketing/email-company-configuration.md
Labels: Editorial, Progress: review

#551 Shared account
  src/images/images/magento-account-share-welcome.png
  src/images/images/magento-account-shared-access-add-new-user.png
  src/images/images/magento-account-shared-access-add.png
  src/images/images/magento-account-shared-access-grant-permissions.png
  src/images/images/magento-account-shared-access-new-user-info.png
  src/images/images/magento-account-shared-access.png
  src/images/images/magento-account-shared-manage-permissions.png
  src/images/images/magento-account-shared-permissions-all.png
  src/images/images/magento-account-shared-support.png
  src/images/images/magento-account-shared-switch.png
  src/images/images/magento-account-shared-with-me.png
  src/images/images/magento-account-shared.png
  src/magento/magento-account-share.md
Labels: Progress: approved

#554 Fix shared access
  src/images/images/magento-account-shared-help-center.png
  src/magento/magento-account-share.md
Labels: Progress: approved

#557 Update English grammar on promotions user guide
  src/marketing/promotions.md
Labels: Editorial, Partner: PHPro, Progress: approved, partners-contribution

#556 Updates for free shipping minimum and new "Delivery Methods" labeling
  src/_data/main-nav.yml
  src/_data/toc/config-ref.yml
  src/_data/toc/sales.yml
  src/configuration/sales/delivery-methods.md
  src/images/images/config-sales-shipping-methods-free-shipping.png
  src/images/images/config-sales-shipping-settings.png
  src/images/images/config-sales.png
  src/images/images/shipping-table-rates-export.png
  src/images/images/shipping-table-rates-import.png
  src/images/images/storefront-cart-table-rate.png
  src/magento/prelaunch-checklist.md
  src/quick-tour/success.md
  src/sales.md
  src/sales/checkout-instant-purchase.md
  src/sales/checkout-step1-shipping.md
  src/sales/order-processing.md
  src/sales/quote-price-negotiation.md
  src/shipping/carriers.md
  src/shipping/delivery.md
  src/shipping/dhl.md
  src/shipping/fedex.md
  src/shipping/methods-basic.md
  src/shipping/point-of-origin.md
  src/shipping/shipping-flat-rate.md
  src/shipping/shipping-free.md
  src/shipping/shipping-label-configure.md
  src/shipping/shipping-label-create.md
  src/shipping/shipping-label-package.md
  src/shipping/shipping-label-workflow.md
  src/shipping/shipping-labels.md
  src/shipping/shipping-multiaddress.md
  src/shipping/shipping-policy-parameters.md
  src/shipping/shipping-settings.md
  src/shipping/shipping-table-rate.md
  src/shipping/ups.md
  src/shipping/usps.md
  src/system/support-system-report.md
  src/tax/vertex-configure-magento.md
Labels: 2.4.0, Major update, Progress: review

#564 Security txt
  src/_data/toc/config-ref.yml
  src/_data/toc/operations.yml
  src/configuration/security/security-txt.md
  src/images/images/config-security-txt-contact-info.png
  src/images/images/config-security-txt-general.png
  src/images/images/config-security-txt-other-info.png
  src/magento/magento-account-share.md
  src/stores/security-admin.md
  src/stores/security-issue-reporting.md
Labels: 2.4.0, New topic, Progress: approved

#562 OM-774: Add MCOM menu info in Operations section
  _config.yml
  src/_data/main-nav.yml
  src/_data/toc/operations.yml
  src/images/images-ee/admin-menu-mcom-ee.png
  src/images/images-ee/mcom-changelog.png
  src/images/images-ee/mcom-integration-enable-disable.png
  src/images/images-ee/mcom-integration.png
  src/images/images-ee/mcom-manage-stock-aggregates-new.png
  src/images/images-ee/mcom-manage-stock-aggregates.png
  src/images/images-ee/mcom-message-log-filters.png
  src/images/images-ee/mcom-message-log-retry.png
  src/images/images-ee/mcom-message-log-trace.png
  src/images/images-ee/mcom-message-log.png
  src/mcom.md
  src/mcom/changelog.md
  src/mcom/integration.md
  src/mcom/manage-stock-aggregates.md
  src/mcom/mcom-menu.md
  src/mcom/message-log.md
Labels: New topic, Progress: review

#566 Adding information about which prex module supports Page Builder
  src/marketing/page-builder-add-product-recs.md
Labels: 2.3.5, Editorial, Progress: approved

#567 Update gems and upgrade ruby
  .ruby-version
  Gemfile.lock
Labels: Progress: approved, maintenance
