Repository magento/merchdocs, pull requests merged in 2021-12, with the labels that each got.

#1632 ACP2E-342: [Documentation] Mention that partially refunded order remains in Processing status until all items are being shipped
  src/sales/order-status.md
Labels: Minor update, Progress: approved, internal-dev, 2.4.x

#1636 ACP2E-348: [Documentation] Add notice into the documentation that new product image is always assigned and visible in all Store Views
  src/catalog/product-image-upload.md
Labels: Minor update, Progress: approved, internal-dev, 2.4.x

#1640 Update display-settings.md
  src/tax/display-settings.md
Labels: Editorial, Progress: approved, 2.4.x

#1635 ACP2E-346: [Documentation] Add final minimum(maximum) price calculation formula into number of documents
  src/catalog/catalog-shared-pricing-structure.md
  src/catalog/product-price-group.md
  src/catalog/product-price-special.md
  src/catalog/product-price-tier.md
  src/marketing/price-rules-catalog-create.md
Labels: Minor update, Progress: approved, internal-dev, 2.4.x

#1637 Update the Custom Order Status page information
  src/sales/order-status-custom.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1638 Add missing columns to the Braintree configuration topic
  src/payment/braintree.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1644 Fixed a minor grammatical error
  src/catalog/product-create-simple.md
Labels: Editorial, Progress: acceptance testing

#1645 Update columns for the page builder topic pages
  src/cms/page-builder-layout-row.md
  src/cms/page-builder-media-banner.md
  src/cms/page-builder-media-slider.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1646 Update search-engine-robots.md
  src/marketing/search-engine-robots.md
Labels: Editorial, Progress: acceptance testing

#1647 Update the columns list on the Gift Card Accounts page
  src/catalog/product-gift-card-accounts.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1648 Update product columns list grid
  src/catalog/products.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1649 ACP2E-395: [Documentation] Add callout that to extend the customization of URLs new and existing URL Rewrites can be used
  src/catalog/catalog-urls.md
Labels: Editorial, internal-dev, Progress: acceptance testing

#1650 ACP2E-402: [Documentation] Mention that currency, price and numbers formatting are affected by the Locale setting
  src/stores/locale-options.md
Labels: Editorial, internal-dev, Progress: acceptance testing
