Repository magento/merchdocs, pull requests merged in 2021-07, with the labels that each got.

#1332 Update fields for the Scheduling an Import page
  src/system/data-schedule-import.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1339 Update the Setting Up a Gift Registry columns
  src/marketing/gift-registry-create.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1347 Describe how to add an item to the gift register
  src/marketing/gift-registries.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1350 Describe how to add a tracking number to a shipment.
  src/images/images/tracking-information.png
  src/sales/shipments-create.md
Labels: Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1352 Add topic about how to update product attribute in bulk
  src/_data/toc/catalog.yml
  src/images/images/bulk-pproduct-attribute-update.png
  src/images/images/bulk-product-updating-action.png
  src/stores/bulk-product-attribute-update.md
Labels: 2.4.x, New topic, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1361 Update SaaS identifier instructions
  src/system/saas.md
Labels: Editorial, Progress: acceptance testing, internal-dev

#1370 Added Additional Info About Integration Managing
  src/images/images/integration-new.png
  src/images/images/integration-tokens-for-extensions.png
  src/system/integrations.md
Labels: 2.4.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#1382 Update pricing-advanced.md
  src/catalog/pricing-advanced.md
Labels: Editorial, Progress: acceptance testing

#1385 Remove "Add Block Names to Hints" and add "Add Block Class Type to hints" where ever required in the docs
  src/configuration/advanced/developer.md
  src/system/template-path-hints.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, Progress: approved, partners-contribution

#1386 Fix missing "Credit Limit Updated' template name
  src/marketing/email-template-list.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1387 Reformat the "Join the Conversation" topic to table
  src/getting-started/magento-ecosystem.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1388 Add the preview and content description to the Configuration Reference topic blocks
  src/stores/configuration.md
Labels: Partner: Atwix, Progress: ready for review, partners-contribution

#1391 Tag fixing on the Intelligent Repricing Rule page
  src/sales-channels/asc/competitor-conditional-variances.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1341 Describe the Layout Updates Options columns for the "Using a Widget to Position a Block" page
  src/cms/widget-static-block.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, Progress: on hold, partners-contribution

#1366 Added explanation for "Applied" option while creating new checkout term and condition
  src/sales/terms-and-conditions.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1357 Add new topic to describe how to allow multiple admin login
  src/images/images/multiple-admin-login.png
  src/stores/admin-signin.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1360 Add description of how to add product attributes to cart price rules
  src/marketing/price-rules-cart-create.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1362 Describe how to configure the Minimum Qty Allowed in Shopping Cart
  src/_data/toc/sales.yml
  src/images/images/minimum-qty-allowed-in-shopping-cart.png
  src/sales/cart-configuration.md
  src/sales/minimum-order-qty.md
Labels: 2.4.x, New topic, Progress: acceptance testing

#1371 Described how to delete attribute set
  src/stores/attribute-sets.md
Labels: 2.4.x, Minor update, Progress: approved

#1374 Fix for camera icon displaying at Media Image page
  src/cms/page-builder-media-image.md
Labels: 2.4.x, Editorial, Progress: approved

#1375 Add description about setting the redirect to Account Dashboard after logging in
  src/customers/customer-sign-in.md
Labels: 2.4.x, Minor update, Progress: approved

#1377 Added info how to delete requisition list from customer's account
  src/customers/account-dashboard-requisition-lists-manage.md
Labels: 2.4.x, Minor update, Progress: approved

#1392 Update account-companies.md
  src/customers/account-companies.md
Labels: 2.4.x, Editorial, Progress: acceptance testing

#1394 Add parentheses to the Manage Product Listings page
  src/sales-channels/asc/managing-listings-by-tab.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1363 Adding a note for content staging preview
  src/cms/content-staging-preview.md
Labels: 2.4.x, Minor update, Progress: acceptance testing

#1364 Describe how to set number of items displayed in the order summary
  src/images/images/order-summary.png
  src/sales/checkout-process.md
Labels: 2.4.x, Minor update, Progress: acceptance testing

#1367 Adding Additional Notes To Email To A Friend Functionality
  src/marketing/email-a-friend.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1369 Added Information About Deleting Admin Users
  src/system/permissions-users-all.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1384 Add a description about adding a new attribute on the fly while creating a product
  src/catalog/product-create-grouped.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1390 Added additional info about widgets managing
  src/_data/toc/content.yml
  src/cms/widget-create.md
Labels: 2.4.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#1395 Fix broken 'Security' and 'Advanced' items on the Configuration Reference page
  src/stores/configuration.md
Labels: 2.4.x, Award: bug fix, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#1396 Describe the update and delete feature for the Scheduling Design Changes
  src/design/schedule.md
  src/images/images/delete-store-design-change.png
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1398 Remove unnecessary ecommerce labels
  src/catalog/product-gift-options.md
  src/catalog/settings-advanced-design.md
  src/stores/bulk-product-attribute-update.md
Labels: 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1399 Update tax-class-new.md
  src/tax/tax-class-new.md
Labels: 2.4.x, Editorial, Progress: approved

#1400 Update customers.yml - Duplicate sub-menu Company Credit
  src/_data/toc/customers.yml
Labels: Progress: acceptance testing, Site improvements

#1402 Fix markdown syntax
  src/marketing/search-terms-popular.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1383 Added "Store URL Option" information while sitemap configuring
  src/images/images/config-catalog-xml-sitemap-store-url-options.png
  src/marketing/sitemap-xml-configure.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1397 Add information about RMA shipping methods
  src/_data/toc/catalog.yml
  src/catalog/product-autosettings.md
  src/images/images/rma-delivery-method.png
  src/sales/rma-configure.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1401 Update the Search Synonyms topic with possible action information
  src/marketing/search-synonyms.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1403 Implement user's experience hint for clearer understanding of the Price Display Settings
  src/images/images/catalog-prices-tax.png
  src/tax/display-settings.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1404 Update catalog-urls.md
  src/catalog/catalog-urls.md
Labels: 2.4.x, Editorial, Progress: acceptance testing

#1408 Edit grammatical typos on the Cart Configuration page
  src/sales/cart-configuration.md
Labels: 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1406 Fill the "Shopping Tools" topic with content
  src/_data/toc/marketing.yml
  src/marketing/customer-engagement.md
  src/marketing/shopping-tools.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1409 Wish List Configuration - Specify multiple wishlist is not in open source version
  src/marketing/wishlist-configuration.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1410 Expanding description of viewing Product Reviews via Magento Admin
  src/images/images/admin-reviews-tab.png
  src/marketing/magento-product-reviews.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1411 Add the Basic Terminology tips about the Managing Inventory
  src/catalog/inventory-learn-more.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1413 Update the action list on the Index Management page
  src/system/index-management.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1418 MC-42708: Scheduled Export does not triggered by cron
  src/system/data-schedule-export.md
  src/system/data-schedule-import.md
  src/system/data-scheduled-import-export.md
Labels: 2.4.x, Minor update, Progress: approved, Stakeholder

#1372 Added Information About Deleting Subscribers From Grid
  src/marketing/newsletter-subscribers.md
Labels: 2.4.x, Minor update, Progress: approved

#1378 Added Additional Information About Wish Lists Managing
  src/customers/account-dashboard-my-wish-list.md
Labels: 2.4.x, Minor update, Progress: approved

#1393 Added additional information about user roles managing
  src/system/permissions-user-roles.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, Progress: on hold, partners-contribution

#1412 Describe the returns attributes creation process
  src/images/images/return-attributes.png
  src/stores/attributes-returns.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1414 Clarify the meaning of the fields for Gift Card Information block
  src/catalog/product-gift-card-information.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1417 Add the Data column to the System Reports page
  src/system/support-system-report.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1420 MC-42925: Custom Attribute not appearing in Layered Navigation
  src/catalog/navigation-layered-filterable-attributes.md
Labels: 2.4.x, Minor update, Progress: approved, Stakeholder
