Repository magento/merchdocs, pull requests merged in 2021-09, with the labels that each got.

#1445 Added Additional information About Deleting Related Product rules
  src/marketing/product-related-rule-create.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1446 Add columns description to the Customer Reports page
  src/reports/customer-reports.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: on hold, 2.4.x

#1447 Added the information about Billing Agreements in customer's account
  src/customers/account-dashboard-billing-agreements.md
  src/images/images/customer-billing-agreements.png
  src/images/images/customer-create-billing-agreement.png
  src/images/images/customer-view-billing-agreement.png
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1451 Steps to Enable Gift Message in Magento 2
  src/catalog/product-gift-options.md
  src/images/images/gift-message.png
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1457 Describe how to setup different prices for same product
  src/catalog/catalog-price-scope.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1464 Add benefits of embedding Google Map
  src/cms/page-builder-media-map.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1466 Describe how to reset orders columns and remove e-commerce label for the Order Action page
  src/sales/order-actions.md
  src/sales/order-grid-layout.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1471 Fix the events titles on the Enhanced Ecommerce topic
  src/marketing/google-enhanced-ecommerce.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1478 Fix: Type in braintree.md
  src/payment/braintree.md
Labels: Editorial, Progress: approved, 2.4.x

#1455 Add the sort orders columns to the Creating Category Rules page
  src/catalog/category-product-rules.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1468 Update image and add description for "Allow remote shopping assistance" and "Show Password"
  src/customers/account-create.md
  src/images/images/storefront-create-account-personal-information.png
  src/images/images/storefront-create-account-signin-information.png
Labels: Minor update, Progress: approved, 2.4.x

#1473 Added additional info about deleting stored payment method
  src/customers/account-dashboard-stored-payment-methods.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1476 Fix markdown in the Workspace controls sheet
  src/catalog/products.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1480 Update the scope field for the Global section of the Configuration list
  src/configuration/general/b2b-features.md
  src/configuration/general/general.md
  src/configuration/general/web.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1482 Add information about Export customers accounts
  src/customers/customer-account-manage.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1483 Correct the typo
  src/sales/order-archive.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1484 Added improvements to reorder from admin section
  src/sales/reorders-allow.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1485 Added additional information to RMA process from customer's account
  src/sales/rma-customer-experience.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1486 Fixes the typo on billing agreements page
  src/sales/billing-agreements.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1487 Add the missing field for the delivery methods
  src/shipping/shipping-flat-rate.md
  src/shipping/shipping-table-rate.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1488 Describe what is it an SKU in Magento
  src/customers/account-dashboard-order-by-sku.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1489 Update the scope and column on the Developer page
  src/configuration/dotdigital/developer.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1494 Fix broken redirect on Elements - HTML Code page
  src/cms/page-builder-elements-html-code.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1495 Correct grammar and markdown mistakes for the Order by SKU topic
  src/sales/order-by-sku.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1472 Added additional information about managing gift registry items
  src/customers/account-dashboard-gift-registry.md
  src/images/images-ee/account-dashboard-gift-registry-items-management.png
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1474 Added additional information about restricting access setting
  src/marketing/event-restrict-access.md
Labels: partners-contribution, Progress: approved, Partner: Atwix

#1475 Added additional information to event-update page
  src/images/images-ee/catalog-event-updating.png
  src/marketing/event-update.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1477 Add clarification about the Minimum Advertised Price workflow
  src/catalog/product-price-minimum-advertised.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1493 Add description about removing a page
  src/_data/toc/content.yml
  src/cms/page-duplicate.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1497 Reward point configuring edits
  src/marketing/reward-point-configure.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1498 Added information how to delete exchange-rate
  src/marketing/reward-exchange-rates.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1469 Describe how to manage the sales reports
  src/reports/sales-reports.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1481 Added additional information for Approval rules page
  src/customers/account-dashboard-approval-rules.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1496 Added missed step on the Scheduled Changes page
  src/catalog/product-scheduled-changes.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1500 Update the "Create a Newsletter Template" flow on the Newsletter Templates page
  src/marketing/variables-predefined.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: on hold, 2.4.x

#1501 Add missing columns to the Store Contact Information Variables
  src/marketing/variables-reference.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1502 Added additional information to Moderate Reviews page
  src/marketing/magento-product-reviews-moderate.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1504 Fix links issue on the Company Users page
  src/customers/account-dashboard-company-users.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1505 Remove duplicate step from the Product Rewrites page
  src/marketing/url-rewrite-product.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1506 Add configuration tip for the Newsletter Subscription topic
  src/customers/account-dashboard-newsletter-subscriptions.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix

#1509 Markdowns correction
  src/catalog/product-create-configurable.md
  src/live-search/facets-add.md
  src/marketing/price-rules-catalog-create.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1515 Minor fixes for header and pagination pages (combined from 1510/1511)
  src/catalog/navigation-pagination.md
  src/design/header.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1516 Expand editing the company users, add notice about adding/editing/removing the company users
  src/customers/account-company-users.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1517 Add information about canceling of Billing Agreement from the storefront
  src/customers/account-dashboard-billing-agreements.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1491 Describe how to Configure New Order Email Notification
  src/sales/order-status-notification.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1499 Edited outdated information on configuring visual merchandiser configuration page
  src/marketing/visual-merchandiser-configuration.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1508 Add description about admin updating the Credit Limit
  src/customers/credit-company-activity.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1512 Add new topic about the Dotdigital form
  src/marketing/dotdigital/engagement-cloud.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1513 Added additional information to search term page
  src/marketing/search-terms-add.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1514 Update the columns on the Email Template List page
  src/marketing/email-template-list.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1520 Added additional information about updating customer's store credit balance
  src/customers/store-credit-using.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1521 Added an information about applying not redeemable gift cards on checkout
  src/customers/account-dashboard-gift-cards.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1522 Added Additional information to gift card accounts page
  src/catalog/product-gift-card-accounts.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1525 Resource fix for the Browser Capabilities Detection topic
  src/stores/security-browser-capabilities-detection.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1527 Add callout info about how many coupons can a Customer use in Magento 2
  src/quick-tour/checkout-page.md
  src/sales/checkout-process.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1530 Add info about domain setting for the Magento stores of the Scope Quick Reference topic
  src/stores/store-scope-reference.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing
