Repository magento/merchdocs, pull requests merged in 2021-03, with the labels that each got.

#1070 Update yotpo-reporting Typo Corrected.md
  src/marketing/yotpo-reporting.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved, Progress: on hold

#1074 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#1079 Update for SWAT access, assigned permissions
  src/images/images-ee/reports-swat-role-access.png
  src/reports/site-wide-analysis-tool.md
Labels: 2.4.x, Minor update, Progress: approved

#1081 Link to commerce features
  src/getting-started.md
Labels: 2.4.x, Minor update, Port change, Progress: approved

#1083 Fix liquid syntax warning
  src/marketing/email-template-message.md
Labels: 2.4.x, Editorial, Progress: approved

#1076 magento/merchdocs#: adds items to the table in advanced content tools for content management section
  src/configuration/general/content-management.md
Labels: 2.4.x, Community, Minor update, Partner: Atwix, Progress: approved, Progress: on hold, partners-contribution

#1075 magento/merchdocs#: adds items to the table in storefront settings for catalog section
  src/configuration/catalog/catalog.md
Labels: 2.4.x, Community, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1082 magento/merchdocs#: adds item to the table in password options for customer configuration section
  src/configuration/customers/customer-configuration.md
Labels: 2.4.x, Community, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1084 Update site-wide-analysis-tool.md
  src/reports/site-wide-analysis-tool.md
Labels: 2.4.x, Minor update, Progress: approved, Stakeholder

#1080 PAY-621: Voids summary
  src/magento-payments/voids.md
Labels: Progress: approved, internal-dev

#1077 Adding Product Recommendations Specific Cookies
  src/stores/cookie-reference.md
Labels: Minor update, Progress: approved, Stakeholder

#1087 Customer Group and Shared Catalog limitations by Websites
  src/customers/account-scope.md
  src/customers/customer-groups.md
  src/images/images/stores-customer-group-information.png
Labels: 2.4.3, Minor update, Progress: approved, Stakeholder

#1085 FTP > FPT
  src/tax/tax-settings-general.md
Labels: Editorial, Progress: approved

#1086 Amazon 4.4 Updates
  src/configuration/sales-channels/global-settings.md
  src/images/images/config-sales-channels.png
  src/sales-channels/asc/assets/config-sales-channel-global-settings.png
Labels: Minor update, Progress: approved, asc-release

#1092 Update linter.yml
  .github/workflows/linter.yml
Labels: Progress: review, maintenance

#1091 Add deprecation notice for db media storage
  src/configuration/advanced/system.md
  src/images/images/config-advanced-database-storage-deprecated.png
  src/images/images/config-advanced-system-storage-configuration-for-media-database.png
  src/system/media-storage-database.md
Labels: 2.4.3, Editorial, Progress: approved, internal-dev

#1088 Add site assessment doc link
  src/getting-started/quick-tour.md
Labels: 2.4.x, Minor update, Progress: approved

#1090 Update dotdigital release highlights for 2.4.2
  src/marketing/dotdigital/engagement-cloud.md
Labels: 2.4.2, Minor update, Progress: approved, Technology Partner: dotdigital, tech-partners-contribution

#1093 Update order-status-custom.md
  src/sales/order-status-custom.md
Labels: Editorial, Progress: ready for review

#1095 Update shipping-in-store-delivery.md
  src/shipping/shipping-in-store-delivery.md
Labels: 2.4.x, Minor update, Progress: approved, Stakeholder
