Repository magento/merchdocs, pull requests merged in 2021-04, with the labels that each got.

#1106 magento/merchdocs#1102: UPS. Access License Number, clarification
  src/shipping/ups.md
Labels: Editorial, Progress: acceptance testing

#1112 Image for hidden category
  src/catalog/category-hidden.md
  src/images/images/hidden-categories.png
Labels: Minor update, Progress: acceptance testing

#1115 Fix typo grammar
  src/marketing/google-tag-manager.md
Labels: Editorial, Progress: approved

#1100 [PayPal] Added note on require customer’s billing address in express checkout
  src/payment/paypal-express-checkout.md
Labels: Editorial, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#1128 Delete the square bracket from the Actions Control page.
  src/stores/admin-actions-control.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1138 Change image for magento Reports Menu
  src/images/images/reports-overview.png
  src/images/images/stores-menu.png
  src/images/images/system-menu.png
  src/reports/reports-menu.md
  src/stores/stores-menu.md
  src/system/system-menu.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1145 magento/merchdocs#1144: Add missing options to the Products Grid page
  src/catalog/products.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1146 magento/merchdocs #1136 : Feedback on page: /system/data-attributes-product.html
  src/_data/toc/operations.yml
  src/system/data-attributes-product.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1148 MC-41680: Visitor Customer are not displayed in "Now Online Customer" Grid
  src/customers/now-online.md
Labels: Editorial, Minor update, Progress: acceptance testing

#1105 magento/merchdocs#1103: Allow Reorders from customer account
  src/images/images/create-reorder-page.png
  src/images/images/my-order-page-view.png
  src/images/images/my-orders-view-page1.png
  src/images/images/order-view-admin.png
  src/images/images/order-view-page.png
  src/images/images/shopping-cart-page.png
  src/images/images/shopping-cart-view1.png
  src/sales/reorders-allow.md
Labels: 2.4.x, Major update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1110 #issue-1108 Describe Image Detail for products
  src/catalog/product-images-and-video.md
  src/images/images/details.png
  src/images/images/image-video.png
Labels: 2.4.x, Major update, Progress: acceptance testing

#1119 magento/merchdocs#1118: Describe the Gift Card functionality
  src/customers/account-dashboard-gift-cards.md
  src/images/images/gift-balance.png
  src/images/images/gift-reddemed-balance.png
  src/images/images/store-credit.png
Labels: 2.4.x, Major update, Progress: acceptance testing

#1125 magento/merchdocs#1124: Describe sign out of the customer account
  src/customers/customer-sign-in.md
  src/images/images/homepage.png
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1127 magento/merchdocs#1126: Add the "Reset" button clarification to the Grid Layout page
  src/stores/admin-grid-layout.md
Labels: 2.4.x, Minor update, Progress: acceptance testing

#1131 magento/merchdocs#1130: Describe product editing flow for Requisition List
  src/customers/account-dashboard-requisition-lists-manage.md
Labels: 2.4.x, Major update, Progress: acceptance testing

#1147 Add "Login as customer" button description for the Customer Profile page
  src/customers/customer-account-update.md
  src/images/images-ee/customer-profile.png
  src/images/images/cust-profile.png
Labels: Editorial, Progress: acceptance testing

#1152 magento/merchdocs#1151: Add missing items to the Role Resources page
  src/system/permissions-role-resources.md
Labels: Editorial, Progress: acceptance testing, Progress: ready for review

#1167 Add missing cache types to the Cache Management page
  src/system/cache-management.md
Labels: Editorial, Partner: Atwix, Progress: approved, Progress: ready for review, partners-contribution

#1170 Describe source adding to the product for the Sources page.
  src/catalog/sources.md
Labels: Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1177 magento/merchdocs#1168: Sales | The /sales/order-ship.html page isn't displayed in the sidebar
  src/_data/toc/sales.yml
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1149 Update cookie-reference.md
  src/stores/cookie-reference.md
Labels: Editorial, Progress: acceptance testing, Progress: approved

#1156 magento/merchdocs#1129: Supplement the "Actions by grid" block
  src/stores/admin-actions-control.md
Labels: Major update, Partner: Atwix, Progress: approved, partners-contribution

#1153 Add missing Entity Type options to the Import page
  src/images/images/import-options.png
  src/images/images/system-import.png
  src/system/data-import.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1155 magento/merchdocs#1154: Catalog| Product Workspace: Expand Product Scheduled Changes
  src/catalog/product-scheduled-changes.md
  src/images/images-ee/remove-product-scheduled-changes.png
  src/images/images-ee/scheduled-changes-assign-to-existing-campaign.png
  src/images/images-ee/view-product-scheduled-changes.png
Labels: 2.4.x, Major update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1176 magento/merchdocs#1166: Sales | Removed deleted "Shipment Workflow" topic from TOC
  src/_data/toc/sales.yml
  src/shipping/delivery.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1181 magento/merchdocs#1162: Stores | Expand a methods of Using a Custom Admin URL
  src/stores/store-urls-custom-admin.md
Labels: Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1182 magento/merchdocs#1179|1174 : Remove wrong label and fix broken link
  src/customers/account-dashboard.md
  src/sales/shipments.md
Labels: 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1197 Add Inventory Indexer Settings for the Inventory page
  src/configuration/catalog/inventory.md
Labels: Minor update, Progress: acceptance testing, Progress: approved

#1205 Update the Design page from the Other Settings block
  src/catalog/settings-advanced-design.md
  src/images/images-ee/product-design-ee.png
Labels: Editorial, Progress: approved

#1158 magento/merchdocs#1157: Add gift card account history
  src/catalog/product-gift-card-accounts.md
  src/images/images-ee/gift-card-history.png
Labels: 2.4.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#1163 magento/merchdocs#1117: Expand catalog and products viewed compared topics
  src/configuration/catalog/catalog.md
  src/images/images/config-catalog-catalog-recently-viewed-and-compared-products.png
  src/images/images/config-catalog-catalog-recently-viewed-compared-products.png
  src/marketing/products-viewed-compared.md
Labels: Partner: Atwix, Progress: acceptance testing, partners-contribution

#1164 magento/merchdocs#1142: My Wish List | Add the clarification about creating a Wish List from storefront
  src/customers/account-dashboard-my-wish-list.md
  src/images/images-ee/account-dashboard-wishlist-create-from-cart.png
  src/images/images-ee/account-dashboard-wishlist-create-from-pdp.png
Labels: 2.4.x, Major update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1169 Add Gift Card Email Sender actions
  src/catalog/product-gift-card-account-configuration.md
Labels: 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1172 magento/merchdocs#1171: Moderation of product reviews
  src/catalog/settings-advanced-product-reviews.md
  src/images/images/product-review.png
  src/images/images/product-reviews-grid-empty.png
Labels: Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1183 magento/merchdocs#1089: Add RMA how-to instructions to Returns section
  src/images/images/return-item-request.png
  src/images/images/sales-return.png
  src/images/images/sales-returns.png
  src/sales/returns.md
Labels: Partner: Atwix, Progress: acceptance testing, partners-contribution

#1184 Describe the Recently Ordered block for the My Account page
  src/customers/account-dashboard-my-account.md
Labels: Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1190 Viewing and using store credit balance on the storefront
  src/images/images-ee/customer-account-order-refund-from-checkout.png
  src/sales/refunds-customer-account.md
Labels: Partner: Atwix, Progress: acceptance testing, partners-contribution

#1201 Update page-builder-elements-buttons.md
  src/cms/page-builder-elements-buttons.md
Labels: 2.4.x, Minor update, Progress: acceptance testing

#1207 MC-41940: Payment on Account not available in multishipping
  src/configuration/sales/multishipping-settings.md
  src/configuration/sales/payment-methods.md
  src/payment/payment-on-account.md
  src/shipping/shipping-multiaddress.md
Labels: Progress: acceptance testing

#1211 Update klarna-customer-experience.md
  src/images/images/storefront-cart-payment-method-klarna1.png
  src/images/images/storefront-cart-payment-method-klarna1b.png
  src/images/images/storefront-cart-payment-method-klarna2.png
  src/images/images/storefront-cart-payment-method-klarna2b.png
  src/images/images/storefront-cart-payment-method-klarna_ot.png
  src/images/images/storefront-cart-payment-method-klarna_pl.png
  src/payment/klarna-customer-experience.md
Labels: 2.4.x, Minor update, Progress: approved

#1245 Update the "Configure the default pages" block
  src/cms/pages-default.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1210 Remove the Notify for Quantity Below field from the Configure advanced product options block
  src/catalog/inventory-product-stock-options.md
  src/images/images/product-inventory-manage-stock-yes.png
Labels: 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1212 Add instruction how to configure the priority of sources on the Configuring Source Priority Algorithm page
  src/catalog/inventory-configure-source-priority.md
  src/images/images/delete-action.png
  src/images/images/drag-and-drop-action.png
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1213 Gift Registry management expanding
  src/customers/account-dashboard-gift-registry.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1161 magento/merchdocs#1160 Add a new topic about adding products to the categories
  src/_data/toc/catalog.yml
  src/catalog/category-products-add.md
  src/images/images-ee/add-product-by-sku.png
  src/images/images-ee/category-product.png
  src/images/images-ee/search-all-product.png
Labels: 2.4.x, New topic, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1187 Edit the container description for the UPS page
  src/shipping/ups.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, Progress: approved, partners-contribution

#1191 Add the Allow Zero GrandTotal field to the Sales page
  src/configuration/sales/sales.md
Labels: Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1214 Adding customer tips for downloadable products
  src/customers/account-dashboard-my-downloadable-products.md
Labels: 2.4.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#1243 Replacing the wrong 'Shared Catalogs' link to correct one
  src/customers/customer-groups.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution
