Repository magento/merchdocs, pull requests merged in 2021-02, with the labels that each got.

#1019 Update inventory-configure-inventory-management.md
  src/catalog/inventory-configure-inventory-management.md
Labels: Editorial, Progress: approved

#1018 Update yotpo.md
  src/configuration/yotpo.md
Labels: Editorial, Progress: approved

#1020 Fixed typo
  src/customers/customer-account.md
Labels: Editorial, Progress: approved

#1024 Disable the jscpd linter
  .github/workflows/linter.yml
Labels: Progress: approved, maintenance

#1022 Updated the Admin Usage Description section
  src/configuration/advanced/admin.md
Labels: 2.4.2, Minor update, Progress: approved, Stakeholder

#1023 Update Usage data Collection
  src/stores/admin.md
Labels: 2.4.2, Minor update, Progress: approved, Stakeholder

#1025 Fixed broken release note link
  src/magento/about-this-release.md
Labels: 2.4.x, Editorial, Progress: approved

#1012 magento/merchdocs#: Minor fixes in Sales, dotdigital and Services navigation
  src/configuration/dotdigital.md
  src/configuration/sales.md
  src/configuration/services.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#1011 magento/merchdocs#: Minor fixes in Sales Channel navigation
  src/configuration/sales-channels.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#1027 magento/merchdocs#: Minor fixes in navigation Sales Channels | Global Settings
  src/configuration/sales-channels/global-settings.md
Labels: Editorial, Progress: approved

#1028 Disable JSCPD for 2.3 production
  .github/workflows/linter.yml
Labels: Progress: approved, maintenance

#1021 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#1029 Customer segment example update
  src/images/images-ee/customer-segment-condition-date-of-birth.png
  src/images/images-ee/customer-segment-condition-equals-or-greater-than.png
  src/images/images-ee/customer-segment-condition-line1.png
  src/images/images-ee/customer-segment-condition-millennial.png
  src/images/images-ee/customer-segment-conditions-la-ladies.png
  src/images/images-ee/customer-segment-matched-customers.png
  src/images/images-ee/customer-segment-saved.png
  src/images/images-ee/customer-segments.png
  src/marketing/customer-segment-create.md
Labels: 2.3.x, Minor update, Progress: approved

#1030 Update release notes links for 2.4.2
  src/magento/about-this-release.md
Labels: 2.4.2, Minor update, Progress: approved

#1026 magento/merchdocs#: Minor fixes in navigation B2B role resources for stores
  src/configuration/customers.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#1035 updating Recs limitations
  src/marketing/product-recs-limitations.md
Labels: 2.4.x, Progress: approved, Stakeholder

#1032 Fix procedure table formatting
  src/customers/password-options.md
Labels: 2.3.x, Editorial, Progress: approved

#1033 Customer segment example update
  src/images/images-ee/customer-segment-condition-date-of-birth.png
  src/images/images-ee/customer-segment-condition-equals-or-greater-than.png
  src/images/images-ee/customer-segment-condition-line1.png
  src/images/images-ee/customer-segment-condition-millennial.png
  src/images/images-ee/customer-segment-conditions-la-ladies.png
  src/images/images-ee/customer-segment-matched-customers.png
  src/images/images-ee/customer-segment-saved.png
  src/images/images-ee/customer-segments.png
  src/marketing/customer-segment-create.md
Labels: 2.4.x, Minor update, Progress: approved

#1031 magento/merchdocs#: Minor fixes in Customers, Catalog, Advanced navigations
  src/configuration/advanced.md
  src/configuration/catalog.md
  src/configuration/customers.md
  src/configuration/general.md
  src/configuration/security.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#1039 2.4.2 whats new
  src/_data/whats-new.yml
Labels: 2.4.2, Progress: approved, maintenance

#1016 MC-40589: Document page builder preview limitation for filtering/sorting configurable, grouped and bundle products by price.
  src/cms/page-builder-add-content-products.md
Labels: Progress: approved

#1017 MC-39773: [Documentation] Editing Price Rule itself affects current scheduled update
  src/cms/content-staging.md
Labels: 2.3.x, 2.4.x, Editorial, Progress: approved

#1038 MC-40719: Product Thumbnails not switching properly for Config product
  src/catalog/product-create-configurable.md
  src/catalog/swatch-create.md
  src/catalog/swatches.md
Labels: 2.4.x, Minor update, Progress: approved, Stakeholder

#1008 Issue with the description line in Maximum Qty Allowed in Shopping Cart
  src/configuration/catalog/inventory.md
Labels: Progress: approved

#1015 MC-40640: [Documentation] Update documentation for MSI Offline distance calculation
  src/catalog/inventory-configure-distance-priority.md
Labels: Editorial, Progress: approved, internal-dev

#1043 Fix a bug at 'rake whatsnew since'
  Rakefile
Labels: Progress: approved, maintenance

#1044 DOB 2.3 configuration ref disclaimers
  src/configuration/customers/customer-configuration.md
  src/configuration/dotdigital/data-mapping.md
  src/system/data-import-product-images.md
Labels: 2.3.x, Minor update, Port change, Progress: approved

#1036 PAY-776: Onboarding Magento Payments topic
  src/magento-payments/assets/onboarding-viewedit-sandbox.png
  src/magento-payments/assets/onboardingflow-docs.png
  src/magento-payments/onboarding-payments.md
Labels: Progress: review, internal-dev

#1048 Trailing space
  src/cms/content-staging.md
Labels: Progress: approved, maintenance

#1049 DOB 2.3 cust attributes disclaimers
  src/customers/account-create.md
  src/customers/customer-account-manage.md
  src/images/images/customers-all-customers.png
  src/images/images/customers-grid-quick-edit.png
  src/stores/attributes-customer.md
  src/system/data-attributes-customer.md
Labels: 2.3.x, Editorial, Port change, Progress: approved

#1050 Revert https://github.com/magento/merchdocs/pull/1016.
  src/cms/page-builder-add-content-products.md
Labels: Editorial, Progress: approved

#1051 MC-40589: Document page builder preview limitation for filtering/sorting configurable, grouped and bundle products by price
  src/cms/page-builder-add-content-products.md
Labels: 2.4.3, Minor update, Progress: approved, Stakeholder

#1052 DOB 2.3 name address and screens
  src/customers/name-address-options.md
  src/images/images-b2b/customers-all-grid.png
  src/images/images/customers-grid-export.png
  src/images/images/customers-grid-tax-vat-number.png
Labels: 2.3.x, Editorial, Port change, Progress: approved

#1053 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#1054 2.4 DOB disclaimers and updates
  src/configuration/customers/customer-configuration.md
  src/configuration/dotdigital/data-mapping.md
  src/customers/account-create.md
  src/customers/customer-account-manage.md
  src/customers/name-address-options.md
  src/images/images-b2b/customers-all-grid.png
  src/images/images/customers-all-customers.png
  src/images/images/customers-grid-export.png
  src/images/images/customers-grid-quick-edit.png
  src/images/images/customers-grid-tax-vat-number.png
  src/stores/attributes-customer.md
  src/system/data-attributes-customer.md
  src/system/data-import-product-images.md
Labels: 2.4.x, Forward port, Minor update, Progress: approved

#1056 FIx typo
  src/customers/login-as-customer.md
Labels: 2.4.x, Editorial, Progress: approved

#1059 Update klarna.md
  src/payment/klarna.md
Labels: Editorial, Progress: approved

#1060 Spaced out line 36 number from text
  src/system/cron.md
Labels: Editorial, Progress: approved

#1061 Topic tuneup - sales folder, pt 3 - GH 725
  src/_data/toc/sales.yml
  src/catalog/product-gift-card-accounts.md
  src/configuration/sales/tax.md
  src/images/images-b2b/storefront-quick-order-link.png
  src/images/images-b2b/storefront-quick-order-page.png
  src/images/images/order-move-to-archive.png
  src/images/images/order-search-filter.png
  src/images/images/order-search.png
  src/images/images/order-status-assign-state.png
  src/images/images/order-status-new.png
  src/images/images/order-status.png
  src/images/images/sales-order-edit-address.png
  src/images/images/sales-order-edit.png
  src/images/images/store-status-assign-status.png
  src/images/images/storefront-order-by-sku.png
  src/sales/batches.md
  src/sales/billing-agreements.md
  src/sales/order-actions.md
  src/sales/order-archive-configure.md
  src/sales/order-archive.md
  src/sales/order-by-sku.md
  src/sales/order-grid-layout.md
  src/sales/order-grid-updates-schedule.md
  src/sales/order-pending-payment-lifetime.md
  src/sales/order-processing.md
  src/sales/order-scheduled-operations.md
  src/sales/order-ship.md
  src/sales/order-status-custom.md
  src/sales/order-status-notification.md
  src/sales/order-status-workflow.md
  src/sales/order-status.md
  src/sales/order-update.md
  src/sales/order-workflow.md
  src/sales/orders-search.md
  src/sales/orders-workspace.md
  src/sales/orders.md
  src/sales/point-of-purchase.md
  src/sales/quick-order.md
  src/sales/sales-menu.md
Labels: 2.3.x, Editorial, Port change, Progress: approved

#1047 Added 'allowed countries' to the reference
  src/stores/store-scope-reference.md
Labels: 2.4.x, Community, Minor update, Progress: approved

#1062 Add missing Commerce icon
  src/_data/toc/customers.yml
Labels: Editorial, Progress: approved

#1067 Remove widgets on content staging
  src/cms/content-staging.md
Labels: 2.4.x, Minor update, Port change, Progress: approved

#1064 PAY-663: Payments overview topic
  src/magento-payments/onboarding-payments.md
  src/magento-payments/payments.md
Labels: Progress: review

#1040 Updating SaaS and adding Cold Start content
  src/marketing/product-recommendations.md
  src/system/saas.md
Labels: 2.4.x, Major update, Progress: approved

#1066 magento/merchdocs#: adds items to the table in the Persistent Shopping Cart section
  src/configuration/customers/persistent-shopping-cart.md
Labels: 2.3.x, 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1071 magento/merchdocs#: adds items to the table in Order by SKU Settings for Customer Group section
  src/configuration/sales/sales.md
Labels: 2.3.x, 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1073 Revising onboarding flow diagram with recent version
  src/magento-payments/assets/onboardingflow-docs-v2.png
  src/magento-payments/assets/onboardingflow-docs.png
  src/magento-payments/onboarding-payments.md
Labels: Progress: approved
