Repository magento/merchdocs, pull requests merged in 2021-01, with the labels that each got.

#963 Backport linter
  .github/linters/.markdownlint.json
  .github/linters/.ruby-lint.yml
  .github/workflows/linter.yml
  .github/workflows/main.yml
  .markdownlint.json
  Rakefile
  _checks/html_check_hook.rb
  _plugins/github-path.rb
  bin/image_optim
  bin/jekyll
  bin/mdl
  bin/whatsup_github
  lib/double_slash_check.rb
  lib/link-checker.rb
  rakelib/build.rake
  rakelib/check.rake
  rakelib/preview.rake
  rakelib/test.rake
  src/catalog/product-create-bundle.md
  src/configuration/customers/newsletter.md
  src/magento/security-scan.md
  src/marketing/price-rules-cart-coupon.md
  src/marketing/price-rules-cart-create.md
  src/shipping/shipping-label-workflow.md
Labels: 2.3.x, Progress: approved, maintenance

#951 update manage subscribers page v2.3.x
  src/marketing/newsletter-subscribers.md
Labels: 2.3.x, Community, Minor update, Partner: EY, Progress: approved, partners-contribution

#947 Changing image in Developer doc
  src/configuration/dotdigital/developer.md
  src/images/images/dotdigital-dash-iprestrict.png
Labels: 2.4.x, Community, Minor update, Progress: approved

#955 Notify for Quantity Below clarity
  src/catalog/inventory-backorders.md
Labels: 2.4.x, Community, Minor update, Partner: EY, Progress: approved, partners-contribution

#964 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#962 Add info for shipping step with downloadable products
  src/catalog/product-create-downloadable.md
Labels: 2.4.x, Community, Minor update, Partner: Ziffity, Port change, Progress: approved, partners-contribution

#969 Clarify multi-store/site config process
  src/stores/stores-all-create-store.md
  src/stores/stores-all-create-website.md
  src/stores/websites-stores-views.md
Labels: Minor update, Progress: approved, internal-dev

#970 618 - Clarify 2FA process
  src/_data/toc/operations.yml
  src/stores/security-two-factor-authentication-use.md
  src/stores/security-two-factor-authentication.md
Labels: Minor update, Progress: approved, internal-dev

#972 Update paypal-payments-standard.md
  src/payment/paypal-payments-standard.md
Labels: Editorial, Progress: approved

#973 CCPA minor updates
  src/stores/compliance-ccpa-guide.md
  src/stores/compliance-ccpa.md
Labels: Minor update, Progress: approved, internal-dev

#974 Fix typo
  src/cms/page-hierarchy-node-add.md
Labels: Editorial, Progress: approved

#966 Update recommendation-metrics.md
  src/marketing/recommendation-metrics.md
Labels: Editorial, Progress: approved

#975 SWAT update
  src/_data/toc/operations.yml
  src/reports/site-wide-analysis-tool.md
Labels: Minor update, Progress: approved, internal-dev

#977 Remove backorders configuration source scope
  src/catalog/inventory-backorders.md
Labels: 2.3.x, Minor update, Port change, Progress: approved

#976 B2B Add payment limitation info around purchase orders
  src/customers/account-dashboard-approval-rules.md
Labels: 2.4.2, Minor update, Progress: approved

#979 PAY-850: Revise Payouts doc to reflect date picker changes
  src/magento-payments/payouts.md
Labels: Progress: approved, internal-dev

#984 Update version and links
  src/magento/about-this-release.md
Labels: 2.4.1, Minor update, Progress: approved

#983 Adding info about requiring API key and SaaS Env
  src/system/catalog-sync.md
Labels: Progress: approved

#985 Fix Shipping option labels in field description table
  src/configuration/general/b2b-features.md
Labels: 2.4.x, Editorial, Progress: approved

#989 2.3 fixes for builds and testing
  _plugins/github_path.rb
  _plugins/last_modified_at.rb
  lib/link_checker.rb
  src/catalog/product-create-bundle.md
  src/marketing/price-rules-cart-create.md
  src/sales-channels/amazon/managing-listings-by-action.md
  src/shipping/magento-shipping-click-collect.md
Labels: 2.3.x, Progress: approved, maintenance

#980 Clarify use system value
  src/configuration/scope-change.md
  src/configuration/scope.md
  src/stores/configuration.md
Labels: Editorial, Minor update, Progress: approved

#988 Update What's New
  src/_data/whats-new.yml
Labels: Automation, Progress: approved

#991 magento/merchdocs#: Wish List. Sharing Options. Add information about MAX input value for "Email Text Length Limit"
  src/configuration/customers/wishlist.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#994 Add more verbiage about multiple invoicing
  src/sales/invoice-create.md
Labels: 2.4.x, Editorial, Progress: approved

#997 magento/merchdocs#: Minor fixes
  src/sales/shipment-cancel.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#995 Sync 2.4.2
  .gitignore
  .whatsup.yml
  src/_data/toc/operations.yml
  src/_data/whats-new.yml
  src/catalog/inventory-backorders.md
  src/catalog/product-create-downloadable.md
  src/cms/page-hierarchy-node-add.md
  src/configuration/customers/wishlist.md
  src/configuration/dotdigital/developer.md
  src/configuration/general/b2b-features.md
  src/configuration/scope-change.md
  src/configuration/scope.md
  src/configuration/services/oauth.md
  src/images/images/config-catalog-catalog-product-reviews.png
  src/images/images/config-catalog-catalog-product-video.png
  src/images/images/dotdigital-dash-iprestrict.png
  src/images/images/reports-customers-segments.png
  src/images/images/reports-customers-wish-list.png
  src/magento/about-this-release.md
  src/marketing/newsletter-subscribers.md
  src/marketing/recommendation-metrics.md
  src/payment/paypal-payments-standard.md
  src/reports/site-wide-analysis-tool.md
  src/sales/order-processing.md
  src/sales/orders-workspace.md
  src/sales/orders.md
  src/stores/compliance-ccpa-guide.md
  src/stores/compliance-ccpa.md
  src/stores/configuration.md
  src/stores/security-two-factor-authentication-use.md
  src/stores/security-two-factor-authentication.md
  src/stores/stores-all-create-store.md
  src/stores/stores-all-create-website.md
  src/stores/websites-stores-views.md
  src/system/catalog-sync.md
Labels: 2.4.2, Progress: approved, maintenance

#998 Update linking for Admin usage data
  src/stores/admin.md
Labels: 2.4.x, Minor update, Progress: approved

#982 Security action plan
  src/_data/toc/operations.yml
  src/magento/magento-security-best-practices.md
  src/magento/security-action-plan.md
  src/stores/security.md
  src/stores/store-urls-custom-admin.md
Labels: Editorial, Minor update, Progress: review

#996 magento/merchdocs#: Customize the template. Add information how to add a custom CSS
  src/images/images/email-template-add-custom-styles-min.png
  src/marketing/email-template-message.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1002 Remove 'the' duplicates
  src/catalog/catalog-shared-create.md
  src/catalog/catalog-shared-custom-pricing-update.md
  src/catalog/catalog-shared-general-information-update.md
  src/catalog/catalog-shared-pricing-structure.md
  src/catalog/catalog-shared-product-add.md
  src/catalog/catalog-shared-product-selection-update.md
  src/catalog/product-create-downloadable.md
  src/catalog/product-price-special.md
  src/cms/page-builder-add-content-products.md
  src/cms/page-builder-elements-buttons.md
  src/cms/page-builder-elements-divider.md
  src/cms/page-builder-layout-tabs.md
  src/cms/page-builder-media-slider.md
  src/cms/page-builder-tutorial2-blocks.md
  src/marketing/page-builder-add-product-recs.md
  src/sales-channels/asc/buy-box-competitor-pricing.md
  src/sales-channels/asc/lowest-competitor-pricing.md
  src/system/data-transfer.md
Labels: 2.4.x, Editorial, Progress: approved

#1001 Update image
  src/images/images/config-sales-checkout-shopping-cart-grouped-product.png
Labels: 2.4.x, Minor update, Progress: approved

#1007 Issue-1006- Removed additional line in Product Configuration page
  src/catalog/product-create-configurable.md
Labels: Editorial, Partner: EY, Progress: approved, partners-contribution

#1004 Storing old passwords
  src/customers/password-options.md
  src/stores/admin-signin.md
  src/stores/security-admin.md
Labels: Editorial, Minor update, Port change, Progress: approved

#1003 Backward port
  src/catalog/inventory-shipment-create.md
  src/catalog/product-create-downloadable.md
  src/configuration/catalog/inventory.md
  src/configuration/customers/wishlist.md
  src/configuration/general/web.md
  src/customers/account-dashboard-account-information.md
  src/customers/account-dashboard-address-book.md
  src/customers/account-dashboard-gift-cards.md
  src/customers/account-dashboard-my-downloadable-products.md
  src/customers/account-dashboard-my-invitations.md
  src/customers/account-dashboard-my-orders.md
  src/customers/account-dashboard-my-product-reviews.md
  src/customers/account-dashboard-my-wish-list.md
  src/customers/account-dashboard-newsletter-subscriptions.md
  src/customers/account-dashboard-store-credit.md
  src/customers/account-dashboard.md
  src/customers/customer-groups.md
  src/getting-started/contribute.md
  src/marketing/price-rules-cart-coupon.md
  src/sales/order-processing.md
  src/sales/orders-workspace.md
  src/sales/orders.md
  src/stores/admin-dashboard.md
  src/stores/country-options.md
  src/tax/vat-validation-configure.md
  src/tax/warning-messages.md
Labels: 2.3.x, Back port, Progress: approved

#1009 PAY-795: Update docs with more info about Credit memo process and invoicing
  src/sales/credit-memo-create.md
  src/sales/credit-memos.md
  src/sales/invoice-create.md
  src/sales/order-status.md
Labels: Editorial, Progress: approved, internal-dev

#999 Update price-rule-catalog-scheduled-changes.md
  src/marketing/price-rule-catalog-scheduled-changes.md
Labels: 2.4.3, Progress: approved

#987 Issue-978- Updated the Media Gallery Information
  src/cms/content-menu.md
  src/cms/media-gallery.md
  src/images/images-ee/admin-menu-content-ee.png
Labels: 2.4.x, Minor update, Partner: EY, Progress: approved, partners-contribution
