Repository magento/merchdocs, pull requests merged in 2021-08, with the labels that each got.

#1422 Added the link to Adobe Acrobate Reader on "Creating an Invoice" page
  src/sales/invoice-create.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1425 Added information about how to delete an address in customer's account
  src/customers/account-dashboard-address-book.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1430 Updated Basic Customer Account Options
  src/customers/account-options-new.md
  src/images/images/config-customers-customer-configuration-create-new-account-options.png
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1432 Removing the wrong markdown syntax
  src/marketing/seo-search.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1444 Fix broken links
  src/catalog/product-create-grouped.md
  src/sales/transactions.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1428 Added the point about deleting permission rules for categories
  src/catalog/catalog-shared-category-permissions-update.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1431 New topic about how to Add GTM (Google Tag Manager) For Magento 2 Stores
  src/_data/toc/marketing.yml
  src/images/images-ee/footer-tag-section.png
  src/images/images-ee/head-tag.png
  src/images/images-ee/install-google-tag-manager.png
  src/marketing/google-tag-manager-troubleshooting.md
  src/marketing/google-tag-manager.md
Labels: Major update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1433 Add description about steps to translate product attribute and attribute options in Magento 2
  src/catalog/product-translate.md
  src/images/images/manage-label-tab.png
  src/images/images/manage-option-tab.png
Labels: Major update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1436 Added additional info about blocks managing
  src/cms/block-add.md
Labels: Major update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1437 Added Additional Info About Billing Agreements
  src/images/images/sales-billing-agreement-related-orders-tab.png
  src/images/images/sales-billing-agreement-view.png
  src/images/images/sales-billling-agreements.png
  src/sales/billing-agreements.md
Labels: Major update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1438 Add steps about how to Remove Filterable Attribute Values with 0 Products from Layered Navigation
  src/catalog/navigation-layered-filterable-attributes.md
  src/images/images/filterable-attributes-on-plp.png
  src/images/images/storefront-properties-tab.png
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1441 The absence of spaces breaks the structure of the fields on the Product Export Attributes Reference page
  src/system/data-attributes-product.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1452 Added additional informations about how to delete customer segments, fixed a typo
  src/marketing/customer-segment-create.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1453 Added additional information for customer segment reports page
  src/reports/customer-segment-reports.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1439 Transactions: Fixed the broken link, added additional info
  src/sales/transactions.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1440 Added additional information to search report page
  src/marketing/search-terms-report.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1442 Add clarification how to set up comments for shipment
  src/images/images/shipment-coments.png
  src/sales/shipments-create.md
Labels: Major update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1443 Add the Credit Memos grid control description
  src/sales/credit-memos.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1448 Describe the payment gateway method for the stores
  src/payment/paypal.md
Labels: small changes, partners-contribution, Progress: approved, Partner: Atwix
