Repository magento/merchdocs, pull requests merged in 2021-06, with the labels that each got.

#1280 Update the Setting Up a Gift Registry page
  src/marketing/gift-registry-create.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1281 Providing more detailed information for transactions grid, data, details, and Childs
  src/sales/transactions.md
Labels: 2.4.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#1284 Add columns description to the Customer Segment Report
  src/reports/customer-segment-reports.md
Labels: 2.4.x, Minor update, Progress: approved

#1286 Update the catalog Scheduled Changes pages
  src/catalog/category-scheduled-changes.md
  src/catalog/product-scheduled-design-update.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#1291 Add the SMS Sends Report field to the Customer Engagement Reporting page
  src/reports/customer-engagement.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1328 Update the list of the Actions Control grid page
  src/stores/admin-actions-control.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1296 Add a hint for users about using the canonical URL
  src/marketing/url-rewrite-configuration.md
Labels: Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1282 Issue # 1065| Adding a block to the slider documentation
  src/cms/page-builder-media-slider.md
  src/images/images-ee/insert-widget-to-slide-page.png
  src/images/images-ee/inserting-widget-on-slide.png
Labels: 2.4.x, Major update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1294 Updated weird sentence structure on getting started
  src/getting-started.md
Labels: 2.4.x, Editorial, Progress: acceptance testing

#1295 Issue #1104 | Update user guide to include information about sitemaps and robots.txt for multistore configuration
  src/marketing/sitemap-xml.md
Labels: 2.4.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#1301 Small edits for the Company Accounts block
  src/customers/account-company-roles-permissions.md
  src/customers/account-company-users-team.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, Progress: approved, partners-contribution

#1334 Remove duplicate content
  src/catalog/product-create-simple.md
Labels: 2.4.x, Editorial, Progress: acceptance testing

#1288 Mer/new checkout 1272
  src/_data/toc/getting-started.yml
  src/images/images/storefront-checkout-payment-full.png
  src/images/images/storefront-checkout-shipping-full.png
  src/quick-tour/checkout-page.md
  src/quick-tour/path-to-purchase.md
Labels: 2.4.x, New topic, Partner: Ziffity, Progress: acceptance testing, partners-contribution

#1306 Describe how to update the reward points balance
  src/customers/account-dashboard-reward-points.md
  src/images/images-ee/reward-points-balance.png
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1307 Add instruction to set the country options for specific delivery method
  src/images/images/country-options-for-specific-delivery-method.png
  src/stores/country-options.md
Labels: 2.4.x, Major update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1312 Describe how to add a product with configuration for the Managing a Shopping Cart page
  src/sales/shopping-assisted-cart-manage.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1313 Issue#47: Improve Top Navigation content
  src/catalog/navigation-top.md
  src/catalog/navigation.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1338 Update the image on the Using Reward Points in Price Rules page
  src/images/images-ee/reward-points-price-rule-actions.png
  src/marketing/reward-points-price-rules.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1344 Update security-scan.md
  src/images/images/magento-security-scan-add-site1.png
  src/images/images/magento-security-scan-add-site2.png
  src/images/images/magento-security-scan-code-PWA.png
  src/magento/security-scan.md
Labels: 2.4.x, MQR, Major update, Progress: approved

#1316 Update the Purchase Order field for the Company Credits pages
  src/customers/credit-company-activity.md
  src/customers/credit-company-reimburse.md
  src/images/images-b2b/company-credit-reimbursements-grid.png
  src/images/images-b2b/company-reimburse-balance.png
Labels: 2.4.0, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1330 Update missing Email Template List
  src/marketing/email-template-list.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1335 Add list of tabs for the Customer information block
  src/customers/customer-account-update.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1309 Update the Managing Customer Accounts page
  src/customers/customer-account-manage.md
  src/images/images/customers-grid-quick-edit.png
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, Progress: approved, partners-contribution

#1348 Remove b2b label from customer page images
  src/customers/customers-all.md
  src/customers/customers-menu.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1349 658 Add clarification on the merge js and css files from Admin
  src/design/merge-css.md
  src/design/merge-javascript.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, Progress: approved, partners-contribution

#1351 Update the SCOPE columns on the Developer page
  src/configuration/advanced/developer.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, Progress: approved, partners-contribution

#1325 2.3.x - Update installation.md
  src/magento/installation.md
Labels: 2.3.x, Editorial, Progress: acceptance testing

#1336 Add field descriptions to the content block pages
  src/cms/page-hierarchy-configure.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1337 Update the Related Product Rules page and add columns description
  src/marketing/product-related-rules.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1355 Update screenshots for product reservations
  src/images/images/inventory/inventory-diagram-complicated-order.png
  src/images/images/inventory/inventory-diagram-simple-order.png
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#1359 Update saas.md
  src/configuration/services/saas.md
Labels: Editorial, Progress: acceptance testing

#1298 Move company credit page and store credit page to the customer block
  src/_data/toc/customers.yml
  src/_data/toc/sales.yml
  src/configuration/customers/customer-configuration.md
  src/customers/account-dashboard-gift-cards.md
  src/customers/credit-company-activity.md
  src/customers/credit-configure.md
  src/customers/refunds-customer-account.md
  src/customers/store-credit-using.md
  src/customers/store-credit.md
  src/quick-tour/customer-retention.md
  src/sales/credit-memo-create.md
  src/sales/credit-memos.md
  src/sales/rma-customer-experience.md
Labels: 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1303 Update the Managing a Shopping Cart page and the Creating an Order page from the Shopping Assistance block
  src/customers/customer-account-create-order.md
  src/sales/shopping-assisted-cart-manage.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1329 Add columns to the Billing Agreements page
  src/sales/billing-agreements.md
Labels: Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1343 Edit invalid link on the About This Release page
  src/magento/about-this-release.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, Progress: approved, Progress: on hold, partners-contribution
