Repository magento/merchdocs, pull requests merged in 2021-11, with the labels that each got.

#1563 Added Additional information to category scheduled changes
  src/catalog/category-scheduled-changes.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1580 Describe the benefits of the Group Price
  src/catalog/product-price-group.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1585 Fixed missing link for Google Maps on adding sources page
  src/catalog/inventory-sources-add.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1587 Add correct Product Alert link to the Catalog Configuration list
  src/configuration/catalog/catalog.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1591 Fix markdown issues
  src/cms/editor-insert-link.md
  src/cms/page-builder.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix

#1595 Update product-image-upload.md
  src/catalog/product-image-upload.md
Labels: Editorial, Progress: acceptance testing

#1600 clarification on diff Recs source
  src/marketing/recommendation-change-source.md
Labels: Editorial, Progress: approved, 2.4.x

#1572 Update the Configuring Quotes topic
  src/stores/b2b-configure-quotes.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1578 Describe how to add CMS block to the Category page
  src/catalog/categories-content-settings.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1582 Add the missing columns to the customer configuration list
  src/configuration/catalog/catalog.md
  src/configuration/catalog/xml-sitemap.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1588 Describe how to enable the newsletter feature in the admin panel
  src/marketing/newsletter-configuration.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix

#1590 Expand best practises for Product attributes
  src/catalog/attribute-best-practices.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1597 Add warning for users of Google reCAPTCHA version 3 with low score
  src/configuration/security/google-recaptcha-admin.md
  src/configuration/security/google-recaptcha-storefront.md
Labels: Minor update, partners-contribution, Progress: approved, 2.4.x, Partner: Fisheye

#1601 Fix the product types included in the Grouped product type
  src/catalog/product-create-grouped.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1583 Add notices about weight and links for the Downloadable products topic
  src/catalog/product-create-downloadable.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1584 Describe how to set up a confirmation email for new customers
  src/customers/account-create.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1589 Describe how to allow company registration from the storefront
  src/customers/account-company-create.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1594 Describe how to set up the Order Approval Configuration
  src/customers/account-dashboard-approval-rules.md
  src/stores/b2b-features.md
Labels: Major update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1603 ACP2E-269: UPS shipping rate calculation error
  src/shipping/fedex.md
  src/shipping/ups.md
Labels: Minor update, Progress: approved, 2.4.x, Stakeholder

#1604 Added additional information to Data Collector Page
  src/system/support-data-collector.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1607 Described how to Re-Authorize active integration
  src/system/integrations.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1608 Fixed the link for Private Sales Report page
  src/reports/reports-menu.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1612 Update site-wide-analysis-tool.md
  src/reports/site-wide-analysis-tool.md
Labels: Editorial, internal-dev, Progress: acceptance testing, Progress: ready for review

#1619 Clarify password reset expiration TTL
  src/customers/password-reset.md
Labels: Editorial, partners-contribution, Progress: acceptance testing, Partner: Visma Digital Commerce

#1581 Describe how to add an event to category, on the Categories page
  src/catalog/category-modify.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1609 ACP2E-160: [Cloud] Shipping prices quoted in UPS doesn't match Magento Checkout page
  src/shipping/fedex.md
  src/shipping/ups.md
Labels: Editorial, Progress: approved, internal-dev

#1611 Added additional information to Tax Rates page
  src/tax/tax-zones-rates.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1614 Added additional information to Invitations page
  src/marketing/invitations.md
Labels: partners-contribution, Progress: approved, Partner: Atwix

#1620 Update the action list of the Admin Actions Logging block, on the (Advanced)Admin page
  src/configuration/advanced/admin.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix

#1592 Add description about the common types of breadcrumbs
  src/catalog/navigation-breadcrumb-trail.md
Labels: Major update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1602 Add missing tab and notices for the Product Settings block
  src/catalog/settings.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1605 Scheduling an Export: Described configuring export if remote server was selected. Updated entity types
  src/system/data-schedule-export.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1621 ACP2E-333: [Documentation] Mention that reward points in cart price rule are added once per each order
  src/marketing/price-rules-cart-create.md
Labels: Editorial, Progress: approved, internal-dev, 2.4.x

#1622 Added additional information to order-ship page. Fixed spelling mistake
  src/sales/order-ship.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1624 ACP2E-338: [Documentation] Add notice that mini cart may be not synchronized across the multiple devices and browsers
  src/sales/mini-cart.md
Labels: Minor update, Progress: approved, internal-dev, 2.4.x

#1626 ACP2E-339: [Documentation] Add clarification that automatic sorting is applied to the category by the "Save Category" button only
  src/catalog/categories-category-products.md
Labels: Minor update, Progress: approved, internal-dev, 2.4.x

#1629 Update the Wish List Search page information and describe the difference between private and public wishlist
  src/customers/account-dashboard-my-wish-list.md
  src/marketing/wishlist-search.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1630 Update the Payment Methods columns
  src/configuration/sales/braintree.md
  src/configuration/sales/paypal-express-checkout.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1631 removing info on reusing data spaces
  src/system/saas.md
Labels: Minor update, Progress: approved, internal-dev
