Repository magento/merchdocs, pull requests merged in 2021-05, with the labels that each got.

#1192 Change the Shopping Cart Sidebar field to the Mini Cart field
  src/_data/toc/sales.yml
  src/configuration/sales/braintree.md
  src/configuration/sales/checkout.md
  src/images/images/config-sales-checkout-shopping-cart-sidebar.png
  src/images/images/config-sales-mini-cart.png
  src/payment/amazon-pay-customer-experience.md
  src/sales/cart-configuration.md
  src/sales/cart-link.md
  src/sales/cart-redirect.md
  src/sales/mini-cart.md
  src/stores/cookie-reference.md
Labels: Partner: Atwix, Progress: acceptance testing, partners-contribution

#1200 Describing of available checkout option
  src/sales/checkout-options.md
Labels: Minor update, Progress: acceptance testing

#1241 Update the General Options section of the wish list configuration page
  src/images/images/config-customers-wishlist-general-options.png
  src/marketing/wishlist-configuration.md
Labels: Minor update, Partner: Atwix, Progress: acceptance testing, Progress: approved, partners-contribution

#1173 magento/merchdocs#1165: Shipping an Order | Describe the Track Order feature
  src/images/images-b2b/sales-order-ship-tracking-information.png
  src/sales/order-ship.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1185 Add a new page My Returns to the Company Account Dashboard block
  src/_data/toc/customers.yml
  src/customers/account-dashboard-my-returns.md
  src/images/images/create-new-return.png
  src/images/images/my-orders-returns.png
  src/images/images/my-returns-page.png
Labels: 2.4.x, New topic, Partner: Atwix, Progress: approved, partners-contribution

#1193 Edits to the login as a customer page.
  src/configuration/customers/login-as-customer.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1231 Replacing outdated image for Catalog Images and Video topic
  src/images/images/product-images-videos-swatch.png
Labels: Partner: Atwix, Progress: approved, partners-contribution

#1208 Updating an invitation information
  src/customers/account-dashboard-my-invitations.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1209 Company Users upgrade
  src/customers/account-dashboard-company-users.md
  src/images/images-b2b/customer-account-dashboard-company-users.png
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1219 Describe the method to add stored payment method from checkout
  src/customers/account-dashboard-stored-payment-methods.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1221 Clarification of the customer's reports (Order Total, New, Order Count, Wish Lists, Segments)
  src/reports/customer-reports.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1222 Remove the "Magento Commerce only" tag from the Customer Accounts page
  src/customers/customer-account.md
Labels: 2.4.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#1195 Column descriptions for invoices
  src/sales/invoices.md
Labels: 2.4.x, Major update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1199 Filling in missing email templates for Magento Company and Magento Company Credit blocks
  src/marketing/email-template-list.md
Labels: Editorial, Progress: acceptance testing

#1271 Removed misleading infromation from adobe stock configuration instructions
  src/cms/adobe-stock.md
Labels: 2.4.x, Minor update, Port change, Progress: acceptance testing, Stakeholder

#1194 Export archived orders workflow
  src/sales/order-archive.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1223 Update to actual version of the supported email clients
  src/_data/toc/marketing.yml
  src/marketing/email-clients-supported.md
  src/marketing/email-templates.md
Labels: 2.4.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#1224 Describe the Startup Page block options from Advanced > Admin page
  src/configuration/advanced/admin.md
Labels: 2.4.x, Major update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1225 Add column description for the Customer Segment page
  src/marketing/customer-segment-create.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1236 Add fields descriptions for other settings pages
  src/catalog/product-configurations.md
  src/catalog/product-scheduled-design-update.md
  src/catalog/settings-advanced-product-reviews.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#1289 Fixing NewRelic queries
  src/reports/new-relic-queries.md
Labels: Editorial, Partner: Comwrap, Progress: acceptance testing, partners-contribution

#1299 Update inventory-product-alert-run-settings.md
  src/catalog/inventory-product-alert-run-settings.md
Labels: Editorial, Progress: acceptance testing, internal-dev

#1244 Deleting a "Custom Pricing" topic that duplicates another same topic in the Catalog section
  src/_data/toc/catalog.yml
  src/catalog/product-price-custom.md
Labels: Editorial, Partner: Atwix, Progress: approved, partners-contribution

#1246 Content filling and navigation for the Managing Price section
  src/catalog/pricing.md
Labels: 2.4.x, Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1258 Update link the Archive order link on the Sales Menu page
  src/sales/sales-menu.md
  src/stores/admin-dashboard.md
Labels: Editorial, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1268 Column description for the Return page
  src/sales/returns.md
Labels: Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1237 Describe the properties for product and customer attributes
  src/stores/attribute-product-create.md
  src/stores/attributes-customer.md
Labels: 2.4.x, Event: Adobe Summit Hackathon, Major update, Partner: Atwix, Progress: approved, partners-contribution

#1250 Update the Address Book topic
  src/customers/account-dashboard-address-book.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1308 Add the "Show my Quotes" block for the My Quotes page
  src/customers/account-dashboard-quotes.md
Labels: Minor update, Partner: Atwix, Progress: acceptance testing, Progress: approved, partners-contribution

#1252 Update the Adding a New Page and the Switching Home pages
  src/cms/page-add.md
  src/cms/page-home-new.md
  src/images/images/page-design.png
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1206 magento/merchdocs#1010: Add the Open Source only tag to the Apply a special price to multiple products block
  src/catalog/product-price-special.md
  src/images/images/product-price-special-commerce.png
Labels: 2.4.x, Major update, Progress: approved

#1249 Update the Workspace Controls and the Scheduled Changes pages
  src/cms/page-scheduled-changes.md
  src/cms/pages-workspace.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1266 Move the Company Credit pages to the Customer block
  src/_data/toc/customers.yml
  src/_data/toc/sales.yml
  src/configuration/customers/company-configuration.md
  src/customers/account-dashboard-company-credit.md
  src/customers/credit-company-activity.md
  src/customers/credit-company-reimburse.md
  src/customers/credit-company.md
Labels: 2.4.x, Editorial, Partner: Atwix, Progress: approved, partners-contribution

#1260 Add topic about Reorder from the Storefront
  src/_data/toc/customers.yml
  src/customers/account-dashboard-reorders.md
  src/images/images/account-dashboard-reorder-grid.png
  src/images/images/account-dashboard-reorder.png
Labels: 2.4.x, New topic, Partner: Atwix, Progress: approved, partners-contribution

#1262 Column description for the Shipment page
  src/sales/shipments.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1267 Column description for Default Pages configuration
  src/cms/pages-default.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1143 magento/merchdocs | Fix typos
  src/marketing/google-tag-manager.md
Labels: Progress: acceptance testing

#1269 Big update for the System section
  src/_data/main-nav.yml
  src/_data/toc/content.yml
  src/_data/toc/operations.yml
  src/content.md
  src/system/custom-variables.md
  src/system/media-storage-content-delivery-network.md
  src/system/media-storage-database.md
  src/system/media-storage.md
  src/system/notifications.md
  src/system/other-settings.md
  src/system/system.md
Labels: 2.4.x, New topic, Partner: Atwix, Progress: acceptance testing, partners-contribution

#1270 Issue #1255 | Expanding of the benefits of the Company Accounts
  src/customers/account-companies.md
Labels: 2.4.x, Major update, Partner: Atwix, Progress: approved, partners-contribution

#1274 Issue#923 Update VAT configuration page
  src/tax/vat-configure.md
Labels: Partner: Atwix, Progress: approved, partners-contribution

#1276 magento/merchdocs#60: Update product review information
  src/images/images/catalog-rating-page.png
  src/images/images/edit-review-page.png
  src/marketing/magento-product-reviews-config.md
  src/marketing/magento-product-reviews-moderate.md
  src/stores/attributes-rating.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1277 Add Braintree block to the Sales Menu page
  src/images/images-b2b/admin-menu-sales-b2b.png
  src/sales/sales-menu.md
Labels: 2.4.x, Minor update, Partner: Atwix, Progress: approved, partners-contribution

#1278 Update the creating category rules page
  src/catalog/category-product-rules.md
  src/images/images-ee/automatic_sorting_field.png
Labels: Partner: Atwix, Progress: approved, partners-contribution

#1310 Fix handling fee for "percentage" type of Shipping Flat Rate
  src/shipping/shipping-flat-rate.md
Labels: Editorial, Progress: acceptance testing, Progress: approved

#1311 Change title of the section in klarna-setup.md
  src/payment/klarna-setup.md
Labels: Editorial, Progress: acceptance testing, Progress: approved
