Repository magento/merchdocs, pull requests merged in 2022-02, with the labels that each got.

#1672 Expand the Import History topic with field description and instruction, how to download Imported/Error file
  src/system/data-import-history.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1700 Added additional information to Coupon Codes page
  src/marketing/price-rules-cart-coupon.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1701 Added additional information to related products page
  src/catalog/related-products-up-sells-cross-sells.md
Labels: partners-contribution, Partner: Atwix, Progress: acceptance testing

#1705 Edited and added additional information on Create Shared Catalog page
  src/catalog/catalog-shared-create.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing
