Repository magento/merchdocs, pull requests merged in 2022-01, with the labels that each got.

#1652 ACP2E-411: [Documentation] Mention that Not Visible Individually products can be reordered
  src/customers/account-dashboard-reorders.md
  src/sales/reorders-allow.md
Labels: Editorial, internal-dev, Progress: acceptance testing

#1653 Update columns for the Credit Memos page
  src/sales/credit-memo-print.md
  src/sales/credit-memos.md
Labels: partners-contribution, Partner: Atwix, Progress: acceptance testing

#1655 Fix typo in page builder tutorial
  src/cms/page-builder-tutorial1-simple-page.md
Labels: Editorial, Progress: approved, Progress: acceptance testing, Progress: on hold

#1659 Fixed typos for Duplicating and Deleting a Page
  src/cms/page-duplicate.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1660 Added Columns Description to Newsletter queue page
  src/marketing/newsletter-queue.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1661 Fixed duplicate link on Content page
  src/content.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1662 Added additional notice to zero subtotal checkout page
  src/payment/zero-subtotal-checkout.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1663 Corrected a shipment creating flow
  src/sales/shipments-create.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1656 ACP2E-436: [Documentation] Add clarification that all category permissions are set to Deny for all customer groups by Shared Catalog enabling
  src/catalog/catalog-shared-category-permissions-update.md
  src/catalog/catalog-shared.md
Labels: Editorial, internal-dev, Progress: acceptance testing

#1657 Edited outdated Grid Layout Info, added new information
  src/stores/admin-grid-controls.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1658 Described the steps how to Prioritize the sources
  src/catalog/inventory-stock-priority.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1666 Added additional steps for assigning a source for a product info
  src/catalog/sources.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, Progress: acceptance testing

#1670 Added missing Entity Type
  src/system/data-export.md
Labels: Minor update, Progress: approved, 2.4.x

#1671 Describe how to cancel order with items from backorders salable qty
  src/catalog/inventory-backorders.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1673 Describe difference between customer group and customer segment
  src/customers.md
  src/marketing/customer-segments.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1677 Add links to the Scope page
  src/configuration/scope.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1682 Update the Two-Factor Authentication page information
  src/stores/security-two-factor-authentication.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, Progress: on hold, 2.4.x

#1684 Add base thing to remember to the Websites, Stores, and Views page
  src/stores/websites-stores-views.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix, 2.4.x

#1685 Update the order editing information
  src/sales/order-processing.md
  src/sales/order-update.md
Labels: partners-contribution, Progress: approved, Partner: Atwix

#1688 Added additional information to product reviews page. [Cloned from /1665]
  src/marketing/magento-product-reviews-moderate.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix

#1692 Added additional info to customer engagement page [CLONE OF /pull/1675]
  src/reports/customer-engagement.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1694 Edited Catalog Price Rule page style [CLONE OF pull/1678/]
  src/marketing/price-rules-catalog.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1695 Added additional note to share catalog price rules preview [CLONE OF pull/1679]
  src/marketing/price-rule-catalog-scheduled-changes.md
Labels: Editorial, partners-contribution, Progress: approved, Partner: Atwix

#1681 Update scope columns of the Advanced configuration block
  src/configuration/advanced/admin.md
  src/configuration/advanced/developer.md
  src/configuration/advanced/system.md
Labels: partners-contribution, Partner: Atwix, Progress: acceptance testing

#1693 Edit pages of the Operations pages
  src/stores/security-two-factor-authentication-manage.md
  src/system/data-export.md
Labels: Editorial, partners-contribution, Partner: Atwix, Progress: acceptance testing

#1690 Added additional information to reward points pages [CLONE OF pull/1669]
  src/customers/account-dashboard-reward-points.md
  src/customers/assets/reward-points-on-checkout.png
  src/marketing/reward-points-price-rules.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x

#1691 Added additional information to Comparison List page [CLONE OF /pull/1674]
  src/catalog/assets/compare-products-header.png
  src/catalog/assets/notification-comparison-list.png
  src/customers/assets/my-account-compare-block.png
  src/marketing/product-compare.md
Labels: Minor update, partners-contribution, Progress: approved, Partner: Atwix

#1696 Update the Google Tag Manager page
  src/marketing/google-tag-manager.md
Labels: Minor update, partners-contribution, Partner: Atwix, Progress: acceptance testing, 2.4.x
